### ISSUE TITLE
Not pulling all audio books from my library

### ISSUE THREAD

**Issue by Mizmelzy** [rmcrackan/Libation#1016]
I have books that are in my library that are not being pulled up. I can play and listen to them online, but they are not showing when I go to import< Scan Library.  It scans but does not pull anything else in.  I have tried deleting my audible account and re-adding it. Still nothing new pops up.

It should pull the new additions to my library in and it is not.

I did find a zip file with todays date which I think is a log file but I can't open it

[_Log202410.zip](https://github.com/user-attachments/files/17499368/_Log202410.zip)
[_Log202410_001.zip](https://github.com/user-attachments/files/17499369/_Log202410_001.zip)

Thank you.
Melissa

**Comment by rmcrackan** [comment]
Sorry about this

* Did they accidentally get put into the trash bin? Check in: Settings > Trash bin
* Are they being hidden by the search filter?

@Mbucari : There are also a handful of these. Do they look familiar to you? I assume it's not the same as that other mac issue because this is windows classic:

```

 {}2024-10-23 18:59:23.551 -05:00 [ERR] (at Dinah.Core.StepRunner.AsyncBaseStep+<RunAsync>d__2.MoveNext()) End step 'Step 1: Get Aaxc Metadata'. FAILED. Completed in 00:00:00
System.IO.EndOfStreamException: Stream ended before all 4 bytes could be read
   at Mpeg4Lib.Util.StreamExtensions.Read(Stream stream, Span`1 buffer, Int32 size) in /home/runner/work/AAXClean/AAXClean/src/Mpeg4Lib/Util/StreamExtensions.cs:line 126
   at Mpeg4Lib.Util.StreamExtensions.ReadInt32BE(Stream stream) in /home/runner/work/AAXClean/AAXClean/src/Mpeg4Lib/Util/StreamExtensions.cs:line 89
   at Mpeg4Lib.Boxes.BoxHeader..ctor(Stream file) in /home/runner/work/AAXClean/AAXClean/src/Mpeg4Lib/Boxes/BoxHeader.cs:line 29
   at Mpeg4Lib.Boxes.BoxFactory.CreateBox(Stream file, IBox parent) in /home/runner/work/AAXClean/AAXClean/src/Mpeg4Lib/Boxes/BoxFactory.cs:line 41
   at Mpeg4Lib.Util.Mpeg4Util.LoadTopLevelBoxes(Stream file) in /home/runner/work/AAXClean/AAXClean/src/Mpeg4Lib/Util/Mpeg4Util.cs:line 26
   at AAXClean.Mp4File..ctor(Stream file, Int64 fileSize) in /home/runner/work/AAXClean/AAXClean/src/AAXClean/Mp4File.cs:line 66
   at AAXClean.AaxFile..ctor(Stream file, Int64 fileSize, Boolean additionalFixups) in /home/runner/work/AAXClean/AAXClean/src/AAXClean/AaxFile.cs:line 20
   at AaxDecrypter.AaxcDownloadConvertBase.Step_GetMetadata() in D:\a\Libation\Libation\Source\AaxDecrypter\AaxcDownloadConvertBase.cs:line 34
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dinah.Core.StepRunner.AsyncBasicStep.RunRawAsync()
   at Dinah.Core.StepRunner.AsyncBaseStep.RunAsync()
 {"ExceptionDetail":{"Type":"System.IO.EndOfStreamException","HResult":-2147024858,"Message":"Stream ended before all 4 bytes could be read","Source":"Mpeg4Lib","TargetSite":"Int32 Read(System.IO.Stream, System.Span`1[System.Byte], Int32)"}}2024-10-23 18:59:23.553 -05:00 [ERR] (at Dinah.Core.StepRunner.AsyncBaseStep+<RunAsync>d__2.MoveNext()) End step 'Download and Convert Aaxc To M4b'. FAILED. Completed in 00:00:00
```

**Comment by Mbucari** [comment]
@rmcrackan 
Look above those lines. The download was cancelled so the network stream was closed. The parser knows how big the block is supposed to be from the header, but it's unable to read that much data.
```
 {}2024-10-23 18:59:21.192 -05:00 [INF] (at AaxDecrypter.NetworkFileStream+<DownloadFile>d__53.MoveNext()) Download was cancelled
 {}2024-10-23 18:59:21.196 -05:00 [ERR] (at Dinah.Core.StepRunner.AsyncBaseStep+<RunAsync>d__2.MoveNext()) End step 'Step 1: Get Aaxc Metadata'. FAILED. Completed in 00:00:00
```

**Comment by rmcrackan** [comment]
@Mbucari Ah, thanks. I thought that would have been an awfully weird coincidence to come up the same week as that other one.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
