### ISSUE TITLE
Crash: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by gitliba** [rmcrackan/Libation#1017]
I get the following crash: Object reference not set to an instance of an object.

I have a lot of titles not marked as downloaded due to a reinstall, so they try to re-download when I restart the program. Can I bulk select a large range of titles as "Not to be processed" during auto-download?  I think I could avoid this bug if it was not trying to process so many files.  

**Describe the bug**
Crashes during use:

**To Reproduce**
Run program

**Expected behavior**
I'd like to be able to mark a large range of files as Not To Be Processed with a shift-click. 

**Screenshots**
![image](https://github.com/user-attachments/assets/18de97ad-2048-4ad9-958a-b83f3786814a)

**Platform**

Windows 10

Log file too big to upload - 45mb

Crash listing: 

Object reference not set to an instance of an object.
 
   at LibationWinForms.GridView.ProductsGrid.GetVisibleBooks() in D:\a\Libation\Libation\Source\LibationWinForms\GridView\ProductsGrid.cs:line 36
   at LibationWinForms.Form1.setLiberatedVisibleMenuItem() in D:\a\Libation\Libation\Source\LibationWinForms\Form1.VisibleBooks.cs:line 30
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LibationWinForms.Form1.setLiberatedVisibleMenuItemAsync(Object _, Object __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.VisibleBooks.cs:line 27
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by rmcrackan** [comment]
Sorry about this bug. Please attach your log file to this ticket.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
