### ISSUE TITLE
Could not deserialize json

### ISSUE THREAD

**Issue by momsareader** [rmcrackan/Libation#1023]
Could not deserialize json: 

   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Form1.refreshImportMenu(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by rmcrackan** [comment]
Sorry about this. Unfortunately I've seen this before. Your `AccountsSettings.json` file got corrupted. This is the file where your account login is stored. To fix it, just delete this file, restart Libation, and recreate your account/s (Settings > Accounts). You'll need to log in again; no books or other settings will be lost.

If you can't find this file: go to Libation > Settings. There's a button to open the folder for your log file. AccountsSettings is in this same folder.

**Comment by momsareader** [comment]
Thank you! It's back working now. I appreciate your quick response.

Holly

**Comment by momsareader** [comment]
Now all the books that are downloading turn red. I re signed into Audible...
Holly

**Comment by rmcrackan** [comment]
That doesn't sound good. Can you attach your log file to this ticket?
