### ISSUE TITLE
Error every time - no changes 

### ISSUE THREAD

**Issue by Teapotsing** [rmcrackan/Libation#1049]
After changing nothing I’m unable to download new books, I’ve checked all settings but get the error message every time 

picture attached 

Running windows 10
![Uploading IMG_2031.jpeg…]()

**Comment by rmcrackan** [comment]
Sorry, the image didn't come through. Can you attach your log file?

**Comment by sarg3nt** [comment]
I'm also getting error downloading as of recently.  No config changes on my end either.

Note: The aliens, robots and elevating black voices books always fail and have been doing so for a LONG time.  I don't even remember purchasing them to be honest, so not sure where they came from but I'd ignore them as I doubt they are the problem.

```
LibationCli v11.5.5
ERROR
=====
Microsoft.EntityFrameworkCore.DbUpdateException
Message: An error occurred while saving the entity changes. See the inner
exception for details.
Stack Trace:
   at
   Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(I
   RelationalConnection connection)
   at
   Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerab
   le`1 commandBatches, IRelationalConnection connection)
   at
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChange
   s(IList`1 entriesToSave)
   at
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChange
   s(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at
   Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TS
   tate,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChange
   s(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean
   acceptAllChangesOnSuccess)
   at ApplicationServices.LibraryCommands.SaveContext(LibationContext context)
   in /Source/ApplicationServices/LibraryCommands.cs:line 342

   at ApplicationServices.LibraryCommands.SaveContext(LibationContext context)
   in /Source/ApplicationServices/LibraryCommands.cs:line 353
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems)
   in /Source/ApplicationServices/LibraryCommands.cs:line 327
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2
   apiExtendedfunc, Account[] accounts) in
   /Source/ApplicationServices/LibraryCommands.cs:line 144
   at LibationCli.ScanOptions.ProcessAsync() in
   /Source/LibationCli/Options/ScanOptions.cs:line 35
   at LibationCli.OptionsBase.Run() in
   /Source/LibationCli/Options/_OptionsBase.cs:line 15

scan Usage:

  --help               Display this help screen.

  Accounts (pos. 0)    Optional: user ID or nicknames of accounts to scan.


Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
2024-11-20 11:53:07 info: initializing libation
2024-11-20 11:53:07 info: loading AccountsSettings.json
2024-11-20 11:53:07 info: loading Settings.json
2024-11-20 11:53:07 info: loading settings
2024-11-20 11:53:07 info: setting Books to /data
2024-11-20 11:53:07 info: setting InProgress to /tmp
2024-11-20 11:53:07 info: loading database
2024-11-20 11:53:07 info: database found at /config/LibationContext.db
2024-11-20 11:53:07 info: running every 30m
2024-11-20 11:53:07 info: scanning accounts
Scanning Audible library. This may take a few minutes.
2024-11-20 11:53:24 info: liberating books
DownloadDecryptBook Begin: 05/15/2020 [B088G1N76W] Ep. 4: Aliens!
DownloadDecryptBook Completed: 05/15/2020 [B088G1N76W] Ep. 4: Aliens!
DownloadDecryptBook Begin: 05/15/2020 [B088G39G8G] Ep. 3: Robots & Artificial Intelligence
DownloadDecryptBook Completed: 05/15/2020 [B088G39G8G] Ep. 3: Robots & Artificial Intelligence
DownloadDecryptBook Begin: 05/15/2020 [B088GSYJMP] Ep. 2: Elevating Black Voices
DownloadDecryptBook Completed: 05/15/2020 [B088GSYJMP] Ep. 2: Elevating Black Voices
Done. All books have been processed
```

**Comment by rmcrackan** [comment]
It looks like it's having issues writing to the database. Can you attach your actual log file?

Also, can you try via the graphic user interface and see if it still fails?

The folder with the log files and the database file (LibationContext.db), is there some software possibly locking files in that? Like a file sync'ing service like dropbox/gdrive/icloud?

**Comment by sarg3nt** [comment]
@rmcrackan   I use the Docker image and didn't realize the `latest` pulled pre-releases versions and looks like there are some breaking changes.
https://github.com/rmcrackan/Libation/blob/master/Documentation/Docker.md
I know relying on `latest` is bad practice.  I was being lazy.  :)
Reverting to 11.1.0 fixed it.
Should we be trying to run the pre-release version or would you recommend  against it?

Sorry no logs.  I couldn't find them in the data folder I have mounted for the container.  There were a bunch of old logs but no new ones.   Now that I've reverted I see new log files being generated though.
I'm guessing if I add the user:group perms the `Docker.md` file mentioned the latest version would work.  I can try that but am wondering what your recommendation would be, should we run pre-release?
If your recommendation is to not run pre-release you probably want to change your pipeline to not tag pre-release images as latest.

**Comment by rmcrackan** [comment]
> Should we be trying to run the pre-release version or would you recommend against it?

They're *usually* safe, but y'know -- they're pre-release for a reason.

Also, officially docker is unsupported. I want to get it right but I don't use docker and I offer it only as a convenience. I didn't write any of the docker stuff; other people did. So I'm not sure what sets it to 'latest' or in what way I should change it. I'll ask those folks if they know the cure. (It's unsupported, but I'd like it to be correct if I can help it.)

**Comment by sarg3nt** [comment]
Fixing the file permissions fixed the issues with latest version.  Just an FYI to everyone.
I just did a 
`chown -R 1001:1001 <my libation data folder>`
and
`chown -R 1001:1001 <my book data folder>`
and that fixed it.

**Comment by pixil98** [comment]
As the author of the docker changes, they should be ready to use. I've been running them in my production deployment for a few weeks now and haven't had any problems. I'm not sure what goes into whether a release of Libation is flagged as a pre-release or not, but I expect we should not be tagging images as latest for pre-releases. Looking at the pipeline, it doesn't have any knowledge of whether it's a pre-release or not. It would require some changes and likely need to key off of something in the tag name.

With all that said, is there a better way we could have released this that would have not broken your deployments? It seems like any breaking change would have been a problem when using the latest tag. If we hadn't built the latest tag now, this would eventually make it into the next full release and cause a breaking change with the latest tag then.

@rmcrackan do you follow Semantic Versioning when making releases? Maybe it should have been a major version bump to indicate that there was breaking change. This wouldn't have helped with the latest tag though. The semver [spec](https://semver.org/#spec-item-9) also covers what a pre-release version should look like. The pipeline could be updated to check that and handle it differently.

**Comment by rmcrackan** [comment]
Every release gets its version from here:

https://github.com/rmcrackan/Libation/blob/eadf7cff79308b80ba19c332871c3c237521eca7/Source/AppScaffolding/AppScaffolding.csproj#L5

I don't use the hyphen stuff for pre-releases because unfortunately, the full release vs pre-release step can only happen directly on github. It's separate from my build process. I start a build and after it's entirely successful, I have to go to github where it's a "draft". Then I choose how to handle the draft: release, pre-release, or discard. I actually like it because it can be a pre-release until I feel like flipping the switch and make the same one a full release without needing another cycle. Or, as has happened before, if there's something wrong with a release I can turn it back into a pre-release so the auto-updater won't grab it.

**Comment by Teapotsing** [comment]
> Sorry, the image didn't come through. Can you attach your log file?

![IMG_2031](https://github.com/user-attachments/assets/356f4ffd-7ee7-4607-9121-a77b303409a3)



sorry! It’s just this for every book at the moment, I’m not at all techy so it might be me

**Comment by rmcrackan** [comment]
Since it looks like you’re using Windows, the log files are probably in `C:\Users\[username]\Libation`. Please attached the latest log file to this ticket.

I am about to be out of town for a while so no rush. And I’ll look at your log when I return.

**Comment by jdietz02** [comment]
> Fixing the file permissions fixed the issues with latest version. Just an FYI to everyone. I just did a `chown -R 1001:1001 <my libation data folder>` and `chown -R 1001:1001 <my book data folder>` and that fixed it.

I try this and get an 'Operation not permited'

**Comment by wtanksleyjr** [comment]
What operating system are you running on? If you're running on Linux, does the command `id` run from a command line print some output you could copy here?

**Comment by jdietz02** [comment]
Docker

**Comment by jdietz02** [comment]
im sorry new to Doker so im not sure

**Comment by jdietz02** [comment]
id
uid=1001 gid=1001 groups=1001

ls -l
lrwxrwxrwx   1 root root      7 Nov 10 18:00 bin -> usr/bin
drwxr-xr-x   1 root root      0 Oct 31 06:04 boot
drwxr-xr-x   1   99 users   152 Dec  5 12:23 config
drwxrwxrwx   1 root root    104 Dec  5 12:37 config-internal
drwxrwxrwx   1   99 users 16384 Dec  5 12:37 data
drwxr-xr-x   5 root root    340 Dec  5 12:37 dev
drwxr-xr-x   1 root root   1218 Dec  5 12:36 etc
drwxr-xr-x   1 root root      6 Nov 12 12:41 home
lrwxrwxrwx   1 root root      7 Nov 10 18:00 lib -> usr/lib
lrwxrwxrwx   1 root root      9 Nov 10 18:00 lib64 -> usr/lib64
drwxr-xr-x   1 root root  15160 Nov 19 05:43 libation
drwxr-xr-x   1 root root      0 Nov 10 18:00 media
drwxr-xr-x   1 root root      0 Nov 10 18:00 mnt
drwxr-xr-x   1 root root      0 Nov 10 18:00 opt
dr-xr-xr-x 453 root root      0 Dec  5 12:37 proc
drwx------   1 root root     30 Nov 10 18:00 root
drwxr-xr-x   1 root root      8 Nov 10 18:00 run
lrwxrwxrwx   1 root root      8 Nov 10 18:00 sbin -> usr/sbin
drwxr-xr-x   1 root root      0 Nov 10 18:00 srv
dr-xr-xr-x  13 root root      0 Dec  5 12:37 sys
drwxrwxrwt   1 root root     72 Dec  5 12:38 tmp
drwxr-xr-x   1 root root     94 Nov 10 18:00 usr
drwxr-xr-x   1 root root     90 Nov 10 18:00 var

**Comment by wtanksleyjr** [comment]
OK, it looks like you're running Docker on Ubuntu Linux, so you're very close to getting this. The only problem is that you need to run `sudo chown -R 1001:1001 <my libation data folder>` and `sudo chown -R 1001:1001 <my book data folder>`, so notice the additional use of `sudo`. That gives your permission for the chown command to actually change the file permissions (it'll ask for your user password).

**Comment by wtanksleyjr** [comment]
Of course, substitute the path of your folders.

**Comment by jdietz02** [comment]
$ sudo chown 1001:1001 /data
sh: 1: sudo: not found

**Comment by wtanksleyjr** [comment]
You need to find exactly what system you're running on; it's not Ubuntu, but it's similar enough to fool me. I honestly don't know what system could put the user on 1001 and NOT provide the `sudo` command.

**Comment by MaggiWuerze** [comment]
Why exactly did the image change to user 1001 anyway? I can't just chown folders to that, other containers access it as well and they use UID 1000

**Comment by wtanksleyjr** [comment]
Yes, you would need to set Docker's external user, not chmod your stuff. Your stuff is fine. I think the documentation says how to do it.

**Comment by MaggiWuerze** [comment]
Yeah, just saw that and set it back to 1000. Thanks

**Comment by mahood73** [comment]
The docker image seems to be ignoring the 'user' parameter. I've set my docker-compose as follows:
```
services:
  libation:
    image: rmcrackan/libation:latest
    container_name: libation
    restart: unless-stopped
    user: 1000:1000
    environment:
      - SLEEP_TIME=1440m
    volumes:
      - ${APPDATA_DIR}/libation:/config
      - /mnt/media/Import/Audiobooks:/data
```
But the process still runs as UID 1001. I get the DB errors unless I chown the config folder (or at least the database) to 1001:1001...

**Comment by pixil98** [comment]
I’m on vacation for the next few days, but I’ll take a look at it when I get back.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
