### ISSUE TITLE
Trying to remove a book from Audible Library

### ISSUE THREAD

**Issue by JonGKay026** [rmcrackan/Libation#1057]
**Describe the bug**
Trying to remove a book from my library but getting the error message "The instance of entity type 'Book' cannot be tracked because another instance with the same key value for {'BookId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at ApplicationServices.LibraryCommands.removeBooks(IEnumerable`1 removeLibraryBooks) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 375
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LibationUiBase.GridView.GridContextMenu.RemoveAsync() in D:\a\Libation\Libation\Source\LibationUiBase\GridView\GridContextMenu.cs:line 74
   at LibationWinForms.GridView.ProductsDisplay.<>c__DisplayClass24_0.<<productsGrid_CellContextMenuStripNeeded>b__2>d.MoveNext() in D:\a\Libation\Libation\Source\LibationWinForms\GridView\ProductsDisplay.cs:line 146
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"

**To Reproduce**
Right clicking on the book and choosing "Remove from Library
[_Log202406.zip](https://github.com/user-attachments/files/17882717/_Log202406.zip)

**Expected behavior**
The book being remove from my library

**Screenshots**

**Platform**
Windows 10
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
[Uploading _Log202411_001.zip…]()
[_Log202408.zip](https://github.com/user-attachments/files/17882718/_Log202408.zip)
[Uploading _Log202411.zip…]()
[_Log202408.zip](https://github.com/user-attachments/files/
[Uploading _Log202406.zip…]()
17882721/_Log202408.zip)

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
