### ISSUE TITLE
Could not deserialize json: 

### ISSUE THREAD

**Issue by KJP15896** [rmcrackan/Libation#1059]
at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Form1.refreshImportMenu(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

[_Log202411_003.zip](https://github.com/user-attachments/files/17894812/_Log202411_003.zip)

[_Log202411_003.zip](https://github.com/user-attachments/files/17894813/_Log202411_003.zip)

**Comment by rmcrackan** [comment]
I am out of town and do not have access to my computer right now. It sounds like you have a corrupted accounts settings file. In the same folder where your log files are is an account settings file. Delete that, restart Libation, and re-add your account/s under settings > accounts. You’ll need to login again but no data, books, or files will have been lost.

**Comment by MacearOG** [comment]
Just submitted another bug report for this same issue.  Deleting account settings file fixed the issue.
