### ISSUE TITLE
Error importing Audible Library

### ISSUE THREAD

**Issue by RhapsodicPiffle** [rmcrackan/Libation#1064]
**Describe the bug**
Recently rebooted my computer since it had been a while, and there must have been some changes that I don't know about, because now Calibre throws an error when trying to scan my Audible library. Any help in correcting my user error is appreciated.

End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 25
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 238
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201

**To Reproduce**

1. Go to 'Import'
2. Click on 'Scan Library'
3. See error

**Expected behavior**
I expect Calibre to read from my Audible Library to download the new books I have purchased. 

**Screenshots**
![image](https://github.com/user-attachments/assets/7e69d891-008d-4cb7-bf39-0af25406cb21)

**Platform**

Windows 10 Pro 22H2

**Log Files**
[_Log202412.zip](https://github.com/user-attachments/files/18012115/_Log202412.zip)

**Comment by rmcrackan** [comment]
Thank you for the log file. If you delete you log files and restart Libation, does this still happen?

**Comment by RhapsodicPiffle** [comment]
I just deleted the log files and I'm still getting the error

**Comment by rmcrackan** [comment]
Does it create a new log? The really weird thing is that it appears to be an error writing to logs -- which is written to the log

**Comment by RhapsodicPiffle** [comment]
[_Log202412.zip](https://github.com/user-attachments/files/18015415/_Log202412.zip)

**Comment by RhapsodicPiffle** [comment]
Later today I'm going to try to uninstall and reinstall to see if that fixes the issue

**Comment by RhapsodicPiffle** [comment]
By deleting my user folder and having Libation recreate it, I am able to start importing again. Not sure what happened, but that was the fix.

**Comment by rmcrackan** [comment]
How very strange. Thanks for following up with me.
