### ISSUE TITLE
Another bug report

### ISSUE THREAD

**Issue by Merren0015** [rmcrackan/Libation#1081]
**Describe the bug**
Cannot open activate program:  Error posted

Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.RecreateHandleCore()
   at System.Windows.Forms.Control.SetParentHandle(IntPtr value)
   at System.Windows.Forms.Control.ControlCollection.Remove(Control value)
   at LibationWinForms.Form1.SetQueueCollapseState(Boolean collapsed) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ProcessQueue.cs:line 97
   at LibationWinForms.Form1.ToggleQueueHideBtn_Click(Object sender, EventArgs e) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ProcessQueue.cs:line 113
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
Try the suggestion in the other ticket. If this bug still happens after that, please reply here with the latest log file. Thanks
