### ISSUE TITLE
License denied

### ISSUE THREAD

**Issue by phonon112358** [rmcrackan/Libation#1084]
**Describe the bug**
I have 737 audiobooks from audible. I want to liberate all of them. I use the .exe program of Libation 11.1. 

The first approximately 200 went well without any issues. 
Then, I was getting the error message "Content license denied". I couldn't download/decrypt any further audiobook. However, on audible, I can listen to them, they are in my library. 
Hence, I removed Libation completely (backuped the 200 audiobooks to another drive and then removed the Libation folder). Afterwards, I import my account once again. Then, I liberate the audiobooks once again. This time, 150 got downloaded before the error message occurred. The 150 were not entirely included in the set of 200 that I liberated the first time. 
Now, I cannot download/liberate anything further.

Is there any limit (from audible or Libation) of audiobooks that can be downloaded? 
Does anyone have any idea how to proceed?

**To Reproduce**

1. Import an account with many books
2. Liberate 
3. Wait
4. See error after approximately 100-300 books

**Expected behavior**
All books should be downloaded 

**Screenshots**
![2024-12-19 at 00-19-32](https://github.com/user-attachments/assets/ed6474de-299c-4770-857b-206e06e9c136)
![2024-12-19 at 00-18-58](https://github.com/user-attachments/assets/f2472d44-c8d2-4667-9f35-33acdc4090a6)

**Platform**
Windows 11
Libation 11.1 Windows version 

**Log Files**
[_Log202412.zip](https://github.com/user-attachments/files/18190157/_Log202412.zip)
[_Log202412.zip](https://github.com/user-attachments/files/18190161/_Log202412.zip)
Unfortunately, I don't have the log file from my first trial anymore.

**Comment by rmcrackan** [comment]
Thank you for the log files. If a large number of these initial failures were "Plus" titles, this will fix itself within a day or 2. (I don't have a Germany account so I can't check whether of these books are Plus titles.)

**Comment by phonon112358** [comment]
today, I tried again. It worked for 150 further books.

Now, I get the following error message:

   Request could not be authenticated

   at AudibleApi.RestMessageValidator.ThrowStrongExceptionsIfInvalid(String message, Uri requestUri) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/RestMessageValidator.cs:line 49
   at AudibleApi.ApiMessageHandler.ProcessResponse(HttpResponseMessage response, CancellationToken cancellationToken) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiMessageHandler.cs:line 69
   at System.Net.Http.MessageProcessingHandler.<>c.<SendAsync>b__5_0(Task`1 task, Object state)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 59
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 57
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 287
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 439
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 402
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 169
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 169
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 317
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 266
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 266
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 179
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

[_Log202412.zip](https://github.com/user-attachments/files/18223331/_Log202412.zip)

**Comment by rmcrackan** [comment]
These new ~150 titles: are these books you own? or Plus titles? If plus, I recommend following the same advice as before.

**Comment by phonon112358** [comment]
ok, yes they are plus titles , so I will wait a few days

**Comment by phonon112358** [comment]
You were right. I can liberate 150-200 audiobooks every 2-3 days.
Thanks
