### ISSUE TITLE
Scan Failure

### ISSUE THREAD

**Issue by chicleeblair** [rmcrackan/Libation#1093]
**Describe the bug**

**To Reproduce**
1. Go to Scan Library

**Expected behavior**
Book list to update
**Screenshots**

Mac OS 15 
Macbook Air M3 

**Log Files**
Attach your Libation log file h
[_Log202409.zip](https://github.com/user-attachments/files/18224568/_Log202409.zip)
ere.

**Comment by rmcrackan** [comment]
Thanks for the log file. I don't see any errors in it. Can you describe the problem?

**Comment by chicleeblair** [comment]
This is the error it gives me:
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions
client, HttpRequestMessage request) in
/home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated
[partial].cs:line 59
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri,
HttpMethod method, IHttpClientActions client, HttpBody requestBody) in
/home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 57
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in
/home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 287
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in
/home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 439
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions
libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim
semaphore)+MoveNext() in
/home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 402
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions
libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim
semaphore)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions
libraryOptions, Boolean importEpisodes) in
/Users/runner/work/Libation/Libation/Source/AudibleUtilities/ApiExtended.cs:line
169
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions
libraryOptions, Boolean importEpisodes) in
/Users/runner/work/Libation/Libation/Source/AudibleUtilities/ApiExtended.cs:line
169
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3
action, Context context, CancellationToken cancellationToken,
ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1
shouldRetryResultPredicates, Func`5 onRetryAsync, Int32
permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4
sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context
context, CancellationToken cancellationToken, Boolean
continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended
apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver
archiver) in
/Users/runner/work/Libation/Libation/Source/ApplicationServices/LibraryCommands.cs:line
281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2
apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in
/Users/runner/work/Libation/Libation/Source/ApplicationServices/LibraryCommands.cs:line
263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2
apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in
/Users/runner/work/Libation/Libation/Source/ApplicationServices/LibraryCommands.cs:line
265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2
apiExtendedfunc, Account[] accounts) in
/Users/runner/work/Libation/Libation/Source/ApplicationServices/LibraryCommands.cs:line
132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[]
accounts) in
/Users/runner/work/Libation/Libation/Source/LibationAvalonia/ViewModels/MainVM.Import.cs:line
201

**Comment by rmcrackan** [comment]
So weird that this isn't in the log. Is there a more recent log? I'd like to dig further into this for you.

**Comment by chicleeblair** [comment]
Not that I can find. The app’s crashing after, too. I was thinking of
uninstalling and redownloading.

**Comment by rmcrackan** [comment]
Yeah, let's try that. If Libation starts and later crashes, it should get far enough to create a log file -- unless the drive is too full to write to, or some similar odd situation.

**Comment by chicleeblair** [comment]
I did a full reinstall, logged in successfully via the browser, and got
the same error. It did give me a log this time.

**Comment by rmcrackan** [comment]
Sounds like progress at least. Please attach the latest log.

**Comment by Mai65** [comment]
Similar problem here: 
```
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 53
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77
```


[_Log202412.zip](https://github.com/user-attachments/files/18266949/_Log202412.zip)

**Comment by rmcrackan** [comment]
@Mai65 : your errors say they are timeouts. Try again tomorrow. If that doesn't work, try again on a different network (friend's wifi, coffee shop, etc). If it's an issue with your network, try upgrading to the latest pre-release. I fixed a networking bug in there that I haven't put into a full release yet -- https://github.com/rmcrackan/Libation/releases/tag/v11.6.3

**Comment by Mai65** [comment]
> @Mai65 : your errors say they are timeouts. Try again tomorrow. If that doesn't work, try again on a different network (friend's wifi, coffee shop, etc). If it's an issue with your network, try upgrading to the latest pre-release. I fixed a networking bug in there that I haven't put into a full release yet -- https://github.com/rmcrackan/Libation/releases/tag/v11.6.3

Thanks for the hint. I did not work today with 11.1 but 11.6.3 worked just fine. Thank you very much for your great work.

**Comment by rmcrackan** [comment]
You're welcome. Happy new year!

**Comment by chicleeblair** [comment]
This is still happening for me. (The Time-outs) Any advice?

**Comment by rmcrackan** [comment]
Can you attach your most recent log? I'd like to see if there are any new details there.
