### ISSUE TITLE
Wont log in

### ISSUE THREAD

**Issue by kellydra** [rmcrackan/Libation#11]
It will not log me in, I tried on the old version before coming here and seeing if it was a known error. I saw there was an update so I tried that one too and the same thing happened. It boots me out saying if it keeps happening to contact you. It just resets back to the login info pop-up. 

2020-08-24 16:50:10.967 -07:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"3.1.10.4","AudibleLocale":"us","LibationFiles":"G:\\LibationFiles_v3.1.10\\publish\\LibationFiles","BooksDirectory":"C:\\Users\\Mike\\Desktop\\New folder","DownloadsInProgressEnum":"LibationFiles","DownloadsInProgressDir":"G:\\LibationFiles_v3.1.10\\publish\\LibationFiles\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"G:\\LibationFiles_v3.1.10\\publish\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\Mike\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-08-24 16:50:20.408 -07:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-08-24 16:50:20.431 -07:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-08-24 16:52:00.576 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportLibraryAsync>d__0.MoveNext()) Error importing library
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Query()
   at AudibleApi.Authentication.ResultFactory.LoginCompleteFactory.getAccessToken(HttpResponseMessage response)
   at AudibleApi.Authentication.ResultFactory.LoginCompleteFactory.IsMatchAsync(HttpResponseMessage response)
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(IHttpClient client, HttpMethod method, Uri uri, HttpContent content)
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(IHttpClient client, HttpMethod method, Uri uri, HttpContent content)
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(IHttpClient client, ISystemDateTime systemDateTime, Dictionary`2 inputs)
   at AudibleApi.Authentication.CaptchaPage.SubmitAsync(String guess)
   at AudibleApi.EzApiCreator.loginAsync(ILoginCallback responder)
   at AudibleApi.EzApiCreator.GetApiAsync(String identityFilePath, ILoginCallback loginCallback, String localeCountryCode)
   at InternalUtilities.AudibleApiActions.getItemsAsync(ILoginCallback callback)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at InternalUtilities.AudibleApiActions.GetAllLibraryItemsAsync(ILoginCallback callback)
   at ApplicationServices.LibraryCommands.ImportLibraryAsync(ILoginCallback callback)

**Comment by rmcrackan** [comment]
Sorry for the delay in getting back with you. I haven't forgotten you. I just released version 4 which focuses on some changes in login. Please try it. If it still doesn't work, let's take a look at the new log.

**Comment by kellydra** [comment]
Thanks for getting back to me and thanks for the new release. Unfortunately it still wont let me get past the capcha. 

2020-08-31 21:04:53.641 -07:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.0.0.5","LibationFiles":"C:\\Users\\Mike\\Downloads\\LibationFiles_v4.0.0\\publish\\LibationFiles","BooksDirectory":"C:\\Users\\Mike\\Downloads\\LibationFiles_v4.0.0\\publish\\LibationFiles","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\Mike\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":1,"DownloadsFinal":"C:\\Users\\Mike\\Downloads\\LibationFiles_v4.0.0\\publish\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\Mike\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-08-31 21:04:54.987 -07:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-08-31 21:04:55.010 -07:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-08-31 21:06:10.054 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__1.MoveNext()) Redirecting to https://www.amazon.com/ap/challenge?ie=UTF8&arb=a7f19312-38a1-4550-bf14-1ac7543e837c
2020-08-31 21:06:10.655 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Query()
   at AudibleApi.Authentication.ResultFactory.LoginCompleteFactory.getAccessToken(HttpResponseMessage response)
   at AudibleApi.Authentication.ResultFactory.LoginCompleteFactory.IsMatchAsync(HttpResponseMessage response)
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(IHttpClient client, Locale locale, HttpMethod method, Uri uri, HttpContent content)
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(IHttpClient client, Locale locale, HttpMethod method, Uri uri, HttpContent content)
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(IHttpClient client, ISystemDateTime systemDateTime, Locale locale, Dictionary`2 inputs)
   at AudibleApi.Authentication.CaptchaPage.SubmitAsync(String guess)
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder)
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback)
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
2020-08-31 21:06:10.695 -07:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Query()
   at AudibleApi.Authentication.ResultFactory.LoginCompleteFactory.getAccessToken(HttpResponseMessage response)
   at AudibleApi.Authentication.ResultFactory.LoginCompleteFactory.IsMatchAsync(HttpResponseMessage response)
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(IHttpClient client, Locale locale, HttpMethod method, Uri uri, HttpContent content)
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(IHttpClient client, Locale locale, HttpMethod method, Uri uri, HttpContent content)
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(IHttpClient client, ISystemDateTime systemDateTime, Locale locale, Dictionary`2 inputs)
   at AudibleApi.Authentication.CaptchaPage.SubmitAsync(String guess)
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder)
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback)
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e)

**Comment by rmcrackan** [comment]
Thanks for the logs. I can't tell what's going wrong but I can spot where it's happening. I made my best guess at a fix and also added some better logs in that area just in case. These are available in v4.0.1. See if this latest release resolves the issue.

https://github.com/rmcrackan/Libation/releases/latest

If it's still giving you trouble, let's take a look at the new logs. Hopefully either the new code or the better logging will be illuminating.

Let me know how it goes

**Comment by kellydra** [comment]
So I discovered that if you have your 2 step verification off it resets you to the captcha every time you try to sign in. I didn't know mine was turned off so when when I went to sign in (this version only) I got an odd notification sent to my phone. After I turned my 2 step back on it seemed to log me in but it did not grab by library. 


2020-09-01 12:51:56.815 -07:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.0.1.2","LibationFiles":"C:\\Users\\Mike\\Downloads\\LibationFiles_v4.0.1\\publish\\LibationFiles","BooksDirectory":"C:\\Users\\Mike\\Downloads\\LibationFiles_v4.0.1\\publish\\LibationFiles","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\Mike\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":1,"DownloadsFinal":"C:\\Users\\Mike\\Downloads\\LibationFiles_v4.0.1\\publish\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\Mike\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-09-01 12:51:58.203 -07:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-09-01 12:51:58.224 -07:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-09-01 12:54:05.669 -07:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"AccountId":"stormy_day_crafts@yahoo.com","LocaleName":"us"}
2020-09-01 12:54:05.740 -07:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__2.MoveNext()) ImportLibraryAsync. {"AccountName":"stormy_day_crafts@yahoo.com - us","AccountId":"stormy_day_crafts@yahoo.com","LocaleName":"us"}
2020-09-01 12:54:24.534 -07:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__37.MoveNext()) Page 1: 1000 results
2020-09-01 12:54:49.503 -07:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__37.MoveNext()) Page 2: 1000 results
2020-09-01 12:55:35.250 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, ISealedHttpClient client)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, ISealedHttpClient client)
   at AudibleApi.Api.getLibraryAsync(String parameters)
   at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions)
   at AudibleApi.Api.GetAllLibraryItemsAsync()
   at InternalUtilities.AudibleApiActions.getItemsAsync(Api api)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(Api api, Account account)
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
2020-09-01 12:55:35.333 -07:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, ISealedHttpClient client)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, ISealedHttpClient client)
   at AudibleApi.Api.getLibraryAsync(String parameters)
   at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions)
   at AudibleApi.Api.GetAllLibraryItemsAsync()
   at InternalUtilities.AudibleApiActions.getItemsAsync(Api api)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(Api api, Account account)
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e)

**Comment by rmcrackan** [comment]
This is a wacky one. It's like your computer can't find the website
sometimes. Are you connecting to the internet through some less traditional
method? Running it on a VM? Proxy? Maybe bad internet connection with
exceptionally high latency?
