### ISSUE TITLE
Error importing audible library

### ISSUE THREAD

**Issue by myopica** [rmcrackan/Libation#119]
Error log :

2021-09-20 22:09:38.874 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(FileManager.Configuration)) 

2021-09-20 22:09:38.937 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(FileManager.Configuration)) Begin. {"AppName":"Libation","Version":"6.0.1.2","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"LibationFiles":"C:\\Users\\Mum\\Libation","BooksDirectory":"M:\\Books","InProgress":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDir":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDir":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2021-09-20 22:09:40.366 +01:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) Book counts. {"total":0,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0}
2021-09-20 22:09:40.379 +01:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0}
2021-09-20 22:09:43.126 +01:00 [INF] (at FileManager.PersistentDictionary.writeFile(System.String, Newtonsoft.Json.Linq.JToken)) Config changed. {"propertyName":"Form1","newValue":"{\r\n  \"X\": 160,\r\n  \"Y\": 160,\r\n  \"Height\": 766,\r\n  \"Width\": 1169,\r\n  \"IsMaximized\": false\r\n}"}
2021-09-21 18:56:28.571 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(FileManager.Configuration)) 

2021-09-21 18:56:28.656 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(FileManager.Configuration)) Begin. {"AppName":"LibationCli","Version":"6.0.1.2","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"LibationFiles":"C:\\Users\\Mum\\Libation","BooksDirectory":"M:\\Books","InProgress":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDir":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDir":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2021-09-21 18:56:30.665 +01:00 [INF] (at Dinah.Core.IO.SerilogTextWriter.WriteLine(System.String)) No verb selected
2021-09-21 18:56:51.076 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(FileManager.Configuration)) 

2021-09-21 18:56:51.127 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(FileManager.Configuration)) Begin. {"AppName":"Libation","Version":"6.0.1.2","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"LibationFiles":"C:\\Users\\Mum\\Libation","BooksDirectory":"M:\\Books","InProgress":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDir":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDir":"C:\\Users\\Mum\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2021-09-21 18:56:52.524 +01:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) Book counts. {"total":0,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0}
2021-09-21 18:56:52.535 +01:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0}
2021-09-21 18:57:05.474 +01:00 [INF] (at InternalUtilities.ApiExtended+<CreateAsync>d__5.MoveNext()) {"LoginType":"ILoginChoiceEager","Account":"AccountId=s[...]1@g[...]l.c[...]m|AccountName=s[...]1@g[...]l.c[...]k|Locale=uk","LocaleName":"uk"}
2021-09-21 18:57:05.844 +01:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__4.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=s[...]1@g[...]l.c[...]m|AccountName=s[...]1@g[...]l.c[...]k|Locale=uk"}
2021-09-21 18:57:12.053 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 1: 250 results
2021-09-21 18:57:18.263 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 2: 250 results
2021-09-21 18:57:24.694 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 3: 250 results
2021-09-21 18:57:31.493 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 4: 250 results
2021-09-21 18:57:37.585 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 5: 250 results
2021-09-21 18:57:43.946 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 6: 250 results
2021-09-21 18:57:50.145 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 7: 250 results
2021-09-21 18:57:51.217 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 8: 41 results
2021-09-21 18:57:51.312 +01:00 [INF] (at InternalUtilities.ApiExtended+<manageEpisodesAsync>d__15.MoveNext()) 13 series of shows/podcasts found
2021-09-21 18:57:53.410 +01:00 [INF] (at InternalUtilities.ApiExtended+<manageEpisodesAsync>d__15.MoveNext()) 114 episodes of shows/podcasts found
2021-09-21 18:57:59.004 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 1: 250 results
2021-09-21 18:58:04.534 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 2: 250 results
2021-09-21 18:58:10.461 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 3: 250 results
2021-09-21 18:58:15.990 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 4: 250 results
2021-09-21 18:58:21.524 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 5: 250 results
2021-09-21 18:58:27.618 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 6: 250 results
2021-09-21 18:58:33.888 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 7: 250 results
2021-09-21 18:58:35.020 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 8: 41 results
2021-09-21 18:58:35.113 +01:00 [INF] (at InternalUtilities.ApiExtended+<manageEpisodesAsync>d__15.MoveNext()) 13 series of shows/podcasts found
2021-09-21 18:58:36.662 +01:00 [INF] (at InternalUtilities.ApiExtended+<manageEpisodesAsync>d__15.MoveNext()) 114 episodes of shows/podcasts found
2021-09-21 18:58:42.500 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 1: 250 results
2021-09-21 18:58:48.088 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 2: 250 results
2021-09-21 18:58:53.480 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 3: 250 results
2021-09-21 18:58:59.901 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 4: 250 results
2021-09-21 18:59:05.889 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 5: 250 results
2021-09-21 18:59:11.947 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 6: 250 results
2021-09-21 18:59:17.472 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 7: 250 results
2021-09-21 18:59:18.510 +01:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__42.MoveNext()) Page 8: 41 results
2021-09-21 18:59:18.603 +01:00 [INF] (at InternalUtilities.ApiExtended+<manageEpisodesAsync>d__15.MoveNext()) 13 series of shows/podcasts found
2021-09-21 18:59:20.000 +01:00 [INF] (at InternalUtilities.ApiExtended+<manageEpisodesAsync>d__15.MoveNext()) 114 episodes of shows/podcasts found
2021-09-21 18:59:20.017 +01:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__2.MoveNext()) Error importing library
System.AggregateException: One or more errors occurred. (Collection contains item(s) with blank Title (Parameter 'items'))
 ---> System.ArgumentException: Collection contains item(s) with blank Title (Parameter 'items')
   --- End of inner exception stack trace ---
   at InternalUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\InternalUtilities\ApiExtended.cs:line 143
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 161
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 145
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 88
2021-09-21 18:59:20.029 +01:00 [ERR] (at LibationWinForms.MessageBoxAlertAdmin.Show(System.String, System.String, System.Exception)) Alert admin error: {"text":"Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator","caption":"Error importing library"}
System.AggregateException: One or more errors occurred. (Collection contains item(s) with blank Title (Parameter 'items'))
 ---> System.ArgumentException: Collection contains item(s) with blank Title (Parameter 'items')
   --- End of inner exception stack trace ---
   at InternalUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\InternalUtilities\ApiExtended.cs:line 143
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 161
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 145
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 88
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 35

**Comment by rmcrackan** [comment]
Wow, I've never actually seen that happen. It looks like there's a podcast episode with no title. Thanks for this log. I'll get a bug fix out shortly.

**Comment by rmcrackan** [comment]
Fixed in [v6.2.0](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by myopica** [comment]
Thank you very much, downloading it now.
