### ISSUE TITLE
Another podcast issue

### ISSUE THREAD

**Issue by tharubberchicken** [rmcrackan/Libation#120]
Firstly, superb app. And congrats on being the first to decrypt AAXC!

So, I still receive a crash when importing my library. By process of elimination I've narrowed it down to the DragonLance Saga podcast. I've done this by unfollowing it, testing Libation, re-following it, testing Libation again. It crashes only when the podcast _is in_ my library.

Scanning the 109 episodes it seems they all have titles, however one doesn't seem to have a cover (Dragons of Summer Flame Review) so maybe this is the cause.

Here is the podcast link, via Amazon Australia:

[DragonLance Saga](https://www.audible.com.au/pd/Podcast/B08K6P5G9N)

And here is the error message I received, along with the log as an attachment.

Value cannot be null. (Parameter 'html')

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Dinah.Core.Threading.ISynchronizeInvokeExt.UIThreadSync(ISynchronizeInvoke synchronizeInvoke, Action code)
   at LibationWinForms.Form1.reloadGridAndUpdateBottomNumbers(Object _, Object __) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Form1.cs:line 62
   at ApplicationServices.LibraryCommands.finalizeLibrarySizeChange() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 209
   at ApplicationServices.LibraryCommands.<>c.<importIntoDbAsync>b__5_0() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 179
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 179
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 96
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 35

[_Log202109.log](https://github.com/rmcrackan/Libation/files/7210226/_Log202109.log)

**Comment by rmcrackan** [comment]
I need more bug reports like this. You narrowed it down to something reproducible and included error logs. Good on ya! I'll take a look at this soon.

Thank you again!

**Comment by rmcrackan** [comment]
Is it any better in [v6.0.5](https://github.com/rmcrackan/Libation/releases/latest) ?

**Comment by tharubberchicken** [comment]
Sorry, it still did not work. Again, I'll attach the error message, the log, and also the JIT error message that comes up when I restart Libation. I hadn't sent this previously, so hopefully this will give you some insight.

I did try importing my library once more before _resetting_ Libation, and it _did_ seem to scan and picked up 700 or so titles (many are podcasts, I don't have that many books!) but it did not display anything in the library. It seems my original issue breaks Libation until I reset the program.

[error_message.txt](https://github.com/rmcrackan/Libation/files/7221096/error_message.txt)
[jit_message.txt](https://github.com/rmcrackan/Libation/files/7221097/jit_message.txt)
[_Log202109.log](https://github.com/rmcrackan/Libation/files/7221098/_Log202109.log)

**Comment by rmcrackan** [comment]
Thanks! those were perfect. Fixed in [v6.1.1](https://github.com/rmcrackan/Libation/releases/latest)

Thank you again for your help and patience
