### ISSUE TITLE
Cannot import library: Dependency problem?

### ISSUE THREAD

**Issue by twlee79** [rmcrackan/Libation#13]
I'm unable to import my Audible library using Libation 4.00 or 4.01, getting the "Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator" error. Examining the log file, this appears to be a dependency error:

```
2020-09-07 08:48:32.556 +12:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at InternalUtilities.AudibleApiActions.<>c.<getValidators>b__7_0(Assembly s)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at InternalUtilities.AudibleApiActions.getValidators()
   at InternalUtilities.AudibleApiActions.getItemsAsync(Api api)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(Api api, Account account)
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts)
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
(log slightly truncated the "Could not load file or assembly" line repeats maybe 20 times)

I have .NET framework 4.8 installed.

**Comment by rmcrackan** [comment]
Thank you for bringing this to my attention. I found a definite problem with the software I was using to publish Libation for use by others. Should be fixed in Libation v4.0.2. Please let me know if you're still seeing this error in v4.0.2
