### ISSUE TITLE
Unable to Execute Libation 

### ISSUE THREAD

**Issue by pakiyabhai** [rmcrackan/Libation#149]
Hi,
I've DOT net 4.8 and 5 installed. I use Windows 10. I'm unable o figure how to get this running. C:\Dropbox\DinahsFolder is something not on my hard drive

`Object reference not set to an instance of an object.

   at FileManager.PersistentDictionary.GetString(String propertyName) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileManager\PersistentDictionary.cs:line 42
   at LibationFileManager.Configuration.SettingsFileIsValid(String settingsFile) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationFileManager\Configuration.cs:line 30
   at LibationFileManager.Configuration.get_LibationSettingsAreValid() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationFileManager\Configuration.cs:line 20
   at LibationWinForms.Program.RunInstaller(Configuration config) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Program.cs:line 86
   at LibationWinForms.Program.Main() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Program.cs:line 43`

**Comment by rmcrackan** [comment]
Those are just the file paths of where the code lives on my computer. It helps when debugging stuff like this.

Do you have the following file? If so, is there anything inside? C:\Users\[username]\Libation\Settings.json

That's a strange error. I added some better debugging to that area. Please try again with [v6.4.2](https://github.com/rmcrackan/Libation/releases/latest) and let me know what kind of error you see

**Comment by pakiyabhai** [comment]
Deleting the settings.json has fixed this error . It was completely blank. 

Before that I still got the error below

`Unrecoverable error. Unable to read settings from Settings file

   at FileManager.PersistentDictionary.readFile() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileManager\PersistentDictionary.cs:line 224
   at FileManager.PersistentDictionary.GetString(String propertyName) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileManager\PersistentDictionary.cs:line 41
   at LibationFileManager.Configuration.SettingsFileIsValid(String settingsFile) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationFileManager\Configuration.cs:line 30
   at LibationFileManager.Configuration.get_LibationSettingsAreValid() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationFileManager\Configuration.cs:line 20
   at LibationWinForms.Program.RunInstaller(Configuration config) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Program.cs:line 86
   at LibationWinForms.Program.Main() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Program.cs:line 43`

**Comment by rmcrackan** [comment]
Thanks for following up. I'll put some extra code around that area to hopefully prevent this in the future.
