### ISSUE TITLE
Cannot login to German audible

### ISSUE THREAD

**Issue by jakob42** [rmcrackan/Libation#15]
Hi,

I have a problem logging into my account. Its in Germany, not sure if there is some URL missing? `System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')` Here is my log, replaced my usernames with dummies.

Thanks in advance!

```
2020-10-01 16:41:54.869 +02:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.0.8.2","LibationFiles":"C:\\Users\\User\\Downloads\\Libation_v4.0.8\\LibationFiles","BooksDirectory":"C:\\Users\\User\\Downloads\\Libation_v4.0.8\\LibationFiles","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\User\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"C:\\Users\\User\\Downloads\\Libation_v4.0.8\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\User\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-10-01 16:41:56.142 +02:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-10-01 16:41:56.152 +02:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-10-01 16:42:01.147 +02:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"AccountId":"myaudible@email.example","LocaleName":"germany"}
2020-10-01 16:42:05.167 +02:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at AudibleApi.Authentication.ResultFactory.CaptchaPageFactory.getCaptchaUri(String body) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\ResultFactory.CaptchaPageFactory.cs:line 59
   at AudibleApi.Authentication.ResultFactory.CaptchaPageFactory.CreateResultAsync(IHttpClient client, ISystemDateTime systemDateTime, Locale locale, HttpResponseMessage response, Dictionary`2 oldInputs) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\ResultFactory.CaptchaPageFactory.cs:line 42
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(IHttpClient client, ISystemDateTime systemDateTime, Locale locale, Dictionary`2 inputs) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 36
   at AudibleApi.Authentication.CredentialsPage.SubmitAsync(String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\CredentialsPage.cs:line 31
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 82
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 66
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 50
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 22
2020-10-01 16:42:05.186 +02:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at AudibleApi.Authentication.ResultFactory.CaptchaPageFactory.getCaptchaUri(String body) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\ResultFactory.CaptchaPageFactory.cs:line 59
   at AudibleApi.Authentication.ResultFactory.CaptchaPageFactory.CreateResultAsync(IHttpClient client, ISystemDateTime systemDateTime, Locale locale, HttpResponseMessage response, Dictionary`2 oldInputs) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\ResultFactory.CaptchaPageFactory.cs:line 42
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(IHttpClient client, ISystemDateTime systemDateTime, Locale locale, Dictionary`2 inputs) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 36
   at AudibleApi.Authentication.CredentialsPage.SubmitAsync(String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\CredentialsPage.cs:line 31
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 82
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 66
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 50
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 22
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\UNTESTED\Dialogs\IndexLibraryDialog.cs:line 34

```

**Comment by jakob42** [comment]
Thanks for the quick fix. It still doesn't work, but it might be an error on my side, I'll try tomorrow. ATM I don't even get a login window again... I'll post logs if I cannot get it to work on the weekend.

**Comment by jakob42** [comment]
Not sure if 4.0.10 fixed it or if waiting solved it, but it works again. Thanks!
