### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by docbha** [rmcrackan/Libation#177]
When try and open libation I get the following error:
Object reference not set to an instance of an object.

   at FileManager.PersistentDictionary.GetString(String propertyName) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileManager\PersistentDictionary.cs:line 42
   at FileManager.Configuration.SettingsFileIsValid(String settingsFile) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileManager\Configuration.cs:line 29
   at FileManager.Configuration.get_LibationSettingsAreValid() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileManager\Configuration.cs:line 19
   at LibationWinForms.Program.RunInstaller(Configuration config) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Program.cs:line 86
   at LibationWinForms.Program.Main() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Program.cs:line 43

**Comment by docbha** [comment]
I tried to download the latest version and registered as new user but i am unable to add any account by both options provided. Attached the error log.
[_Log202112.log](https://github.com/rmcrackan/Libation/files/7787576/_Log202112.log)

**Comment by rmcrackan** [comment]
There seem to be a lot of recent issues with not being able to log in/register. I suspect audible changed something on their end. I'm going to track these login/register bugs together in issue #175

**Comment by docbha** [comment]
Thanks so much.
