### ISSUE TITLE
Unable to sync library when selecting Locale as India but works for other Locales

### ISSUE THREAD

**Issue by battlingnebula** [rmcrackan/Libation#179]
[Log202112.log](https://github.com/rmcrackan/Libation/files/7793101/Log202112.log)

**I get this error:**

Could not register

   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies)
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync()
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime)
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(Identity inMemoryIdentity, String identityFilePath, String jsonPath)
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath)
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 30
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 136
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

**Comment by rmcrackan** [comment]
What happens if you try to alternate login method? The "or click here" link on Libation's password page

**Comment by battlingnebula** [comment]
> What happens if you try to alternate login method? The "or click here" link on Libation's password page

I get error too:

Could not register

   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies)
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync()
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime)
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(Identity inMemoryIdentity, String identityFilePath, String jsonPath)
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath)
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 30
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 136
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

**Comment by rmcrackan** [comment]
There seem to be a lot of recent issues with not being able to log in/register. I suspect audible changed something on their end. I'm going to track these login/register bugs together in issue #175
