### ISSUE TITLE
Books not being displayed in library area and book download progress not being kept track of

### ISSUE THREAD

**Issue by Zachman1** [rmcrackan/Libation#198]
No filters are being used but not a single book is shown in the library area. In addition, after this error popped up, Libation seemed to lose the ability to realize books were being downloaded. A book would download to it's folder but the "No progress" number would not change. If you press Liberate again, all of these books would redownload and copies of the download would be in each folder.

Attempted to reset progress by rescanning library but nothing changed. Then attempted to delete LibationContext.db and the folder SearchEngine but got following error:

Object reference not set to an instance of an object.

   at LibationFileManager.TagsPersistence.GetTags(String productId) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\TagsPersistence.cs:line 51
   at DataLayer.UserDefinedItem..ctor(Book book) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DataLayer\EfClasses\UserDefinedItem.cs:line 36
   at DataLayer.Book..ctor(AudibleProductId audibleProductId, String title, String description, Int32 lengthInMinutes, ContentType contentType, IEnumerable`1 authors, IEnumerable`1 narrators, Category category, String localeName) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DataLayer\EfClasses\Book.cs:line 94
   at DtoImporterService.BookImporter.createNewBook(ImportItem importItem) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\BookImporter.cs:line 129
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\BookImporter.cs:line 74
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\BookImporter.cs:line 30
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.ImporterBase`1.Import(T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\ImporterBase.cs:line 21
   at DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\LibraryBookImporter.cs:line 17
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.ImporterBase`1.Import(T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\DtoImporterService\ImporterBase.cs:line 21
   at ApplicationServices.LibraryCommands.<>c__DisplayClass4_0.<importIntoDbAsync>b__1() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 171
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 171
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 94
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

Log file is attached
[Log202202.log](https://github.com/rmcrackan/Libation/files/8104930/Log202202.log)
d

**Comment by rmcrackan** [comment]
Did you close Libation before deleting that file and folder?

**Comment by Zachman1** [comment]
I tried it a few times. First time I tried it it was with the app open. Then I tried closing it and deleting it again and got what looked like the same error.

**Comment by rmcrackan** [comment]
So weird. When I do this, it just opens up blank. Let's get methodical. Do the following. If at any time you get an error, close Libation and attach the new log file:

* close Libation
* move or delete these: log files, LibationContext.db, SearchEngine, BookTags.json (if you have any tags you want to save, move/rename this file instead of deleting it)
* open Libation
* scan library

**Comment by Zachman1** [comment]
Well good news. No errors and all books are showing up now. If I run into either error again though, I will let you know. 


Thank you for the help.

**Comment by rmcrackan** [comment]
Sorry about the weird hiccup. Better lucky than good. Glad it's working again.
