### ISSUE TITLE
unable to download library

### ISSUE THREAD

**Issue by draxal** [rmcrackan/Libation#2]
I saw mention of your solution on r/audible in a thread, and love the idea but I appear to be having an issue downloading the library.

When I try to import my library, it appears to login just fine and gets the book count and then starts failing. I believe this would be the relevant parts of the log file. Any ideas? 

------------------------------------------

2020-02-17 10:43:24.221 -07:00 [ERR] (at DtoImporterService.ImporterBase`1.Run(, )) Import error: post-validation importing
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at AudibleApiDTOs.Series.get_Index()
   at DtoImporterService.BookImporter.updateBook(Item item, Book book)
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 items)
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 items)
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param)
2020-02-17 10:43:24.223 -07:00 [ERR] (at DtoImporterService.ImporterBase`1.Run(, )) Import error: post-validation importing
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at AudibleApiDTOs.Series.get_Index()
   at DtoImporterService.BookImporter.updateBook(Item item, Book book)
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 items)
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 items)
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param)
   at DtoImporterService.ImporterBase`1.Import(T param)
   at DtoImporterService.LibraryImporter.DoImport(IEnumerable`1 items)
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param)
2020-02-17 10:43:24.225 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportLibraryAsync>d__0.MoveNext()) Error importing library
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at AudibleApiDTOs.Series.get_Index()
   at DtoImporterService.BookImporter.updateBook(Item item, Book book)
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 items)
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 items)
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param)
   at DtoImporterService.ImporterBase`1.Import(T param)
   at DtoImporterService.LibraryImporter.DoImport(IEnumerable`1 items)
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param)
   at DtoImporterService.ImporterBase`1.Import(T param)
   at ApplicationServices.LibraryCommands.<>c__DisplayClass0_0.<ImportLibraryAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at ApplicationServices.LibraryCommands.ImportLibraryAsync(ILoginCallback callback)

**Comment by rmcrackan** [comment]
I found where the problem is happening. I created an update to Libation which will hide the issue enough to continue. Please get the latest version, import your library, then open your log. Copy any lines like this and include them in this bug report:
Error parsing series index. Title: Whatever. ASIN: B123456789. Series index: more-stuff

**Comment by draxal** [comment]
Thanks for the quick reply and fix! Here are the 2 books that appear to be an issue:

----------------------------------------------------------------------------------------

2020-02-17 13:37:27.442 -07:00 [ERR] (at DtoImporterService.BookImporter.updateBook(AudibleApiDTOs.Item, DataLayer.Book)) Error parsing series index. Title: Besieged. ASIN: B06XNZJJH9. Series index: 0.3,4.7,8.6
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at AudibleApiDTOs.Series.get_Index()
   at DtoImporterService.BookImporter.updateBook(Item item, Book book)
2020-02-17 13:37:46.237 -07:00 [ERR] (at DtoImporterService.BookImporter.updateBook(AudibleApiDTOs.Item, DataLayer.Book)) Error parsing series index. Title: Two Tales of the Iron Druid Chronicles. ASIN: B00XUMA190. Series index: 0.6, 3.5
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at AudibleApiDTOs.Series.get_Index()
   at DtoImporterService.BookImporter.updateBook(Item item, Book book)

**Comment by rmcrackan** [comment]
Perfect. Fixed for real in latest update. Thanks for your help
