### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by rossdargan** [rmcrackan/Libation#201]
[Log202202.log](https://github.com/rmcrackan/Libation/files/8148703/Log202202.log)

I get this error while trying to do an import on my account:

Bad Data.

   at Internal.NativeCrypto.CapiHelper.ToKeyBlob(RSAParameters rsaParameters)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at AudibleApi.Cryptography.CreateRsaProviderFromPrivateKey(String privateKey)
   at AudibleApi.Cryptography.signSha256(String private_key, String dataString)
   at AudibleApi.Cryptography.CalculateSignature(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey)
   at AudibleApi.Cryptography.SignRequest(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey)
   at AudibleApi.Api.signRequestAsync(HttpRequestMessage request)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client)
   at AudibleApi.Api.getLibraryAsync(String parameters)
   at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions)
   at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups)
   at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 131
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

**Comment by rmcrackan** [comment]
Thank you for the log. Wow, I've never seen that part fail. If you close and re-open Libation does it happen again? If yes, what about if you remove your account, save, then re-add?

**Comment by rossdargan** [comment]
I had asked me to log back in, and provide my second factor but then I got that error. Closing an re-opening doesn't help. If I remove it and re add it will it cause all my downloaded books to be re-downloaded?

**Comment by rmcrackan** [comment]
Removing the account will not remove any books. I recommend removing account. Save. Re-add account. On the first scan it will ask you to log in again. If the log in doesn't work, try the "Or click here" method. That is: on the box that first asks for your password, there's a link that says "Or click here" and it walks you through another way of logging in.

Thank you for your patience. Sorry this has been such a hassle.

**Comment by rmcrackan** [comment]
@rossdargan  Any progress on this login issue?

**Comment by rmcrackan** [comment]
Since there's been no activity on this issue for a few weeks, I'm closing it for now. If you're still having this issue, reply and we I can re-open so we can continue the conversation.
