### ISSUE TITLE
Collection contains Categories with wrong number of categories

### ISSUE THREAD

**Issue by Deepwinter77** [rmcrackan/Libation#213]
Im getting the following Error message when i try to scan library
Error importing library. Please try again. If this happens after 2 or 3 tries, stop and contact administrator

Any ideas

[Log202203.log](https://github.com/rmcrackan/Libation/files/8307767/Log202203.log)

**Comment by rmcrackan** [comment]
Thanks for the log. Since this isn't the whole log I can't tell: what version are you using? The log file format looks like an older version. Does upgrading to the latest help?

**Comment by Deepwinter77** [comment]
Thanks for replying,
I tried installing the latest version I'm getting a different error message now.
I get a window popup Error importing library. Please try again. If this happens after 2 or 3 tries, stop and contact administrator

Followed by this,

Any ideas.

   at AudibleApi.RestMessageValidator.ThrowStrongExceptionsIfInvalid(String message, Uri requestUri)
   at AudibleApi.ApiMessageHandler.ProcessResponse(HttpResponseMessage response, CancellationToken cancellationToken)
   at System.Net.Http.MessageProcessingHandler.<>c.<SendAsync>b__5_0(Task`1 task, Object state)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client)
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client)
   at AudibleApi.Api.getLibraryAsync(String parameters)
   at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions)
   at AudibleApi.Api.getAllLibraryItemsAsync(LibraryOptions libraryOptions)
   at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups)
   at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 134
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34


[_Log202203.log](https://github.com/rmcrackan/Libation/files/8308990/_Log202203.log)
n

**Comment by Deepwinter77** [comment]
Ok so I went back  and tried to import the accounts one at a time and that worked without any error messages.

All sorted now :)

Thanks

**Comment by rmcrackan** [comment]
Great! I'm glad it worked out
