### ISSUE TITLE
Error downloading books with PDFs? 

### ISSUE THREAD

**Issue by PsychoData** [rmcrackan/Libation#216]
Hello, 

I am having trouble downloading some books. It seems like it might be Books with PDFs specifically having the issue. 

A few books worked fine, but others didn't. I tried adding some assorted "Free" books to see if I could replicate - and Pride & Prejudice worked fine, as well as Sense & Sensibility, but Moby Dick failed.
![image](https://user-images.githubusercontent.com/3719116/159205803-03f1d4a2-17d4-4ef9-831d-618fa18339f0.png)

When I try to download the individual book with the stoplight button, the program crashes and I get this prompt (full text attached)
![image](https://user-images.githubusercontent.com/3719116/159206116-07edd7c0-fee8-429c-beab-957b21f00334.png)

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudibleApi.Api.GetPdfDownloadLinkAsync(String asin)
   at FileLiberator.DownloadPdf.downloadPdfAsync(LibraryBook libraryBook, String proposedDownloadFilePath) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\DownloadPdf.cs:line 63
   at FileLiberator.DownloadPdf.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\DownloadPdf.cs:line 28
   at FileLiberator.Processable.TryProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\Processable.cs:line 54
   at LibationWinForms.BookLiberation.ProcessorAutomationController.<>c__DisplayClass4_0.<<CreateBackupBook>g__onDownloadDecryptBookCompleted|0>d.MoveNext() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\BookLiberation\ProcessorAutomationController.cs:line 106
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
......More in attached crash.txt
```

I also attached the logs in "info" mode and emailed them to your email in "verbose" mode

**Comment by PsychoData** [comment]
Logs
[Log202203.log](https://github.com/rmcrackan/Libation/files/8313169/Log202203.log)

**Comment by PsychoData** [comment]
Oh - I think it was Audible Plus membership being not-active

I didn't realize they were only in my library through "plus"

**Comment by rmcrackan** [comment]
Yeah, sounds like it's lingering "plus" things. I should probably handle this better.

The easiest way to get rid of them is Import > Remove Library Books. This will get your latest book list from audible and compare it to what Libation knows. Books that are no longer in your audible library will be at the top of the list and will be checked. You can click the button to remove clicked items.
