### ISSUE TITLE
Can't download books and error pop-up loop

### ISSUE THREAD

**Issue by Ulyzzeus** [rmcrackan/Libation#225]
It seems like downloads fail because Libation tries to access E:\config.msi, but there is no such file. 
```
 {}2022-04-08 12:38:33.966 +02:00 [INF] (at LibationWinForms.BookLiberation.ProcessorAutomationController+<BackupAllBooksAsync>d__1.MoveNext()) Begin BackupAllBooksAsync
 {}2022-04-08 12:38:33.996 +02:00 [INF] (at FileLiberator.Processable+<ProcessSingleAsync>d__12.MoveNext()) Begin ProcessSingleAsync {"Title":"Amongst Our Weapons: The Brand New Rivers of London Novel","AudibleProductId":"B09LMRCZ29","Locale":"uk","Account":"m[...]l.a[...]t@m[...]x.o[...]g"}
 {}2022-04-08 12:38:34.004 +02:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Download & Decrypt Step, Begin: [B09LMRCZ29] Amongst Our Weapons: The Brand New Rivers of London Novel
 {}2022-04-08 12:38:34.024 +02:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__9.MoveNext()) {"Username":"m[...]l.a[...]t@m[...]x.o[...]g","LocaleName":"uk"}
 {}2022-04-08 12:38:34.482 +02:00 [INF] (at FileManager.PersistentDictionary.writeFile(System.String, Newtonsoft.Json.Linq.JToken)) Config changed. {"propertyName":"DecryptForm","newValue":"{\r\n  \"X\": 156,\r\n  \"Y\": 156,\r\n  \"Height\": 222,\r\n  \"Width\": 723,\r\n  \"IsMaximized\": false\r\n}"}
 {}2022-04-08 12:38:34.491 +02:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Download & Decrypt Step, Completed: [B09LMRCZ29] Amongst Our Weapons: The Brand New Rivers of London Novel

 {}2022-04-08 12:38:34.495 +02:00 [ERR] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_2(System.Object, System.ValueTuple`2[[System.Exception, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]])) Automated backup: error
System.TypeInitializationException: The type initializer for 'LibationFileManager.AudibleFileStorage' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path 'E:\Config.Msi' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at FileManager.BackgroundFileSystem.Init() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileManager\BackgroundFileSystem.cs:line 55
   at FileManager.BackgroundFileSystem..ctor(String rootDirectory, String searchPattern, SearchOption searchOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileManager\BackgroundFileSystem.cs:line 32
   at LibationFileManager.AudioFileStorage..ctor() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\AudibleFileStorage.cs:line 87
   at LibationFileManager.AudibleFileStorage..cctor() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\AudibleFileStorage.cs:line 21
   --- End of inner exception stack trace ---
   at FileLiberator.DownloadDecryptBook.downloadAudiobookAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\DownloadDecryptBook.cs:line 114
   at FileLiberator.DownloadDecryptBook.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\DownloadDecryptBook.cs:line 54
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\Processable.cs:line 46
   at LibationWinForms.BookLiberation.BackupRunner.ProcessOneAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\BookLiberation\ProcessorAutomationController.cs:line 201
 {"ExceptionDetail":{"HResult":-2146233036,"Message":"The type initializer for 'LibationFileManager.AudibleFileStorage' threw an exception.","Source":"FileLiberator","TargetSite":"Void MoveNext()","InnerException":{"Type":"System.UnauthorizedAccessException","HResult":-2147024891,"Message":"Access to the path 'E:\\Config.Msi' is denied.","Source":"System.Private.CoreLib","TargetSite":"IntPtr CreateRelativeDirectoryHandle(System.ReadOnlySpan`1[System.Char], System.String)"},"TypeName":"LibationFileManager.AudibleFileStorage","Type":"System.TypeInitializationException"}}2022-04-08 12:38:34.509 +02:00 [ERR] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_1(System.Object, System.String)) ERROR. All books have not been processed. Most recent book: processing failed
 {}2022-04-08 12:39:00.479 +02:00 [INF] (at FileLiberator.Processable+<ProcessSingleAsync>d__12.MoveNext()) Begin ProcessSingleAsync {"Title":"Le Morte D'Arthur","AudibleProductId":"B01G7MFTFA","Locale":"uk","Account":"m[...]l.a[...]t@m[...]x.o[...]g"}
 {}2022-04-08 12:39:00.487 +02:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Download & Decrypt Step, Begin: [B01G7MFTFA] Le Morte D'Arthur
 {}2022-04-08 12:39:00.506 +02:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__9.MoveNext()) {"Username":"m[...]l.a[...]t@m[...]x.o[...]g","LocaleName":"uk"}
 {}2022-04-08 12:39:00.889 +02:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Download & Decrypt Step, Completed: [B01G7MFTFA] Le Morte D'Arthur

 {}2022-04-08 12:39:00.894 +02:00 [ERR] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_2(System.Object, System.ValueTuple`2[[System.Exception, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]])) Automated backup: error
System.TypeInitializationException: The type initializer for 'LibationFileManager.AudibleFileStorage' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path 'E:\Config.Msi' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at FileManager.BackgroundFileSystem.Init() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileManager\BackgroundFileSystem.cs:line 55
   at FileManager.BackgroundFileSystem..ctor(String rootDirectory, String searchPattern, SearchOption searchOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileManager\BackgroundFileSystem.cs:line 32
   at LibationFileManager.AudioFileStorage..ctor() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\AudibleFileStorage.cs:line 87
   at LibationFileManager.AudibleFileStorage..cctor() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\AudibleFileStorage.cs:line 21
   --- End of inner exception stack trace ---
   at FileLiberator.DownloadDecryptBook.downloadAudiobookAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\DownloadDecryptBook.cs:line 114
   at FileLiberator.DownloadDecryptBook.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\DownloadDecryptBook.cs:line 54
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\FileLiberator\Processable.cs:line 46
   at LibationWinForms.BookLiberation.BackupRunner.ProcessOneAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\BookLiberation\ProcessorAutomationController.cs:line 201
 {"ExceptionDetail":{"HResult":-2146233036,"Message":"The type initializer for 'LibationFileManager.AudibleFileStorage' threw an exception.","Source":"FileLiberator","TargetSite":"Void MoveNext()","InnerException":{"Type":"System.UnauthorizedAccessException","HResult":-2147024891,"Message":"Access to the path 'E:\\Config.Msi' is denied.","Source":"System.Private.CoreLib","TargetSite":"IntPtr CreateRelativeDirectoryHandle(System.ReadOnlySpan`1[System.Char], System.String)"},"TypeName":"LibationFileManager.AudibleFileStorage","Type":"System.TypeInitializationException"}}2022-04-08 12:39:00.906 +02:00 [ERR] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_1(System.Object, System.String)) ERROR. All books have not been processed. Most recent book: processing failed
 {}2022-04-08 12:39:02.215 +02:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Done. All books have been processed
 {}2022-04-08 12:39:02.225 +02:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: DONE
 {}

```

![Libation_error](https://user-images.githubusercontent.com/103255220/162424658-7c60cc6e-6211-4969-9b18-3a1c397afbb7.jpg)

I also get this pop-up when I click anywhere in the library, when I click "ok" it opens again and again

**Comment by rmcrackan** [comment]
Woah, that's a new one. Can you attach the full log file?

**Comment by Ulyzzeus** [comment]
sure
[Log202204.log](https://github.com/rmcrackan/Libation/files/8451360/Log202204.log)

**Comment by rmcrackan** [comment]
Perfect, thanks!

I see. It's trying to find old books in your BooksDirectory (E:) and since access is blocked for `E:\Config.Msi`, it's choking. I'll get a bug fix out today.

**Comment by rmcrackan** [comment]
The latest version [v6.7.5](https://github.com/rmcrackan/Libation/releases/latest) should fix this. If not, let me know and I'll re-open this issue. Thank you again for your help!
