### ISSUE TITLE
Unhandled SQLite error

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#250]
Version 7.6.0.2, freshly downloaded. On opening, I get an "unhandled exception" and an offer to quit or continue. Continue seems to be fine. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'duplicate column name: PictureLarge'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Dinah.EntityFrameworkCore.DesignTimeDbContextFactoryBase`1.Create(String connectionString)
   at DataLayer.LibationContext.Create(String connectionString) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DataLayer\LibationContext.cs:line 31
   at ApplicationServices.DbContexts.GetContext() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\DbContexts.cs:line 12
   at ApplicationServices.DbContexts.GetLibrary_Flat_NoTracking() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\DbContexts.cs:line 17
   at ApplicationServices.LibraryCommands.GetCounts() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 328
   at LibationWinForms.Form1.UpdateCountsBw_DoWork(Object sender, DoWorkEventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\Form1.BackupCounts.cs:line 43
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Private.CoreLib.dll
----------------------------------------
Libation
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Downloads/Libation.7.6.0/Libation.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Runtime.dll
----------------------------------------
AppScaffolding
    Assembly Version: 7.6.0.2
    Win32 Version: 7.6.0.2
    CodeBase: file:///D:/Downloads/Libation.7.6.0/AppScaffolding.dll
----------------------------------------
LibationFileManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Downloads/Libation.7.6.0/LibationFileManager.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Downloads/Libation.7.6.0/System.Collections.dll
----------------------------------------

**Comment by Mbucari** [comment]
Well shoot. Only 2 hours after the release. This doesn't bode well...

**Comment by Mbucari** [comment]
Well shoot. Only 2 hours after the release. This doesn't bode well...
@rmcrackan while debugging during the last week, I delete it all my libation settings a couple of times. When I did that, libation crashed on initial launch. Maybe that info helps.

**Comment by rmcrackan** [comment]
So sorry! Fixed in [v7.6.1](https://github.com/rmcrackan/Libation/releases/latest). Thanks for reporting this.
