### ISSUE TITLE
Libation no longer scans | Error when scanning

### ISSUE THREAD

**Issue by ilicity** [rmcrackan/Libation#289]
When attempting to scan manually, it scans for about the time it usually does to scan my library, but then it errors out and says this

One or more errors occurred. (A task was canceled.)

   at AudibleApi.Api.GetLibraryItemAsyncEnumerable(LibraryOptions libraryOptions, Int32 numItemsPerRequest, Int32 maxConcurrentRequests)+MoveNext()
   at AudibleApi.Api.GetLibraryItemAsyncEnumerable(LibraryOptions libraryOptions, Int32 numItemsPerRequest, Int32 maxConcurrentRequests)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 133
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 133
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 213
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 197
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 120
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77
   
  Attached is a logfile
  I have tried version 8.1.1 and 8.0.1
  both versions have worked for me in the past, but neither are working now.
 
[Log202206_010.log](https://github.com/rmcrackan/Libation/files/8954762/Log202206_010.log)

**Comment by Mbucari** [comment]
Geeze those logs are a mess!

It LOOKS like the SendAsync was cancelled because of timeout. The first finished downloadItemPage (which was for Page 3) finished at 01:29:04.590. The cancelled SendAsync (which was in the first batch or requests) errored at 01:30:11.429, over 1 minute later. If that's what this is, it's a network problem, not a Libation problem.

**Comment by rmcrackan** [comment]
@ilicity When you got this error, how did Libation tell you? ie: did it just fail without telling you? did you get an error pop-up? etc

@Mbucari 

> network problem, not a Libation problem

I'm surprised this hasn't come up before. Nothing we can do about network. We should fail more gracefully though. That log file is ... special. Our network calls all go through AudibleApi and within there all calls must route through the 'ad hoc authenticated' and 'ad hoc unauthenticated' methods. If I'm remembering all that correctly then this gives us a very tiny surface area to cover which is great. If nothing else, we can discover if it's a timeout exception (or if the aggregate exception/inner exception contains a timeout) and hide the rest of that abominable stack trace. Hopefully handling it better at the api will suffice and Libation will be more clear by virtue of that. If not we can add better specific handling to Libation; I'm hoping that won't be necessary though.

**Comment by rmcrackan** [comment]
Since this look like it was a network thing, I'm going to close this issue and open a [new issue](https://github.com/rmcrackan/AudibleApi/issues/31) with the audible api about the ridiculous logs that timeouts can cause.

**Comment by ilicity** [comment]
@Mbucari 
> Geeze those logs are a mess!
@rmcrackan 
> That log file is ... special

I took a peek before i sent it. It scared me.

It was an error popup. however, i was able to close it and libation would continue to function, minus the scanning

Network issue makes sense though. My internet was having an absolute fit. I just didn't realize, just exactly how much of a fit it was having.
