### ISSUE TITLE
Fails to Scan, 0 Parents Found 8.X

### ISSUE THREAD

**Issue by spiralingtides** [rmcrackan/Libation#301]
[_Log202206.log](https://github.com/rmcrackan/Libation/files/8986234/_Log202206.log)
Attempting to scan library in version 8 or higher results in the above error, and no books being found. I tried this with 8.1.3, 8, 7.10.1, and 7.10. With the 7.X versions it worked as expected.

**Comment by spiralingtides** [comment]
Found 0 parents for B08GCFQ7N8

   at AudibleUtilities.ApiExtended.getChildEpisodesAsync(SemaphoreSlim concurrencySemaphore, Item parent) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 212
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 149
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 213
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 197
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 120
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by rmcrackan** [comment]
Fixed in [version 8.1.5](https://github.com/rmcrackan/Libation/releases/latest)
