### ISSUE TITLE
Unable to scan library

### ISSUE THREAD

**Issue by Psazich** [rmcrackan/Libation#362]
Just readded my amazon account after formatting my computer. Libation worked fine preformat, getting this error when trying to scan my library now.

Log is attached, and I copy/pasted the error message from Libation below. Thank you

[_Log202208.log](https://github.com/rmcrackan/Libation/files/9365984/_Log202208.log)

The instance of entity type 'BookContributor' cannot be tracked because another instance with the same key value for {'BookId', 'ContributorId', 'Role'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at DtoImporterService.BookImporter.createNewBook(ImportItem importItem) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\BookImporter.cs:line 117
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\BookImporter.cs:line 64
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\BookImporter.cs:line 39
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.ImporterBase`1.Import(T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\ImporterBase.cs:line 21
   at DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\LibraryBookImporter.cs:line 23
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.ImporterBase`1.Import(T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\DtoImporterService\ImporterBase.cs:line 21
   at ApplicationServices.LibraryCommands.<>c__DisplayClass18_0.<importIntoDbAsync>b__1() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 225
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 225
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 147
   at LibationAvalonia.Views.MainWindow.scanLibrariesAsync(Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationAvalonia\Views\MainWindow\MainWindow.ScanManual.axaml.cs:line 65

**Comment by rmcrackan** [comment]
In the Import menu, turn off auto-scan then try again for your first full scan.

If you're still having problems: since you're starting from scratch anyway, there's no harm in deleting your database to see if that helps.

* open the folder for your log file
* close Libation
* delete `LibationContext.db` and the folder `SearchEngine`
* restart Libation
* do a new manual scan

Let me know if you're still seeing this error.

**Comment by Psazich** [comment]
I've tried the steps above, except deleting the SearchEngine folder, it's not there to delete. I believe it's getting held up because one book in particular. The book "The Best American Science Fiction and Fantasy 2021" ID: 0358578396 shows up in the logs repeatedly. Maybe the way that Audible tagged it is causing the issue?

**Comment by rmcrackan** [comment]
Is the result the same if you try to use windows Classic instead of Chardonnay?

**Comment by rmcrackan** [comment]
Nevermind. I see it. That's a first -- audible listed the same author twice in the author list.

**Comment by rmcrackan** [comment]
Thanks for pointing out that book. It was indeed the problem.

I just released [v8.4.2](https://github.com/rmcrackan/Libation/releases/tag/v8.4.2) to address your issue. Please try it and let me know if this fixes your import error. This is technically a "pre-release" because I'm going on vacation soon and I don't want to risk putting out a bad full release then people are stuck with it until I return to angry emails.

**Comment by Psazich** [comment]
I just tried again with the newest version and it scanned my library correctly. I even downloaded and converted the book in question to confirm and it worked. Thank you for the quick response and resolving the issue so quickly. Enjoy your vacation!
