### ISSUE TITLE
Error importing library 

### ISSUE THREAD

**Issue by myopica** [rmcrackan/Libation#373]
After much faffing around I eventually received this notification, I'd tried three times earlier but literally nothing happened until I added an additional account to check and then I got this message :

One or more errors occurred. (Exception of type 'AudibleApi.ApiErrorException' was thrown.)

   at AudibleApi.Api.GetLibraryItemAsyncEnumerable(LibraryOptions libraryOptions, Int32 numItemsPerRequest, Int32 maxConcurrentRequests)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 316
   at AudibleApi.Api.GetLibraryItemAsyncEnumerable(LibraryOptions libraryOptions, Int32 numItemsPerRequest, Int32 maxConcurrentRequests)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 171
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 171
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 213
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 197
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 120
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77
[Log202209_001.log](https://github.com/rmcrackan/Libation/files/9629834/Log202209_001.log)

**Comment by rmcrackan** [comment]
Part of the logs has "The request failed due to timeout." Obviously this happens if you're having an actual network issue and it might also be hiding another issue while communicating with audible. Please try again today and let me know the result.

**Comment by myopica** [comment]
Great news, it worked. Thank you so much, I'll go to GitHub and post this result. --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 9/23/22, 1:01 PM rmcrackan ***@***.***> wrote:

   
  Part of the logs has "The request failed due to timeout." Obviously this happens if you're having an actual network issue and it might also be hiding another issue while communicating with audible. Please try again today and let me know the result.

**Comment by rmcrackan** [comment]
Nice! Thanks for following up.
