### ISSUE TITLE
Unable to liberate some books

### ISSUE THREAD

**Issue by 1100101** [rmcrackan/Libation#447]
**Describe the bug**
I have a library of ~90 books, and while most of them liberate just fine, some of them fail, with no file being downloaded.

**NOTE**: This issue only happens if the setting `Allow libation to fixup audiobook metadata` is enabled.

**To Reproduce**
1. Add https://www.audible.de/pd/Die-drei-und-der-Super-Papagei-Hoerbuch/B0B1QKF361 to your account 
2. Enable "Allow libation to fixup audiobook metadata"
3. Try to liberate the book
4. FAIL

**Expected behavior**
The book should download just as any other book

**Platform**
Windows 11, Libation 8.8.21

**Log Files**
There's an exception listed in the log file related to the issue:
```
 {}2023-01-11 23:02:51.824 +01:00 [INF] (at LibationAvalonia.Views.MainWindow+<ProductsDisplay_LiberateClicked>d__31.MoveNext()) Begin single book backup of 11.01.2023 [B0B1QKF361] Die drei ??? und der Super-Papagei: Die drei ??? 1
 {}2023-01-11 23:02:51.833 +01:00 [INF] (at LibationAvalonia.ViewModels.ProcessQueueViewModel.AddDownloadDecrypt(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Queueing 1 books
 {}2023-01-11 23:02:51.843 +01:00 [INF] (at LibationAvalonia.ViewModels.ProcessQueueViewModel+<QueueLoop>d__68.MoveNext()) Begin processing queue
 {}2023-01-11 23:02:51.845 +01:00 [INF] (at LibationAvalonia.ViewModels.ProcessQueueViewModel+<QueueLoop>d__68.MoveNext()) Begin processing queued item. 11.01.2023 [B0B1QKF361] Die drei ??? und der Super-Papagei: Die drei ??? 1
 {}2023-01-11 23:02:51.846 +01:00 [INF] (at FileLiberator.Processable+<ProcessSingleAsync>d__23.MoveNext()) Begin ProcessSingleAsync {"Title":"Die drei ??? und der Super-Papagei: Die drei ??? 1","AudibleProductId":"B0B1QKF361","Locale":"germany","Account":"a[...]h.f[...]k@g[...]l.c[...]m"}
 {}2023-01-11 23:02:51.849 +01:00 [INF] (at LibationAvalonia.ViewModels.ProcessBookViewModel.Processable_Begin(System.Object, DataLayer.LibraryBook)) Automated backup: 
Download & Decrypt Step, Begin: [B0B1QKF361] Die drei ??? und der Super-Papagei: Die drei ??? 1
 {}2023-01-11 23:02:51.853 +01:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__9.MoveNext()) {"Username":"a[...]h.f[...]k@g[...]l.c[...]m","LocaleName":"germany"}
 {}2023-01-11 23:02:52.303 +01:00 [INF] (at AaxDecrypter.AaxcDownloadSingleConverter+<RunAsync>d__1.MoveNext()) Begin download and convert Aaxc To "M4b"
 {}2023-01-11 23:02:52.313 +01:00 [INF] (at AaxDecrypter.AaxcDownloadSingleConverter+<RunAsync>d__1.MoveNext()) Begin Step 1: Get Aaxc Metadata
 {}2023-01-11 23:02:52.375 +01:00 [ERR] (at AaxDecrypter.AaxcDownloadSingleConverter+<RunAsync>d__1.MoveNext()) Error encountered in download and convert Aaxc To "M4b"
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Text.Encoding.GetBytes(String s)
   at Mpeg4Lib.Boxes.AppleListBox.EditOrAddTag(String name, String data)
   at AaxDecrypter.AaxcDownloadConvertBase.Step_GetMetadata() in D:\a\Libation\Libation\Source\AaxDecrypter\AaxcDownloadConvertBase.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AaxDecrypter.AaxcDownloadSingleConverter.RunAsync() in D:\a\Libation\Libation\Source\AaxDecrypter\AaxcDownloadSingleConverter.cs:line 23
 {"ExceptionDetail":{"Type":"System.ArgumentNullException","HResult":-2147467261,"Message":"Value cannot be null. (Parameter 's')","Source":"System.Private.CoreLib","TargetSite":"Void Throw(System.String)","ParamName":"s"}}2023-01-11 23:02:52.378 +01:00 [INF] (at LibationAvalonia.ViewModels.ProcessBookViewModel+<Processable_Completed>d__76.MoveNext()) Automated backup: Download & Decrypt Step, Completed: [B0B1QKF361] Die drei ??? und der Super-Papagei: Die drei ??? 1
 {}2023-01-11 23:02:52.381 +01:00 [ERR] (at LibationAvalonia.ViewModels.ProcessBookViewModel+<ProcessOneAsync>d__59.MoveNext()) Download & Decrypt:  Decrypt failed

```

**Comment by rmcrackan** [comment]
Sorry about this. The code is now fixed. The next version of Libation will include this bug fix. I'm about to leave town for a bit and I'll create a new version when I return.
