### ISSUE TITLE
error saving book's location 

### ISSUE THREAD

**Issue by TatyMissy** [rmcrackan/Libation#472]
non riesco a trovare il file appena scaricato mi da questo errore

Invalid URI: The hostname could not be parsed.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri.CreateUri(Uri baseUri, String relativeUri, Boolean dontEscape)
   at Avalonia.Platform.Storage.FileIO.BclStorageFolder.TryGetUri(Uri& uri) in /_/src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs:line 82
   at Avalonia.Win32.Win32StorageProvider.<>c__DisplayClass13_0.<ShowFilePicker>b__0() in /_/src/Windows/Avalonia.Win32/Win32StorageProvider.cs:line 137
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Avalonia.Win32.Win32StorageProvider.OpenFilePickerAsync(FilePickerOpenOptions options) in /_/src/Windows/Avalonia.Win32/Win32StorageProvider.cs:line 50
   at LibationAvalonia.Views.ProductsDisplay.<>c__DisplayClass9_1.<<ProductsGrid_CellContextMenuStripNeeded>b__3>d.MoveNext() in D:\a\Libation\Libation\Source\LibationAvalonia\Views\ProductsDisplay.axaml.cs:line 121
   
   
   cosa devo fare? prima dell'aggiornamento funzionava  per favore grazie

**Comment by Mbucari** [comment]
@rmcrackan Avalonia's OpenFile Dialog doesn't like window's `\\?\` path prefix.

You need to add ".PathWithoutPrefix" to Books LongPath here.

https://github.com/rmcrackan/Libation/blob/40602c76268b7183fdd793986ca6eb40e2bdfe84/Source/LibationAvalonia/Views/ProductsDisplay.axaml.cs#L114

**Comment by TatyMissy** [comment]
Perdonami io non sono esperta di queste cose mi dici come fare? Grazie mille


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: ***@***.***>
Inviato: sabato 4 febbraio 2023 15:50
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [rmcrackan/Libation] error saving book's location (Issue #472)


@rmcrackan<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frmcrackan&data=05%7C01%7C%7Cd6ef2fe3d7544772895c08db06bf2ec6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111190405502151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=33vub66IuN2tDNTp4PvnRAj6nDlz0KO%2BwQeRbRu1Dkc%3D&reserved=0> Avalonia's OpenFile Dialog doesn't like window's \\?\ path prefix.

You need to add ".PathWithoutPrefix" to Books LongPath here.

https://github.com/rmcrackan/Libation/blob/40602c76268b7183fdd793986ca6eb40e2bdfe84/Source/LibationAvalonia/Views/ProductsDisplay.axaml.cs#L114<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frmcrackan%2FLibation%2Fblob%2F40602c76268b7183fdd793986ca6eb40e2bdfe84%2FSource%2FLibationAvalonia%2FViews%2FProductsDisplay.axaml.cs%23L114&data=05%7C01%7C%7Cd6ef2fe3d7544772895c08db06bf2ec6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111190405502151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r1jN3AZr%2BYq1eN8x5L08JMYpxmuCENNSZtxXTil%2BFRM%3D&reserved=0>

**Comment by Mbucari** [comment]
> Perdonami io non sono esperta di queste cose mi dici come fare? Grazie mille

Questo è un problema nel programma. Stavo dicendo a rmcrackan come risolverlo. Devi aspettare che rmcrackan lo risolva.

**Comment by TatyMissy** [comment]
a ok ti ringrazio tanto, scusami ancora purtroppo sono davvero poco esperta di queste cose non avevo capito, aspetto risoluzione perche al momento non mi fa trovare i file, grazie ancora per tutto

**Comment by Mbucari** [comment]
Fino a quando non viene risolto, puoi utilizzare l'altra versione di Windows.

https://github.com/rmcrackan/Libation/releases/download/v9.2.1/Classic-Libation.9.2.1-windows-classic.zip

**Comment by TatyMissy** [comment]
si va benissimo aspetto notizie sei stato gentilissimo grazie ancora

**Comment by rmcrackan** [comment]
The fix is live in the [latest version: 9.2.2](https://github.com/rmcrackan/Libation/releases/latest). Please let us know if it does not work.
