### ISSUE TITLE
Error Importing Library when on a VPN

### ISSUE THREAD

**Issue by 1BrianShaw** [rmcrackan/Libation#477]
**Describe the bug**
I filled out the report below when I could not import my library.  I filled out everything before realizing my VPN was on.  I turned it off and resolved this issue.  I would suggest noting to have any VPNs off when importing but here is the information if you would rather know why the vpn was an issue at all.  Do I need to have a specific site filtered out of my VPN so this can update when my VPN is on?

**To Reproduce**

Have VPN on
In initial setup and import.
Select Import
enter in Audible Password
Error is generated

Next 
Select Import
click to login to browser 
paste URL into your browser
input login information in browser
reach the Error on Amazon page (indicating success) 
paste URL into the text box on Libation
click submit
Generate Same error

**Expected behavior**
Successfully import my library

**Screenshots**
attached

**Platform**
Edition	Windows 11 Pro
Version	22H2
Installed on	‎1/‎22/‎2023
OS build	22621.1194
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Log Files**

Error in program
Could not register

   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/Authorize.cs:line 72
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 103
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 38
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 31
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 34
   at AudibleApi.EzApiCreator.createApiAsync(Identity inMemoryIdentity, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 18
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.LoginChoiceEager.cs:line 29
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 34
   at LibationAvalonia.Dialogs.Login.AvaloniaLoginChoiceEager.ApiExtendedFunc(Account account) in D:\a\Libation\Libation\Source\LibationAvalonia\Dialogs\Login\AvaloniaLoginChoiceEager.cs:line 11
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 174
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 120
   at LibationAvalonia.Views.MainWindow.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\Views\MainWindow.ScanManual.cs:line 65

[_Log202302.log](https://github.com/rmcrackan/Libation/files/10676506/_Log202302.log)
![Screenshot_1](https://user-images.githubusercontent.com/123191227/217283786-653da503-8a79-4eb3-a62b-9536e78b2bc6.png)

**Comment by rmcrackan** [comment]
A VPN isn't an issue per se. I sometimes accidentally leave my VPN on while scanning also. I suspect you're VPN'd into a region or network which also can't reach those paths.

**Comment by 1BrianShaw** [comment]
I used NordVPN and had a US VPN selected, my library is US as well.  to test it out I added a book to my library and then asked my library to update while on the VPN and got this issue again.  I ended the VPN and scanned my library again, it worked without a problem. At this point its just an FYI anyways but thought you should know

**Comment by 1BrianShaw** [comment]
Yes and I successfully reached the nothing here window logging into audible via copying and pasting the url you provided.  I pasted the resulting url in and it generated the error

**Comment by rmcrackan** [comment]
Thank you for bringing this to our attention. As much as this sucks, since the only way to experience (or test) this is with a NordVPN account, I'm going to close this for now. I'll keep it in mind in case I ever get an account with this particular vpn.

Thanks again!
