### ISSUE TITLE
Error Importing library and error downloading books

### ISSUE THREAD

**Issue by sevenVIIghosts** [rmcrackan/Libation#484]
Device name	DESKTOP-644B36F
Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
Installed RAM	32.0 GB
Device ID	A2977D15-8441-4C74-86BE-4A5785BEFCCE
Product ID	00330-50000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Initial login added all books to library. When attempting to download the books though I receive an error on every single one. Attempts to manually scan my library also receives and error.
Could not register

   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/Authorize.cs:line 72
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 103
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 42
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 32
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 36
   at AudibleApi.EzApiCreator.createApiAsync(Identity inMemoryIdentity, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 18
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.LoginChoiceEager.cs:line 29
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 34
   at LibationAvalonia.Dialogs.Login.AvaloniaLoginChoiceEager.ApiExtendedFunc(Account account) in D:\a\Libation\Libation\Source\LibationAvalonia\Dialogs\Login\AvaloniaLoginChoiceEager.cs:line 11
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 174
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 120
   at LibationAvalonia.Views.MainWindow.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\Views\MainWindow.ScanManual.cs:line 65

![image](https://user-images.githubusercontent.com/124934735/217940550-a358e285-91ec-408e-9741-583bf177eea3.png)

**Log Files**
Attach your Libation log file here.
[_Log202302.log](https://github.com/rmcrackan/Libation/files/10701515/_Log202302.log)

**Comment by rmcrackan** [comment]
So sorry about this. Much thanks for all these details.

I've seen this happen a few times in the past and it nearly always resolves itself after about 1 day. Let's wait for 24 hours, try again, and if it still doesn't work, please attach the new log file to this issue.

**Comment by rmcrackan** [comment]
Following up -- is this problem still happening?

**Comment by sevenVIIghosts** [comment]
It was but the update the other day seems to have fixed it. I was able to
download all my books

**Comment by rmcrackan** [comment]
W00h00 -- glad to hear it 😄
