### ISSUE TITLE
Audible Account failed for pre-amazon - germany

### ISSUE THREAD

**Issue by elvquant** [rmcrackan/Libation#532]
Trying to Login Aubible-Account via Browser (inside has infinite capcha loop)

Add account username and pre-amazon-germany
Scan Library
Audible Login: click here to login with your browser
(Login-Process successful)
Copy URL from sorry-page
Waiting some seconds and the following Error occurs

Platform: Mac x86 (macOS 12.6.2)

Error getting value from 'Cookies' on 'AudibleApi.Authorization.Identity'.

   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
   at Dinah.Core.IO.JsonFilePersister`1.saveFile(Object _, EventArgs __)
   at AudibleApi.Authorization.Identity.Update(PrivateKey privateKey, AdpToken adpToken, AccessToken accessToken, RefreshToken refreshToken, IEnumerable`1 cookies, String deviceSerialNumber, String deviceType, String amazonAccountId, String deviceName, String storeAuthenticationCookie) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/Identity [partial].cs:line 96
   at AudibleApi.Authorization.RegistrationParser.ParseRegistrationIntoIdentity(JObject authRegister, IIdentity identity, ISystemDateTime systemDateTime) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/RegistrationParser.cs:line 32
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 101
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 36
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 29
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 31
   at AudibleApi.EzApiCreator.createApiAsync(Identity inMemoryIdentity, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 15
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.LoginChoiceEager.cs:line 29
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in /Users/runner/work/Libation/Libation/Source/AudibleUtilities/ApiExtended.cs:line 38
   at LibationAvalonia.Dialogs.Login.AvaloniaLoginChoiceEager.ApiExtendedFunc(Account account) in /Users/runner/work/Libation/Libation/Source/LibationAvalonia/Dialogs/Login/AvaloniaLoginChoiceEager.cs:line 12
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in /Users/runner/work/Libation/Libation/Source/ApplicationServices/LibraryCommands.cs:line 186
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in /Users/runner/work/Libation/Libation/Source/ApplicationServices/LibraryCommands.cs:line 124
   at LibationAvalonia.Views.MainWindow.scanLibrariesAsync(Account[] accounts) in /Users/runner/work/Libation/Libation/Source/LibationAvalonia/Views/MainWindow.ScanManual.cs:line 66

**Comment by elvquant** [comment]
[Log202303.log](https://github.com/rmcrackan/Libation/files/10978461/Log202303.log)

**Comment by elvquant** [comment]
Cross check with an amazon-account (germany) works well via browser

**Comment by Mbucari** [comment]
@elvquant Are you able to log in via the in-app login method with username and password?

@rmcrackan Do you have a pre-amazon audible account? I don't, so I can't test or debug the web browser login. My first instinct is to create an empty list if cookies is null on this line.
https://github.com/rmcrackan/AudibleApi/blob/3e9c97b62ec02e6e6109f2327037a9f309f51ba0/AudibleApi/Authorization/Identity%20%5Bpartial%5D.cs#L88

Thoughts?

**Comment by rmcrackan** [comment]
Unfortunately I have no pre-audible accounts. mkb79 does and he's even in Germany.

**Comment by rmcrackan** [comment]
It looks like this may simply be a case where we just need better NRE handling. Esp given what mkb79 says above about the lack of `website_cookies`

**Comment by mkb79** [comment]
No I does not have a pre-Amazon account. But someone had give me his credentials so I could find these out.

**Comment by rmcrackan** [comment]
Whoops. My mistake. Well, he has more access than I do in any case

**Comment by mkb79** [comment]
Yeah. I was wondering at the time about the missing `website_cookies` key. They where not None or an empty array. There where complete left out.

**Comment by rmcrackan** [comment]
Sorry for all the back and forth of closed and re-open. Github is overly helpful and automatically closes the ticket when fixes are created for this issue; whether or not the fix has been verified.

**Comment by rmcrackan** [comment]
Thank you for your patience. Please try the [new version 9.4.6](https://github.com/rmcrackan/Libation/releases/latest) and let us know if you're still seeing this issue.

**Comment by Mbucari** [comment]
> Thank you for your patience.

patience?! Eight hours from report to patch is practically light speed! :laughing:

**Comment by rmcrackan** [comment]
lol Fair enough. I was thinking more that he shouldn't have had to wait at all. This was presumably our bug. In this situation I always feel contrite.

**Comment by elvquant** [comment]
Many thanks to you for the light speed reaction!

@Mbucari i tryed in-app login before. It ends with endless captcha loop.

@rmcrackan i will try the new version 9.4.6 and let you know the result.

**Comment by elvquant** [comment]
Adding Login Aubible-Account via Browser again ... and it works! Many thanks for lightspeed fix.
