### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by Weldawadyathink** [rmcrackan/Libation#596]
The docker image currently only supports amd64. I run my audiobook server on an Oracle cloud ampere server, which is arm64. It appears that the normal application is already bundled for linux/arm64, so I am hoping it is a simple change to bundle docker for arm. 

I have been trying to get this running myself, but I have absolutely no experience with dotnet. I will keep trying, and if I get anything usable, I will add a pull request.

**Comment by Weldawadyathink** [comment]
I got the docker file to compile correctly, but libation doesn't seem to work. 

Dockerfile (somewhat generated by GPT-4)
`ARG TARGET_ARCH
ARG TARGETPLATFORM
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
ARG TARGET_ARCH

COPY Source /Source
RUN dotnet publish -c Release -o /Source/bin/Publish/Linux-chardonnay --runtime linux-${TARGET_ARCH} /Source/LibationCli/LibationCli.csproj -p:PublishProfile=/Source/LibationCli/Properties/PublishProfiles/LinuxProfile.pubxml -p:RuntimeIdentifier=linux-${TARGET_ARCH}
COPY Docker/liberate.sh /Source/bin/Publish/Linux-chardonnay

FROM --platform=$TARGETPLATFORM mcr.microsoft.com/dotnet/runtime:7.0

ENV SLEEP_TIME "30m"

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN mkdir /db /config /data

# Install FFmpeg and LAME libraries
RUN apt-get update && apt-get install -y \
    ffmpeg \
    lame \
    libmp3lame-dev

COPY --from=build-env /Source/bin/Publish/Linux-chardonnay /libation

CMD ["./libation/liberate.sh"]
`

Error log:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleApi.EzApiCreator.createApiAsync(String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator [partial].cs:line 25
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.NoLogin.cs:line 36
   at AudibleUtilities.ApiExtended.CreateAsync(String username, String localeName) in /Source/AudibleUtilities/ApiExtended.cs:line 72
   at FileLiberator.UtilityExtensions.GetApiAsync(LibraryBook libraryBook) in /Source/FileLiberator/UtilityExtensions.cs:line 25
   at FileLiberator.DownloadDecryptBook.downloadAudiobookAsync(LibraryBook libraryBook) in /Source/FileLiberator/DownloadDecryptBook.cs:line 135
   at FileLiberator.DownloadDecryptBook.ProcessAsync(LibraryBook libraryBook) in /Source/FileLiberator/DownloadDecryptBook.cs:line 95
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in /Source/FileLiberator/Processable.cs:line 60
   at LibationCli.ProcessableOptionsBase.ProcessOneAsync(Processable Processable, LibraryBook libraryBook, Boolean validate) in /Source/LibationCli/Options/_ProcessableOptionsBase.cs:line 65
 {"ExceptionDetail":{"Type":"System.NullReferenceException","HResult":-2147467261,"Message":"Object reference not set to an instance of an object.","Source":"Dinah.Core","TargetSite":"T FromJson[T](System.String, System.String, Newtonsoft.Json.JsonSerializerSettings)"}}2023-05-07 00:31:56.509 +00:00 [INF] (at Dinah.Core.IO.MultiTextWriter.WriteLine(System.String)) Done. All books have been processed
`

Looks like there is some issue with the json decoding. Gotta admit I am a bit out of my depth on this.

**Comment by Ejmathewp** [comment]
I looked back through the pull requests and the tags on docker hub and it doesn't seem like the arm64 docker support ever got merged? @Weldawadyathink do you still have the modifications you made to issue a pull request?

**Comment by Weldawadyathink** [comment]
@Ejmathewp I remember I ran into some roadblocks but I don't remember what they were. It looks like I already deleted my fork of the repo, so I don't still have those commits. I ended up just having a separate VPS that was x86 for Libation. Sorry!
