### ISSUE TITLE
I don't code & don't know what this means:

### ISSUE THREAD

**Issue by qmab47** [rmcrackan/Libation#641]
Could not load file or assembly 'System.Linq.Queryable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

   at DataLayer.LibraryBookQueries.GetLibrary(IQueryable`1 library)
   at DataLayer.LibraryBookQueries.GetLibrary_Flat_NoTracking(LibationContext context, Boolean includeParents) in D:\a\Libation\Libation\Source\DataLayer\QueryObjects\LibraryBookQueries.cs:line 19
   at ApplicationServices.DbContexts.GetLibrary_Flat_NoTracking(Boolean includeParents) in D:\a\Libation\Libation\Source\ApplicationServices\DbContexts.cs:line 18
   at ApplicationServices.LibraryCommands.GetCounts(IEnumerable`1 libraryBooks) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 591
   at LibationWinForms.Form1.UpdateCountsBw_DoWork(Object sender, DoWorkEventArgs e) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.BackupCounts.cs:line 43
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by rmcrackan** [comment]
> I don't code & don't know what this means

It means that those of us who do code must have goofed. Sorry about this! Can you attach your Log file to this ticket? It will tell us more about the error.

**Comment by qmab47** [comment]
So I deleted it and re-downloaded Libation and now cannot get it to open. I have a Windows computer, though I doubt without seeing the log files, could figure it out.

**Comment by qmab47** [comment]
[_Log202306_004.log](https://github.com/rmcrackan/Libation/files/11860137/_Log202306_004.log)

**Comment by qmab47** [comment]
[_Log202306_006.log](https://github.com/rmcrackan/Libation/files/11860138/_Log202306_006.log)

**Comment by qmab47** [comment]
[_Log202306_001.log](https://github.com/rmcrackan/Libation/files/11860139/_Log202306_001.log)

**Comment by qmab47** [comment]
[_Log202306.log](https://github.com/rmcrackan/Libation/files/11860141/_Log202306.log)

**Comment by Mbucari** [comment]
If Libation won't even open then something is wrong with its configuration. Try renaming the `%userprofile%\Libation` folder to `LibationBAK`, then relaunch Libation. Libation will prompt you for setup, just select "New User".

If that works, close Libation and copy your old `AccountsSettings.json` and `LibationContext.db` from `LibationBAK` into `%userprofile%\Libation` and then restart. If that works, copy over `FileLocations.json` and `QuickFilters.json` as well. I would not copy `Settings.json`, so you should re-enter your settings.

**Comment by rmcrackan** [comment]
@qmab47 Any luck after following @Mbucari 's ideas?

**Comment by runehizen** [comment]
hi i cant seem to download some of my books , quite a few and i started skiping them but now it wont start downloading any of them  this is the coad error im getting 
SQLite Error 10: 'disk I/O error'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Dinah.EntityFrameworkCore.DesignTimeDbContextFactoryBase`1.Create(String connectionString)
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 316
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 137
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by Mbucari** [comment]
@runehizen Is your hard drive full?

**Comment by runehizen** [comment]
Im sure its not. But ill double-check when home

**Comment by rmcrackan** [comment]
This ticket seems to have gone stale so I'll close it. If you have an update though, I'll be glad to re-open it.
