### ISSUE TITLE
Libation won't launch

### ISSUE THREAD

**Issue by jumplinjake** [rmcrackan/Libation#643]
The type initializer for 'LibationFileManager.AudibleFileStorage' threw an exception.

   at LibationFileManager.AudibleFileStorage.get_BooksDirectory() in D:\a\Libation\Libation\Source\LibationFileManager\AudibleFileStorage.cs:line 41
   at AppScaffolding.LibationScaffolding.logStartupState(Configuration config) in D:\a\Libation\Libation\Source\AppScaffolding\LibationScaffolding.cs:line 239
   at AppScaffolding.LibationScaffolding.RunPostMigrationScaffolding(Configuration config) in D:\a\Libation\Libation\Source\AppScaffolding\LibationScaffolding.cs:line 112
   at LibationWinForms.Program.Main() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 55
[_Log202306.zip](https://github.com/rmcrackan/Libation/files/11863821/_Log202306.zip)

**Comment by jumplinjake** [comment]
I guess I needed to add permission to access a folder.  once I did that it works again

**Comment by rmcrackan** [comment]
Great. Glad it's working for you again.
