### ISSUE TITLE
Libation terminates with an unhandled exception

### ISSUE THREAD

**Issue by octaquist** [rmcrackan/Libation#645]
`Unhandled exception. System.TypeInitializationException: The type initializer for 'LibationFileManager.Configuration' threw an exception.
 ---> System.ApplicationException: Could not locate or create appsettings.json
   at LibationFileManager.Configuration.getOrCreateAppsettingsFile() in /home/runner/work/Libation/Libation/Source/LibationFileManager/Configuration.LibationFiles.cs:line 119
   at LibationFileManager.Configuration..cctor() in /home/runner/work/Libation/Libation/Source/LibationFileManager/Configuration.LibationFiles.cs:line 14
   --- End of inner exception stack trace ---
   at LibationFileManager.Configuration.get_IsMacOs() in /home/runner/work/Libation/Libation/Source/LibationFileManager/Configuration.Environment.cs:line 22
   at LibationAvalonia.Program.Main(String[] args) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/Program.cs:line 21
[1]    4730 IOT instruction (core dumped)  libation`

I've tried `touch ~/.config/libation/appsettings.json` to no avail...

**Comment by Mbucari** [comment]
Are you using one of the installers? If so, which one?

**Comment by Mbucari** [comment]
Also, which distro are you running?

**Comment by rmcrackan** [comment]
This ticket seems to have gone stale so I'll close it. If you have an update though, I'll be glad to re-open it.
