### ISSUE TITLE
AccountsSettings.json corrupted, Libation wouldn't start

### ISSUE THREAD

**Issue by aheber** [rmcrackan/Libation#649]
**Describe the bug**
When trying to open Libation, it would start and I could see the screen, then it would close. I tried multiple versions and saw the same behavior. When I looked at the Windows Event Viewer I could see it was crashing trying to parse a JSON file. I reviewed the JSON files in my user's Libation folder and found the AccountsSettings.json file was empty.
I delete/renamed the file and Libation was able to recreate it and allowed me to login again.

**To Reproduce**
I don't know how it got in this state.

**Expected behavior**
Failure to parse a JSON fail should report the problem instead of crashing without error text.

**Platform**
Windows 11

**Logs**
```
{}2023-06-01 18:21:26.670 -06:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Error importing library
AudibleApi.Authorization.RegistrationException: Error ensuring valid state
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Dinah.Core.IO.JsonFilePersister`1.saveFile(Object _, EventArgs __)
   at AudibleApi.Authorization.Identity.Invalidate() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/Identity [partial].cs:line 103
   at AudibleApi.Authorization.IdentityMaintainer.DeregisterAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 113
   at AudibleApi.Authorization.IdentityMaintainer.EnsureStateAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 90
   --- End of inner exception stack trace ---
   at AudibleApi.Authorization.IdentityMaintainer.EnsureStateAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 90
   at AudibleApi.Authorization.IdentityMaintainer.GetAdpTokenAsync() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authorization/IdentityMaintainer.cs:line 61
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, JObject requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 59
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 229
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 366
   at AudibleApi.Api.GetLibraryItemAsyncEnumerable(LibraryOptions libraryOptions, Int32 numItemsPerRequest, Int32 maxConcurrentRequests)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 316
   at AudibleApi.Api.GetLibraryItemAsyncEnumerable(LibraryOptions libraryOptions, Int32 numItemsPerRequest, Int32 maxConcurrentRequests)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 171
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 171
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 202
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 184
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 166
 {"ExceptionDetail":{"HResult":-2146233088,"Message":"Error ensuring valid state","Source":"AudibleApi","TargetSite":"Void MoveNext()","InnerException":{"HResult":-2146233088,"Message":"Error reading JObject from JsonReader. Path '', line 0, position 0.","Source":"Newtonsoft.Json","TargetSite":"Newtonsoft.Json.Linq.JObject Load(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Linq.JsonLoadSettings)","LineNumber":0,"LinePosition":0,"Path":"","Type":"Newtonsoft.Json.JsonReaderException"},"Type":"AudibleApi.Authorization.RegistrationException"}}2023-06-01 18:21:26.693 -06:00 [ERR] (at LibationAvalonia.Views.MainWindow+<>c+<<Configure_ScanAuto>b__51_0>d.MoveNext()) Error invoking auto-scan
```

**Comment by rmcrackan** [comment]
> I delete/renamed the file and Libation was able to recreate it and allowed me to login again.

Sounds like it somehow got into a bad state and you fixed it by deleting the file. Since you solved this problem, I'll close the ticket. I'll look into this case later though.

**Comment by aheber** [comment]
Thanks, just wanted to make sure I made you aware of it.
