### ISSUE TITLE
Confusing error message on Linux install

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#650]
**Describe the bug**
I get the following text output when I run Libation, although it was running fine until today. Does anyone know where this text comes from? The first line having a blank path is especially offputting :) .

(I've changed my mind, I'll paste in the log of the run, it contains the same text plus more info. The actual text printed that halts the run is the second exception, saying something about extra text in some unstated JSON file.)

**Platform**

Ubuntu 22.04 LTS

**Log Files**
```
 {}2023-06-30 22:30:04.699 -07:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"LibationCli","Version":"9.4.4.1","ReleaseIdentifier":"None","OS":"Linux","InteropFunctionsType":"LinuxConfigApp.LinuxInterop","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":true,"LibationFiles":"/home/william/Libation","BooksDirectory":"/home/william/Libation/Books","InProgress":"/home/william/Libation/tmp","DownloadsInProgressDirectory":"/home/william/Libation/tmp/DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDirectory":"/home/william/Libation/tmp/DecryptInProgress","DecryptInProgressFiles":0}
 {}2023-06-30 22:30:05.471 -07:00 [ERR] (at AppScaffolding.LibationScaffolding.getLatestRelease(System.TimeSpan)) Checking for new version too often
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'pattern'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'pattern')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture)
   at AppScaffolding.LibationScaffolding.getLatestRelease() in /home/runner/work/Libation/Libation/Source/AppScaffolding/LibationScaffolding.cs:line 327
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at AppScaffolding.LibationScaffolding.getLatestRelease(TimeSpan timeout) in /home/runner/work/Libation/Libation/Source/AppScaffolding/LibationScaffolding.cs:line 305
 {"ExceptionDetail":{"Type":"System.AggregateException","HResult":-2146233088,"Message":"One or more errors occurred. (Value cannot be null. (Parameter 'pattern'))","Source":"System.Private.CoreLib","TargetSite":"Void ThrowIfExceptional(Boolean)","InnerException":{"Type":"System.ArgumentNullException","HResult":-2147467261,"Message":"Value cannot be null. (Parameter 'pattern')","Source":"System.Text.RegularExpressions","TargetSite":"Void ThrowArgumentNullException(System.Text.RegularExpressions.ExceptionArgument)","ParamName":"pattern"},"InnerExceptions":[{"Type":"System.ArgumentNullException","HResult":-2147467261,"Message":"Value cannot be null. (Parameter 'pattern')","Source":"System.Text.RegularExpressions","TargetSite":"Void ThrowArgumentNullException(System.Text.RegularExpressions.ExceptionArgument)","ParamName":"pattern"}]}}2023-06-30 22:30:05.697 -07:00 [INF] (at Dinah.Core.IO.MultiTextWriter.WriteLine(System.String)) ERROR
 {}2023-06-30 22:30:05.698 -07:00 [INF] (at Dinah.Core.IO.MultiTextWriter.WriteLine(System.String)) =====
 {}2023-06-30 22:30:05.698 -07:00 [INF] (at Dinah.Core.IO.MultiTextWriter.WriteLine(System.String)) Additional text encountered after finished reading JSON content: }. Path '', line 104, position 1.
 {}2023-06-30 22:30:05.700 -07:00 [INF] (at Dinah.Core.IO.MultiTextWriter.WriteLine(System.String))    at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in /home/runner/work/Libation/Libation/Source/AudibleUtilities/AudibleApiStorage.cs:line 20
   at LibationCli.ScanOptions.getAccounts() in /home/runner/work/Libation/Libation/Source/LibationCli/Options/ScanOptions.cs:line 44
   at LibationCli.ScanOptions.ProcessAsync() in /home/runner/work/Libation/Libation/Source/LibationCli/Options/ScanOptions.cs:line 19
   at LibationCli.OptionsBase.Run() in /home/runner/work/Libation/Libation/Source/LibationCli/Options/_OptionsBase.cs:line 15
```

**Comment by Mbucari** [comment]
Looks like libationcli is doing a check for updat every time it runs and your IP has been temporarily blocked by the GitHub API.

**Comment by wtanksleyjr** [comment]
True, which is interesting (note that I can still manually download the
dpkg and update, which I did). But the next exception (the one with the
JSON) kills the process, so nothing else can get done. Oh, and this
happened yesterday -- the day before I bought and it liberated a book, no
problem.

One more thing -- this is the CLI. I have it running automatically so I
don't have to think about liberating my new purchases. Speaking of which,
is there a command line to turn off the automatic update check? It doesn't
do me any good, since this is running in the background.

-Wm

**Comment by Mbucari** [comment]
> the next exception (the one with the JSON) kills the process.

The json exception is caused by the API exception. The crash is all due to the failing update check, so this is a bug.

> is there a command line to turn off the automatic update check?

Nope. And really the update check should not run automatically in the cli. This is also a bug.

**Comment by wtanksleyjr** [comment]
I just manually scanned all the json files, and found an extra "}" at the
end of AccountSettings.json. On removing it, I was able to run.

I wouldn't be surprised if the two weren't related of course, but I'm back
up and running again.

-Wm

**Comment by Mbucari** [comment]
@wtanksleyjr There's a complete overhaul of the cli incoming which includes this fix.
