### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by johnowens22** [rmcrackan/Libation#665]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by johnowens22** [comment]
Response status code does not indicate success: 404 (Not Found).

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authentication/LoginResultRunner.cs:line 228
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, Dictionary`2 inputs, String url) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authentication/LoginResultRunner.cs:line 46
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, Dictionary`2 inputs, SignInPage signInPage) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authentication/LoginResultRunner.cs:line 36
   at AudibleApi.Authentication.TwoFactorAuthenticationPage.SubmitAsync(String _2faCode) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Authentication/TwoFactorAuthenticationPage.cs:line 26
   at AudibleApi.EzApiCreator.loginEmailPasswordAsync(Locale locale, ILoginCallback responder, String email, String password) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.LoginCallback.cs:line 71
   at AudibleApi.EzApiCreator.choiceLoginAsync(Locale locale, ILoginChoiceEager loginChoiceEager) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.LoginChoiceEager.cs:line 50
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/EzApiCreator/EzApiCreator.LoginChoiceEager.cs:line 28
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AudibleUtilities\ApiExtended.cs:line 34
   at LibationWinForms.Login.WinformLoginChoiceEager.ApiExtendedFunc(Account account) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\Dialogs\Login\WinformLoginChoiceEager.cs:line 12
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 190
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\ApplicationServices\LibraryCommands.cs:line 120
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by johnowens22** [comment]
[_Log202207.log](https://github.com/rmcrackan/Libation/files/11998265/_Log202207.log)

**Comment by johnowens22** [comment]
[Log202307.log](https://github.com/rmcrackan/Libation/files/11998266/Log202307.log)

**Comment by rmcrackan** [comment]
Any luck with this issue?

**Comment by rmcrackan** [comment]
This ticket seems to have gone cold. If you're still having issues, reply here and I'll be glad to re-open it.
