### ISSUE TITLE
Error upon Library scan with 10.6.3.1

### ISSUE THREAD

**Issue by lobsterbake** [rmcrackan/Libation#685]
Greetings - I upgraded Libation to version 10.6.3.1 today and find that I receive an error upon trying to scan my library (e.g., via Import -> Scan Library of All Accounts). I'm on a Windows 10 Pro system. While I haven't encountered this problem previously, I can't say for sure whether it's related to the upgrade (I hadn't used Libation for a couple of weeks prior to upgrading).

Log file content pasted below.

I would appreciate any suggestions. Thank you!

Log file snippet: 

```
 {}2023-07-25 09:22:50.543 -04:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"Libation","Version":"10.6.3.1","ReleaseIdentifier":"WindowsClassic","OS":"Windows","InteropFunctionsType":"WindowsConfigApp.WinInterop","Mode":"Release","LogLevel_Verbose_Enabled":true,"LogLevel_Debug_Enabled":true,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":false,"LibationFiles":"C:\\Users\\all\\Libation","BooksDirectory":"\\\\?\\E:\\Documents\\audio.books","InProgress":"C:\\Users\\all\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDirectory":"\\\\?\\C:\\Users\\all\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDirectory":"\\\\?\\C:\\Users\\all\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
 {}2023-07-25 09:22:50.918 -04:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Libation.resources, Version=1.0.0.0, Culture=en-US, PublicKeyToken=null
 {}2023-07-25 09:22:51.034 -04:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Libation.resources, Version=1.0.0.0, Culture=en, PublicKeyToken=null
 {}2023-07-25 09:22:57.414 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":5102,"booksFullyBackedUp":2457,"booksDownloadedOnly":0,"booksNoProgress":2644,"booksError":0,"booksUnavailable":1}
 {}2023-07-25 09:22:57.625 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":479,"pdfsDownloaded":465,"pdfsNotDownloaded":14,"pdfsUnavailable":0}
 {}2023-07-25 09:23:02.109 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":5102,"booksFullyBackedUp":2457,"booksDownloadedOnly":0,"booksNoProgress":2644,"booksError":0,"booksUnavailable":1}
 {}2023-07-25 09:23:02.219 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":479,"pdfsDownloaded":465,"pdfsNotDownloaded":14,"pdfsUnavailable":0}
 {}2023-07-25 09:24:05.268 -04:00 [INF] (at FileManager.PersistentDictionary.writeFile(System.String, Newtonsoft.Json.Linq.JToken)) Config changed. {"propertyName":"AutoScan","newValue":"True"}
 {}2023-07-25 09:24:05.441 -04:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Error importing library
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 24
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 232
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
 {"ExceptionDetail":{"Type":"System.IO.InvalidDataException","HResult":-2146233087,"Message":"End of Central Directory record could not be found.","Source":"System.IO.Compression","TargetSite":"Void ReadEndOfCentralDirectory()"}}2023-07-25 09:24:05.785 -04:00 [ERR] (at LibationWinForms.Form1+<<Configure_ScanAuto>b__115_0>d.MoveNext()) Error invoking auto-scan
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 24
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 232
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
   at LibationWinForms.Form1.<Configure_ScanAuto>b__115_0(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanAuto.cs:line 39
 {"ExceptionDetail":{"Type":"System.IO.InvalidDataException","HResult":-2146233087,"Message":"End of Central Directory record could not be found.","Source":"System.IO.Compression","TargetSite":"Void ReadEndOfCentralDirectory()"}}2023-07-25 09:24:15.311 -04:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Error importing library
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 24
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 232
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
 {"ExceptionDetail":{"Type":"System.IO.InvalidDataException","HResult":-2146233087,"Message":"End of Central Directory record could not be found.","Source":"System.IO.Compression","TargetSite":"Void ReadEndOfCentralDirectory()"}}2023-07-25 09:24:15.541 -04:00 [ERR] (at LibationWinForms.MessageBoxLib.ShowAdminAlert(System.ComponentModel.ISynchronizeInvoke, System.String, System.String, System.Exception)) Alert admin error: {"text":"Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator","caption":"Error importing library"}
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 24
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 232
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77
 {"ExceptionDetail":{"Type":"System.IO.InvalidDataException","HResult":-2146233087,"Message":"End of Central Directory record could not be found.","Source":"System.IO.Compression","TargetSite":"Void ReadEndOfCentralDirectory()"}}2023-07-25 09:25:29.076 -04:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Error importing library
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 24
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 232
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
 {"ExceptionDetail":{"Type":"System.IO.InvalidDataException","HResult":-2146233087,"Message":"End of Central Directory record could not be found.","Source":"System.IO.Compression","TargetSite":"Void ReadEndOfCentralDirectory()"}}2023-07-25 09:25:30.163 -04:00 [ERR] (at LibationWinForms.MessageBoxLib.ShowAdminAlert(System.ComponentModel.ISynchronizeInvoke, System.String, System.String, System.Exception)) Alert admin error: {"text":"Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator","caption":"Error importing library"}
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 24
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 232
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77
 {"ExceptionDetail":{"Type":"System.IO.InvalidDataException","HResult":-2146233087,"Message":"End of Central Directory record could not be found.","Source":"System.IO.Compression","TargetSite":"Void ReadEndOfCentralDirectory()"}}2023-07-25 09:26:00.268 -04:00 [INF] (at FileManager.PersistentDictionary.writeFile(System.String, Newtonsoft.Json.Linq.JToken)) Config changed. {"propertyName":"AutoScan","newValue":"False"}
```

Edited by @rmcrackan so we can see the raw snippet. Github was making it look weird

**Comment by Mbucari** [comment]
Looks like you have enable the "debug" log level. Part of debug logging is saving the raw data from library scans in LibraryScans.zip (in your Libation settings folder). That file appears to be corrupted. Try finding and deleting LibraryScans.zip and/or changing your logging level to "information".

**Comment by lobsterbake** [comment]
Thank you so much for the rapid response! I renamed LibraryScans.zip to LibraryScans_OLD.zip and relaunched and all is working just fine.
