### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by falcon935** [rmcrackan/Libation#7]
2020-06-14 15:08:39.490 -05:00 [INF] (at LibationLauncher.Program.initLogging()) Begin Libation
2020-06-14 15:08:48.055 -05:00 [INF] (at InternalUtilities.AudibleApiExtensions+<GetAllLibraryItemsAsync>d__0.MoveNext()) Page 1: 199 results
2020-06-14 15:08:53.740 -05:00 [INF] (at InternalUtilities.AudibleApiExtensions+<GetAllLibraryItemsAsync>d__0.MoveNext()) Page 1: 199 results
2020-06-14 15:08:58.717 -05:00 [INF] (at InternalUtilities.AudibleApiExtensions+<GetAllLibraryItemsAsync>d__0.MoveNext()) Page 1: 199 results
2020-06-14 15:08:58.937 -05:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportLibraryAsync>d__0.MoveNext()) Error importing library
System.AggregateException: One or more errors occurred. (Collection contains Categories with wrong number of categories. Expecting 0, 1, or 2 categories per title (Parameter 'items'))
 ---> System.ArgumentException: Collection contains Categories with wrong number of categories. Expecting 0, 1, or 2 categories per title (Parameter 'items')
   --- End of inner exception stack trace ---
   at InternalUtilities.AudibleApiActions.getItemsAsync(ILoginCallback callback)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at InternalUtilities.AudibleApiActions.GetAllLibraryItemsAsync(ILoginCallback callback)
   at ApplicationServices.LibraryCommands.ImportLibraryAsync(ILoginCallback callback)

**Comment by rmcrackan** [comment]
Audible changed how they did categories which in turn broke my imports. Fixed in the latest version -- https://github.com/rmcrackan/Libation/releases
