### ISSUE TITLE
Linux on X11 - instant crash

### ISSUE THREAD

**Issue by nrbeaton** [rmcrackan/Libation#708]
Installing the latest version on Ubuntu 23.04 goes OK using the .deb file. Opening the app the first time, the dialog box opens asking if I'm a new or existing user. I click on "new user", and then it instantly crashes. Trying to open the app again, something small briefly flashes up and then disappears.

Same thing happens on Arch Linux using the AUR version.

Oddly I tried the app using a Live USB version of Ubuntu and it worked then. But with Ubuntu actually installed on the machine the above crash occurs.

Log file is:

```
8/10/2023 3:08:04PM - Libation Crash
 OS                    Linux
 Version               10.6.5.1
 ReleaseIdentifier     LinuxAvalonia
 InteropFunctionsType  LinuxConfigApp.LinuxInterop
 LibationFiles         /home/nrb/Libation
 Books Folder          /home/nrb/Libation/Books
 === EXCEPTION ===
 System.NullReferenceException: Object reference not set to an instance of an object.
   at LibationAvalonia.MessageBox.CreateMessageBox(Window owner, String message, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, Boolean saveAndRestorePosition) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/MessageBox.cs:line 180
   at LibationAvalonia.MessageBox.<>c__DisplayClass13_0.<ShowCoreAsync>b__0() in /home/runner/work/Libation/Libation/Source/LibationAvalonia/MessageBox.cs:line 157
   at Avalonia.Threading.DispatcherOperation`1.InvokeCore()
--- End of stack trace from previous location ---
   at LibationAvalonia.MessageBox.ShowCoreAsync(Window owner, String message, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, Boolean saveAndRestorePosition) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/MessageBox.cs:line 157
   at LibationAvalonia.Views.MainWindow.MainWindow_Loaded(Object sender, EventArgs e) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/Views/MainWindow.axaml.cs:line 42
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at LibationAvalonia.Program.Main(String[] args) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/Program.cs:line 67
```

EDIT: The lines about X11 suggested it might be an issue with X11, so I switched to Wayland, and it works! So the problem seems to lie with X11. (I use X11 because I have a hybrid graphics laptop and on Wayland I can't run everything on the dedicated Nvidia GPU.)

**Comment by nrbeaton** [comment]
I'll also add that on Wayland the app does not seem to respect GNOME's scaling by default. There's probably an environment variable which will fix that.

**Comment by Mbucari** [comment]
Thanks for the report. So far I've been unable to replicate this error. I tried Ubuntu 22 on with Wayland disabled and I did not receive any errors. I only use Linux through VMs, and maybe I got this error if I was running on bare metal. I have most of a circa 2016 PC not doing anything, so maybe I'll try turning it into a Linux box.

That said, even though I can't reproduce this error I think I can find a way to work around it. The workaround might cause message boxes to look a little screwy, but there should be no other side effects.

**Comment by nrbeaton** [comment]
For some reason once I got it working on Wayland and then switched back to X11, it continued working! Very odd. (This was before the v11 update.)

It continues to work on X11 after the v11 update. Though the initial dialog box where you tell it where to find the pre-existing library seems a bit broken -- I can select the directory but the "save" button stays grayed out. Just closing the dialog box seems to work.

Thanks for your work!

**Comment by Mbucari** [comment]
Thanks for the update! I thought I had fixed that grayed out button. Oh well, I'll get it next time.
