### ISSUE TITLE
2fa field does not seem to be working

### ISSUE THREAD

**Issue by yupinacup** [rmcrackan/Libation#71]
When entering a 2fa code, I get the following error in my logs. Unsure if it is a hard coded file path or an issue with the 2fa text field.

```
System.ArgumentException: 2FA code may not be blank (Parameter '_2faCode')
   at AudibleApi.Authentication.TwoFactorAuthenticationPage.SubmitAsync(String _2faCode) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\TwoFactorAuthenticationPage.cs:line 20
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 86
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 23
```

**Comment by rmcrackan** [comment]
Thank you for including that part from the log file.

The log messages mentioning with Dropbox is fine. That's just where my code lives on my computer. Leaving it the error logs in helps me debug stuff like this

The error is interesting though. "2FA code may not be blank" is only supposed to be possible if you were shown the 2 factor authentication window and clicked "Submit" without typing the code that was texted/emailed to you. Did you type in that number before clicking the Submit button? Please try again and make sure the number is typed correctly in the tiny "2FA Code" window before hitting submit. If you're still getting this error, can you attach the whole log file? You can drag/drop it into github when you replay.

Thank you for your patience with bugs like this. This is the 2nd error I've seen lately where something inexplicable has happened. I'm starting to wonder if something is getting corrupted when I compile my code.

**Comment by yupinacup** [comment]
Thanks for the clarification on the dropbox thing. I pasted the code in and hit submit. I don't know if that is a corner case, maybe you were expecting keystrokes? I can get the log file in a bit, I stepped away from my computer at the moment

**Comment by rmcrackan** [comment]
Thanks! Please reproduce this and send me the new full log just to be safe. I just tried every combination I can think of and I cannot get this to give the blank error when something exists in the text box. I tried copy+pasting, clicking the button with a mouse, and submitting the form by pressing the enter key with the text box in focus. I'll release a new version of Libation soon-ish with additional logging around places like this.

**Comment by rmcrackan** [comment]
Try [v5.3.8](https://github.com/rmcrackan/Libation/releases/tag/v5.3.8). It has better logging around these log-in steps which could help us.

**Comment by yupinacup** [comment]
[_Log202107.log](https://github.com/rmcrackan/Libation/files/6882230/_Log202107.log)

**Comment by yupinacup** [comment]
Using v5.3.9

**Comment by rmcrackan** [comment]
> "Version":"5.3.6.2"

This doesn't appear to be a log from v5.3.9. Either you ran a different version of Libation or you copied from an older log file. It's probably my fault -- I changed some defaults this month. Do you have log files in the folder C:\Users\{login name}\Libation\ ?

**Comment by yupinacup** [comment]
```
2021-07-29 03:12:06.387 -06:00 [INF] (at LibationLauncher.Program.logStartupState(FileManager.Configuration)) 
2021-07-29 03:12:06.420 -06:00 [INF] (at LibationLauncher.Program.logStartupState(FileManager.Configuration)) Begin Libation. {"Version":"5.3.9.2","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"LibationFiles":"C:\\Users\\user\\Libation","BooksDirectory":"C:\\Users\\user\\Documents\\Audiobooks","InProgress":"C:\\Users\\user\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDir":"C:\\Users\\user\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDir":"C:\\Users\\user\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2021-07-29 03:12:13.690 -06:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2021-07-29 03:12:13.697 -06:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2021-07-29 03:12:20.857 -06:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=t[...]y@g[...]l.c[...]m|AccountName=t[...]y@g[...]l.c[...]s|Locale=us","LocaleName":"us"}
2021-07-29 03:12:37.491 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Send request {"method":"POST","uri":"https://www.amazon.com/ap/signin","absoluteUri":"[== uri]"}
2021-07-29 03:12:37.885 -06:00 [INF] (at AudibleApi.EzApiCreator+<loginAsync>d__1.MoveNext()) Login result: "AudibleApi.Authentication.CaptchaPage"
2021-07-29 03:12:50.111 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Send request {"method":"POST","uri":"https://www.amazon.com/ap/signin","absoluteUri":"[== uri]"}
2021-07-29 03:12:50.438 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Redirecting to https://www.amazon.com/ap/mfa/new-otp?ie=UTF8&arb=e143af8c-4787-45e1-8877-59d44d1f272d&mfa.arb.value=e143af8c-4787-45e1-8877-59d44d1f272d&mfa.arb.key=arb&codeHasBeenSent=false
2021-07-29 03:12:50.448 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Send request {"method":"GET","uri":"https://www.amazon.com/ap/mfa/new-otp?ie=UTF8&arb=e143af8c-4787-45e1-8877-59d44d1f272d&mfa.arb.value=e143af8c-4787-45e1-8877-59d44d1f272d&mfa.arb.key=arb&codeHasBeenSent=false","absoluteUri":"[== uri]"}
2021-07-29 03:12:50.643 -06:00 [INF] (at AudibleApi.Authentication.MfaSelectionPage..ctor(AudibleApi.Authentication.Authenticate, System.String)) Page info {"Count":3,"title":"Two-Step Verification"}
2021-07-29 03:12:50.651 -06:00 [INF] (at AudibleApi.EzApiCreator+<loginAsync>d__1.MoveNext()) Login result: "AudibleApi.Authentication.MfaSelectionPage"
2021-07-29 03:12:50.661 -06:00 [INF] (at LibationWinForms.Dialogs.Login.MfaDialog..ctor(AudibleApi.MfaConfig)) {"paramButtonCount":3,"visibleRadioButtonCount":0}
2021-07-29 03:12:53.937 -06:00 [INF] (at LibationWinForms.Dialogs.Login.MfaDialog.submitBtn_Click(System.Object, System.EventArgs)) RadioButton states: {"rb1_visible":true,"rb1_checked":true,"r21_visible":true,"r21_checked":false,"rb3_visible":true,"rb3_checked":false}
2021-07-29 03:12:53.948 -06:00 [INF] (at LibationWinForms.Dialogs.Login.MfaDialog.submitBtn_Click(System.Object, System.EventArgs)) Selected: {"isSelected":true,"name":"otpDeviceContext","value":"Da9iClWH4WU6ut9ncWNP/mlvZBLO37dSH9LNzCYJVM4=, TOTP"}
2021-07-29 03:12:53.962 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Send request {"method":"POST","uri":"https://www.amazon.com/ap/mfa","absoluteUri":"[== uri]"}
2021-07-29 03:12:54.204 -06:00 [INF] (at AudibleApi.EzApiCreator+<loginAsync>d__1.MoveNext()) Login result: "AudibleApi.Authentication.TwoFactorAuthenticationPage"
2021-07-29 03:13:07.136 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Send request {"method":"POST","uri":"https://www.amazon.com/ap/signin","absoluteUri":"[== uri]"}
2021-07-29 03:13:07.284 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Redirecting to https://www.amazon.com/ap/mfa?ie=UTF8&arb=c16a3ceb-2e42-41d2-a4e3-df754a65fdb6&mfa.arb.value=c16a3ceb-2e42-41d2-a4e3-df754a65fdb6&mfa.arb.key=arb
2021-07-29 03:13:07.287 -06:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__6.MoveNext()) Send request {"method":"GET","uri":"https://www.amazon.com/ap/mfa?ie=UTF8&arb=c16a3ceb-2e42-41d2-a4e3-df754a65fdb6&mfa.arb.value=c16a3ceb-2e42-41d2-a4e3-df754a65fdb6&mfa.arb.key=arb","absoluteUri":"[== uri]"}
2021-07-29 03:13:07.496 -06:00 [INF] (at AudibleApi.EzApiCreator+<loginAsync>d__1.MoveNext()) Login result: "AudibleApi.Authentication.TwoFactorAuthenticationPage"
2021-07-29 03:13:10.381 -06:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.ArgumentNullException: Value cannot be null. (Parameter '_2faCode')
   at AudibleApi.Authentication.TwoFactorAuthenticationPage.SubmitAsync(String _2faCode) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\TwoFactorAuthenticationPage.cs:line 17
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 86
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 23
2021-07-29 03:13:10.405 -06:00 [ERR] (at LibationWinForms.MessageBoxAlertAdmin.Show(System.String, System.String, System.Exception)) Alert admin error: {"text":"Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator","caption":"Error importing library"}
System.ArgumentNullException: Value cannot be null. (Parameter '_2faCode')
   at AudibleApi.Authentication.TwoFactorAuthenticationPage.SubmitAsync(String _2faCode) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\TwoFactorAuthenticationPage.cs:line 17
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 86
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 23
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34
```

**Comment by rmcrackan** [comment]
That bug is persistent and I have no idea how it's only happening for you. Let's try this. Please use the latest [v5.4.4](https://github.com/rmcrackan/Libation/releases/latest) and change it to debug:

> Libation > Settings > Settings...
> Logging level: Debug

**Comment by familiarrStrangerr** [comment]
[Log202108.log](https://github.com/rmcrackan/Libation/files/6914661/Log202108.log)

Sharing the debug log

**Comment by rmcrackan** [comment]
Does this fix it? https://github.com/rmcrackan/Libation/releases/tag/v5.4.9

**Comment by Jamyn** [comment]
5.4.9 didn't fix MFA login for me. I'm not prompted at all, it just fails.

[Log202108.log](https://github.com/rmcrackan/Libation/files/6933909/Log202108.log)

**Comment by Jamyn** [comment]
5.4.9 didn't fix my MFA issue. Note that I redacted the account name on line 7 from the attached log since it was included in full.

`2021-08-04 14:22:16.566 -05:00 [DBG] (at AudibleApi.EzApiCreator+<GetApiAsync>d__0.MoveNext()) GetApiAsync. {"localeName":"us","jsonPath":"$.Accounts[?(@.AccountId == '**redacted@account.com**' && @.IdentityTokens.LocaleName == 'us')].IdentityTokens","debugEx_Message":"Cookies may not be empty (Parameter 'cookies')","debugEx_StackTrace":"   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies) in C:\\Users\\mbuca\\source\\repos\\audible api\\AudibleApi\\AudibleApi\\Authorization\\Authorize.cs:line 67\r\n   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync() in C:\\Users\\mbuca\\source\\repos\\audible api\\AudibleApi\\AudibleApi\\Authorization\\IdentityMaintainer.cs:line 103\r\n   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime) in C:\\Users\\mbuca\\source\\repos\\audible api\\AudibleApi\\AudibleApi\\Authorization\\IdentityMaintainer.cs:line 38\r\n   at AudibleApi.Authorization.I
`

[Log202108.log](https://github.com/rmcrackan/Libation/files/6933952/Log202108.log)

**Comment by familiarrStrangerr** [comment]
This issue is persistent in these two stores: Australia and Japan. Others seems to be working fine.

**Comment by yupinacup** [comment]
Sorry, I have been very busy. I will follow up on this soon

**Comment by yupinacup** [comment]
5.4.9 works! Thanks for the effort @rmcrackan!!
