### ISSUE TITLE
Unauthenticated API call from AudibleAPI

### ISSUE THREAD

**Issue by ajstack** [rmcrackan/Libation#713]
**Describe the bug**
My library isn't being imported.

When I initially added my account and signed in, it did NOT prompt me with a CAPTCHA. I deleted the account (clicked save) and then readded the account and when scanning it DID  prompt me with a CAPTCHA. The error happens regardless

**To Reproduce**

1. Settings > Accounts... > Add account 
- Add email + Select 'us' as 'Locale'
- Click 'Save'
2. Allow scan
- Scan runs automatically
- Sign in to Audible account
- - No CAPTCHA prompt present
3. *See error*
4. Import > Uncheck 'Auto Scan Library'
5. Settings > Accounts... > Delete existing account
- Click Save
- Re-add account
6. Import > 'Scan Library'
- Allow scan
- Sign in to Audible account
- - CAPTCHA prompt present
7. *See error*

**Expected behavior**
Library to be scanned successfully

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/36316119/fe18973e-d4d2-4dd0-9b9f-2dd3b550439a)

Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 53
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 275
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 257
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 259
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 126
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201
**Platform**

Windows 11

**Log Files**
[_Log202308.zip](https://github.com/rmcrackan/Libation/files/12362607/_Log202308.zip)

**Comment by Mbucari** [comment]
Hi @ajstack thanks for the report. Unfortunately this is a networking error. They _usually_ resolve themselves in time, but it could be a problem with your home internet as well.

**Comment by ajstack** [comment]
I tried again and it worked, thank you!!
