### ISSUE TITLE
After updating from 10.0.2, ERROR: Access to the path is denied.

### ISSUE THREAD

**Issue by yupccscott** [rmcrackan/Libation#722]
**Describe the bug**
Recently updated from Libation.10.0.2-linux-chardonnay-amd64.deb to Libation.11.0.1-linux-chardonnay-amd64.deb and now when liberating the transcoding step fails due to a permission error. I believe download functions fine as the source file is there and decrypted.
Different books bring the same result.
The directory is a mounted SMB/CIFS directory and is accessible otherwise - including it seems during the copy from temp location.

**To Reproduce**
1. Open Libation
2. Click on an unbacked up book
3. Wait for download to complete and decryption/transcoding to being

2023-08-24 1:05 p.m.	Download & Decrypt Step, Begin: [B09FR2J8MJ] Of Blood and Fire: The Bound and the Broken, Book 1
2023-08-24 1:05 p.m.	Download & Decrypt Step, Completed: [B09FR2J8MJ] Of Blood and Fire: The Bound and the Broken, Book 1
2023-08-24 1:05 p.m.	Download & Decrypt
2023-08-24 1:05 p.m.	ERROR. All books have not been processed. Most recent book: processing failed
2023-08-24 1:05 p.m.	ERROR: Access to the path '/mnt/media/Audiobooks/Audiobookshelf/Ryan Cahill/Bound and the Broken/1 - Of Blood and Fire/Of Blood and Fire The Bound and the Broken Book 1 [B09FR2J8MJ].m4b' is denied.

**Expected behavior**
It previously completed without issue. There were no configuration nor path changes that I can think of outside of Libation

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/55902063/82de5403-5127-4448-9455-256952eb8741)
![image](https://github.com/rmcrackan/Libation/assets/55902063/141987e5-91ea-43e6-98e2-bf71e021f6a3)

**Platform**
Linux. PopOS 22.04

**Log Files**
Verbose log attached. The account obfuscation is appreciated
[Log202308.zip](https://github.com/rmcrackan/Libation/files/12433064/Log202308.zip)

**Comment by Mbucari** [comment]
Does downgrading back to 10.0.2 fix it?

**Comment by yupccscott** [comment]
Downgrade did work previously but it appears there was a database schema change so after going back from 11.x now causes an error on start when rolled back to 10.0.2.
A fresh database file gets around it but it will have lost download status for all books (very reasonable work around).

Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: b.CategoryId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at ApplicationServices.DbContexts.GetLibrary_Flat_NoTracking(Boolean includeParents) in /home/runner/work/Libation/Libation/Source/ApplicationServices/DbContexts.cs:line 18
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LibationAvalonia.App.ShowMainWindow(IClassicDesktopStyleApplicationLifetime desktop) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/App.axaml.cs:line 220
   at LibationAvalonia.App.OnFrameworkInitializationCompleted() in /home/runner/work/Libation/Libation/Source/LibationAvalonia/App.axaml.cs:line 71
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 162
   at LibationAvalonia.Program.Main(String[] args) in /home/runner/work/Libation/Libation/Source/LibationAvalonia/Program.cs:line 64
Aborted (core dumped)

**Comment by Mbucari** [comment]
Cool, thanks.

Can you tell me about your media drive? What kind of drive is it? What file system is it?

**Comment by yupccscott** [comment]
You bet.

It's a Synology NAS mounted over the network via CIFS to the computer that's running Libation.

from fndmount:
TARGET     SOURCE        FSTYPE
/mnt/media //nas00/Media cifs

the mount options in fstab, the user used to mount has full permissions on the NAS side of things
iocharset=utf8,vers=3.0,file_mode=0777,dir_mode=0777

On the backend its Btrfs

LMK if you want other details/specifics. Happy to provide.

**Comment by Mbucari** [comment]
@yupccscott Thanks again. It so happens that I also have a synology server, but I was unable to reproduce the error on Ubuntu 22 upgrading from 10.0.2 to 11.0.1. It just works.

Maybe try unmounting and remounting?

Here's the connection string I used:

```Console
sudo umount /mnt/media
sudo mount -t cifs -o rw,vers=2.0,username=mbucari,file_mode=0777,dir_mode=0777,uid=$(id -u),gid=$(id -g),forceuid,forcegid //192.168.0.112/Public /mnt/media
```

**Comment by Mbucari** [comment]
@yupccscott OK, I was able to reproduce the error! I changed my server settings to permit SMB 3 and used this connection string:

```
sudo mount -t cifs -o iocharset=utf8,vers=3.0,file_mode=0777,dir_mode=0777,username=mbucari //192.168.0.112/Public /mnt/media
```

10.0.4 worked, but I got a write access error after upgrading to 11.0.1.

I unmounted then remounted with the following connection string, then tested it again. Libation was still able to access the mount point after upgrading.

```Console
sudo mount -t cifs -o iocharset=utf8,vers=3.0,file_mode=0777,dir_mode=0777,uid=$(id -u),gid=$(id -g),forceuid,forcegid,username=mbucari //192.168.0.112/Public /mnt/media
```

**Comment by yupccscott** [comment]
At least we know it's something specific to my config.

pretty sure I've tested unmounting/remounting before but I see some differences in our mount options.

I'll do some trial and error with it over the next couple days

**Comment by yupccscott** [comment]
Confirmed the uid/gid additions made all the difference with SMB3 and 11.x

Much appreciated for the assist.
