### ISSUE TITLE
Unrecoverable error. Unable to read settings from Settings file

### ISSUE THREAD

**Issue by dr-fluff** [rmcrackan/Libation#727]
**Describe the bug**
Unable to start libaton after update

**To Reproduce**
Install latest version(11.0.1) and start aplication.

**Expected behavior**
Starting the app

**Platform**
 Windows 10

**Log Files**
Unrecoverable error. Unable to read settings from Settings file

   at FileManager.PersistentDictionary.readFile() in D:\a\Libation\Libation\Source\FileManager\PersistentDictionary.cs:line 281
   at FileManager.PersistentDictionary.GetString(String propertyName, String defaultValue) in D:\a\Libation\Libation\Source\FileManager\PersistentDictionary.cs:line 43
   at LibationFileManager.Configuration.SettingsFileIsValid(String settingsFile) in D:\a\Libation\Libation\Source\LibationFileManager\Configuration.cs:line 21
   at LibationWinForms.Program.RunInstaller(Configuration config) in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 98

**Comment by Mbucari** [comment]
Your settings.json file got corrupted. Try deleting it then restarting Libation. You'll be asked if you're a new or returning user; click "returning". You'll then be asked to select the Libation settings folder.
