### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by Blanket-Why** [rmcrackan/Libation#731]
**Describe the bug**
Error importing library

**To Reproduce**
Error happened after first library synch. Succesful log in then pressed import it scanned for a couple of seconds then error message appeared.

**Platform**

Windows 10

**Log**

Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 53
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201

**Comment by Mbucari** [comment]
@Blanket-Why please attach your entire log.zip file, not just an excerpt that you believe is sufficient.

**Comment by mesquiteTX** [comment]
> @Blanket-Why please attach your entire log.zip file, not just an excerpt that you believe is sufficient.

The copied text by OP is the same pop-up I get as well. Here is the Log File from my attempt.

[Log202309.zip](https://github.com/rmcrackan/Libation/files/12506743/Log202309.zip)

**Comment by Mbucari** [comment]
@mesquiteTX this is a network error. Libation is trying to connect to audible servers but the request is timing out

`{\"http_error\":\"The request failed due to timeout.\"}`

This should resolve itself in a day or two.

**Comment by mesquiteTX** [comment]
> 

Interesting, I’d attempted a download and decryption of another file in the same time frame but only got the error after the update from .2 to .3. Thanks for the response and I'll keep trying. Is there any way to "force" it to keep trying?

**Comment by Mbucari** [comment]
> @Mbucari Interesting, I’d attempted a download and decryption of another file in the same time frame but only got the error after the update from .2 to .3. Thanks for the response and I'll keep an eye on things. Is there any way to "force" it to keep trying, or is it just a "wait and see" type of situation?

I'm 99% sure it has nothing to do with the different libation version, but if you want to run the experiment try downgrading to 11.0.2 and trying again.

**Comment by mesquiteTX** [comment]
@Mbucari I must be brain dead, how would I go back a version? :/

**Comment by Mbucari** [comment]
@mesquiteTX there's no in-app way to do it, but you can download any prior release [from the release page](https://github.com/rmcrackan/Libation/releases) and then extract it to you libation program files folder.
