### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by bgodfray** [rmcrackan/Libation#735]
Error message 

Object reference not set to an instance of an object.

   at DataLayer.Book..ctor(AudibleProductId audibleProductId, String title, String description, Int32 lengthInMinutes, ContentType contentType, IEnumerable`1 authors, IEnumerable`1 narrators, Category category, String localeName) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DataLayer\EfClasses\Book.cs:line 109
   at DtoImporterService.BookImporter.createNewBook(ImportItem importItem)
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\BookImporter.cs:line 74
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\BookImporter.cs:line 30
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.ImporterBase`1.Import(T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\ImporterBase.cs:line 21
   at DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\LibraryBookImporter.cs:line 17
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.ImporterBase`1.Import(T param) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\DtoImporterService\ImporterBase.cs:line 21
   at ApplicationServices.LibraryCommands.<>c__DisplayClass5_0.<importIntoDbAsync>b__1() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 174
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 174
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 95
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 35

**Platform**
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]
Windows 10 

**Log Files**
[Log202309.log](https://github.com/rmcrackan/Libation/files/12553737/Log202309.log)
[_Log202309.log](https://github.com/rmcrackan/Libation/files/12553738/_Log202309.log)

**Comment by Mbucari** [comment]
I have a hunch this would be fixed by upgrading Libation. Please do that and let us know if it's fixed.

**Comment by bgodfray** [comment]
yes thanks that did work, sorry I thought I was on the latest version
