### ISSUE TITLE
Account validation fail on fresh reinstall

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#77]
I ripped everything out except the books folder, including %tmp% and my Libation user dir, as well as all the files in the install dir. Unpacked the old files. Opened Libation, chose "new user", placed all of the folders in the same place as before.

Added both of my Audible accounts. Ran import on my smaller account only. Typed in two verification images, then it asked for email verification. Went to email, waited, followed the link, and approved. Came back and clicked on "Approved" button.

```
Value cannot be null. (Parameter 'url')

   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 19
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 91
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 70
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 24
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34
```

**Comment by wtanksleyjr** [comment]
[_Log202107.log](https://github.com/rmcrackan/Libation/files/6902853/_Log202107.log)

**Comment by wtanksleyjr** [comment]
Hm, so this may be very bad, I can't get any of my accounts to progress -- my other account said it was sending me an email, but nothing ever happened.

**Comment by wtanksleyjr** [comment]
Oh, wait -- I reran the original account, and it worked without any further problems.

**Comment by rmcrackan** [comment]
You lost me. Is this still an issue?

**Comment by wtanksleyjr** [comment]
Yes, still a problem: specifically, clicking "Approved" crashes every time. The only part that isn't a problem is that the approval actually does work -- once you crash-close and reopen the app, and reenter your password, Amazon's fine with you, no need to email approval.

**Comment by rmcrackan** [comment]
Uggg. Of course it's Approved again. Can you drag/drop the offending log file?

**Comment by rmcrackan** [comment]
Actually: better. Are you able to repro with logging set to Debug?

**Comment by rmcrackan** [comment]
Better still would be Verbose mode so we can get the pages’ output

**Comment by rmcrackan** [comment]
Does this fix it? https://github.com/rmcrackan/Libation/releases/tag/v5.4.9

**Comment by wtanksleyjr** [comment]
Sorry for the delay, I'm still waiting my turn on the Windows machine ;) .

-Wm

**Comment by wtanksleyjr** [comment]
I wasn't able to make it angry enough at me to demand authorization. I must have made some unique typos in the authentication glyphs.

I'd recommend just closing this, we'll try again under better conditions if it ever happens again.
