### ISSUE TITLE
Not sure if I did this right

### ISSUE THREAD

**Issue by cschuerg2** [rmcrackan/Libation#785]
Could not deserialize json: 

   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Form1.refreshImportMenu(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by rmcrackan** [comment]
Sorry about this!

That feels like a corrupted file. Go to the same folder where your logs are. Try renaming `AccountsSettings.json` to something else, re-add your account, scan, and log in again. This should hopefully fix it.
