### ISSUE TITLE
New or different?

### ISSUE THREAD

**Issue by cschuerg2** [rmcrackan/Libation#786]
Could not deserialize json: 

   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Form1.refreshImportMenu(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by rmcrackan** [comment]
Sorry about this! To me this sounds like a corrupted file.

Try this: rename AccountsSettings.json , restart Libation, under Settings > Accounts re-add your account(s), do a scan, log in. This should fix your issue.
