### ISSUE TITLE
PDF download not working

### ISSUE THREAD

**Issue by anesone** [rmcrackan/Libation#8]
When I try to do the PDF only download, I get this error:
6/19/2020 5:07:54 PM Begin: [B00K583BC6] Discovering Your Roots
6/19/2020 5:07:58 PM - Y:\Libation\Program files\BK_TCCO_000377.pdf
6/19/2020 5:08:08 PM Completed: [B00K583BC6] Discovering Your Roots

6/19/2020 5:08:08 PM ERROR. All books have not been processed. Most recent valid book: processing failed
6/19/2020 5:08:08 PM Downloaded PDF cannot be found
6/19/2020 5:08:08 PM DONE

Any ideas of what I should do?

**Comment by rmcrackan** [comment]
That's no good. I can't reproduce the issue on my computer. Can you post
the contents of your log file?

**Comment by anesone** [comment]
Sorry, I never got a notification that you responded.
Here is what the log says:

2020-09-18 16:47:34.377 -05:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.0.6.3","LibationFiles":"C:\\Libation\\LibationFiles_v4.0.6\\LibationFiles","BooksDirectory":"C:\\Libation\\LibationFiles_v4.0.6\\LibationFiles","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\aneso\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"C:\\Libation\\LibationFiles_v4.0.6\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\aneso\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-09-18 16:47:37.473 -05:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":999,"pending":999,"statusStripText":"BACKUPS: No progress: 999  Encrypted: 0  Fully backed up: 0","menuItemText":"999 remaining"}
2020-09-18 16:47:37.549 -05:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":50,"statusStripText":"|  PDFs: NOT d/l'ed: 50  Downloaded: 0","menuItemText":"50 remaining"}
2020-09-18 16:47:38.028 -05:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":999,"pending":999,"statusStripText":"BACKUPS: No progress: 999  Encrypted: 0  Fully backed up: 0","menuItemText":"999 remaining"}
2020-09-18 16:47:38.039 -05:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":50,"statusStripText":"|  PDFs: NOT d/l'ed: 50  Downloaded: 0","menuItemText":"50 remaining"}
2020-09-18 16:47:47.309 -05:00 [INF] (at FileLiberator.IProcessableExt+<processBookAsync>d__2.MoveNext()) Begin processBookAsync {"Title":"Discovering Your Roots","AudibleProductId":"B00K583BC6","Locale":"us","Account":"anesone@xxxxxxxxx.com"}
2020-09-18 16:47:47.319 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: Begin: [B00K583BC6] Discovering Your Roots
2020-09-18 16:47:47.945 -05:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":999,"pending":999,"statusStripText":"BACKUPS: No progress: 999  Encrypted: 0  Fully backed up: 0","menuItemText":"999 remaining"}
2020-09-18 16:47:47.982 -05:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":50,"statusStripText":"|  PDFs: NOT d/l'ed: 50  Downloaded: 0","menuItemText":"50 remaining"}
2020-09-18 16:47:47.993 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: Completed: [B00K583BC6] Discovering Your Roots

2020-09-18 16:47:48.005 -05:00 [ERR] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendError(System.Exception)) Automated backup: error
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Dinah.Core.Net.Http.SystemNetHttpExtensions.downloadAsync(HttpResponseMessage response, String destinationFilePath, IProgress`1 progress) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Dinah.Core\Dinah.Core\_Net\_Http\SystemNetHttpExtensions.cs:line 144
   at Dinah.Core.Net.Http.SystemNetHttpExtensions.DownloadFileAsync(HttpClient client, String downloadUrl, String destinationFilePath, IProgress`1 progress) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Dinah.Core\Dinah.Core\_Net\_Http\SystemNetHttpExtensions.cs:line 124
   at FileLiberator.DownloadableBase.PerformDownloadAsync(String proposedDownloadFilePath, Func`2 func) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\UNTESTED\DownloadableBase.cs:line 50
   at FileLiberator.DownloadPdf.downloadPdfAsync(LibraryBook libraryBook, String proposedDownloadFilePath) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\UNTESTED\DownloadPdf.cs:line 47
   at FileLiberator.DownloadPdf.ProcessItemAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\UNTESTED\DownloadPdf.cs:line 23
   at FileLiberator.DownloadableBase.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\UNTESTED\DownloadableBase.cs:line 33
   at FileLiberator.IProcessableExt.processBookAsync(IProcessable processable, LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\UNTESTED\IProcessableExt.cs:line 58
   at FileLiberator.IProcessableExt.ProcessFirstValidAsync(IProcessable processable) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\UNTESTED\IProcessableExt.cs:line 26
   at LibationWinForms.BookLiberation.ProcessorAutomationController.runBackupLoopAsync(IProcessable processable, AutomatedBackupsForm automatedBackupsForm) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\UNTESTED\BookLiberation\ProcessorAutomationController.cs:line 290
2020-09-18 16:47:48.057 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: DONE

**Comment by mkb79** [comment]
@rmcrackan

I had problems downloading pdf with my python app too. They have changed something. You can’t download pdf with given `pdf_url` anymore. They gives you a 403 error. 

I have found a workaround. You can take a look here https://github.com/mkb79/audible-cli/commit/7b96dd0ae70d13e16ba7816c0fd973500bef8182

**Comment by rmcrackan** [comment]
@mkb79
 
How do you avoid getting redirected to the login page? When I use that url, it's just a login redirect. I tried signing the headers as with api calls and by including cookies but it still 302s to the login

**Comment by mkb79** [comment]
I‘m using sign request auth method when I make the `head` request to `https://www.audible.{tld}/companion-file/{asin}`. 

Maybe the device cert you are retrieving by registering a device is limited to the tld for your registration endpoint. I know, that the website cookies are limited to a specific tld.

Example:
My registration endpoint looks like this `https://api.amazon.{tld}/auth/register`. So the endpoint depends on the selected marketplace (locale code)! In my case this is `de`. The website cookies are valid only for `amazon.de` and `audible.de`. When I try to access `audible.com` the website cookies are invalid and I have to authenticate (login) again.

**Comment by mkb79** [comment]
You can exchange your website cookies to a specific tld with this request:

method: POST

endpoint: https://www.amazon.{tld}/ap/exchangetoken

body = {
    "app_name": "Audible",
    "app_version": "3.26.1",
    "source_token": refresh_token,
    "requested_token_type": "auth_cookies",
    "source_token_type": "refresh_token",
    "domain": f".amazon.{cookies_tld}"
}

**Comment by rmcrackan** [comment]
@mkb79

> I‘m using sign request auth method when I make the `head` request to `https://www.audible.{tld}/companion-file/{asin}`

Excuse my python ignorance, but I don't see where.

get_pdf() calls get_pdf_url() which makes a head() call. To me it looks like head() runs with no special headers, no cookies, and no auth signing

> Maybe the device cert you are retrieving by registering a device is limited to the tld for your registration endpoint. I know, that the website cookies are limited to a specific tld

Mine is all .com so it's easy

Unrelated, you might have a copy-paste bug. async def main(loop, auth, **params) ~ln 384

    get_pdf = params.get("pdf")
    get_cover = params.get("pdf") <--- is this correct?

**Comment by mkb79** [comment]
`head` request means, that the request only get the headers of the response without the content. Here are some informations about a [head request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD). 

The `get_pdf_url` method makes a HEAD request to `https://www.audible.{tld}/companion-file/{asin}`. This request is redirected to the correct pdf url. Then I get the url to the redirected site. 

Thanks for your hint with `params.get("pdf")`. This is really a copy and paste bug!

**Comment by mkb79** [comment]
Can you download PDFs with url given by API pdf_url with .com tld?

**Comment by rmcrackan** [comment]
> Can you download PDFs with url given by API pdf_url with .com tld?

I cannot get any pdf download code to work. When I try, instead of giving me the download url, it redirects to the login screen. Signing the request (headers: x-adp-token , x-adp-alg , x-adp-signature) does not resolve the issue.

**Comment by mkb79** [comment]
And when make an api request to /1.0/library with response_groups=pdf_url? Does the delivered pdf_url work for you? In germany the provided pdf_url gives an error code when you try to download the pdf.

**Comment by rmcrackan** [comment]
> And when make an api request to /1.0/library with response_groups=pdf_url? Does the delivered pdf_url work for you? In germany the provided pdf_url gives an error code when you try to download the pdf.

No. This is broken in the US also. What does your HEAD request contain? Also, is there a better way for us to chat than this board?

**Comment by mkb79** [comment]
You can write to me via mail at mkb79@hackitall.de. Then we can communicate via mail or discord.

**Comment by rmcrackan** [comment]
I wasted days on this and the issue turns out that with the client I'm using, if you specify a base url then requests with relative url acts differently than absolute url. I changed my request from absolute url to relative and now it works. So anti climactic. Thank you for all your help. I'll send you my contact via email.

**Comment by rmcrackan** [comment]
@anesone 

Fixed in v4.0.7

https://github.com/rmcrackan/Libation/releases/latest

**Comment by anesone** [comment]
@rmcrackan 
Still no joy.  Here is my log dump:

2020-09-22 09:25:57.875 -05:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.0.7.4","LibationFiles":"C:\\Users\\aneso\\Downloads\\Libation_v4.0.7\\Libation 4.0.7\\LibationFiles","BooksDirectory":"C:\\Users\\aneso\\Downloads\\Libation_v4.0.7\\Libation 4.0.7\\LibationFiles","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\aneso\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"C:\\Users\\aneso\\Downloads\\Libation_v4.0.7\\Libation 4.0.7\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\aneso\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-09-22 09:26:01.135 -05:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":1004,"pending":1004,"statusStripText":"BACKUPS: No progress: 1004  Encrypted: 0  Fully backed up: 0","menuItemText":"1004 remaining"}
2020-09-22 09:26:01.281 -05:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":51,"statusStripText":"|  PDFs: NOT d/l'ed: 51  Downloaded: 0","menuItemText":"51 remaining"}
2020-09-22 09:26:01.778 -05:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":1004,"pending":1004,"statusStripText":"BACKUPS: No progress: 1004  Encrypted: 0  Fully backed up: 0","menuItemText":"1004 remaining"}
2020-09-22 09:26:01.795 -05:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":51,"statusStripText":"|  PDFs: NOT d/l'ed: 51  Downloaded: 0","menuItemText":"51 remaining"}
2020-09-22 09:26:31.062 -05:00 [INF] (at FileLiberator.IProcessableExt+<processBookAsync>d__2.MoveNext()) Begin processBookAsync {"Title":"Discovering Your Roots","AudibleProductId":"B00K583BC6","Locale":"us","Account":"myacccount@email.org"}
2020-09-22 09:26:31.077 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: Begin: [B00K583BC6] Discovering Your Roots
2020-09-22 09:26:31.086 -05:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(System.String, System.String, AudibleApi.ILoginCallback)) GetApiAsync. {"username":"myacccount@email.org","LocaleName":"us"}
2020-09-22 09:26:32.190 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: - C:\Users\aneso\Downloads\Libation_v4.0.7\Libation 4.0.7\LibationFiles\bk_tcco_000377.pdf
2020-09-22 09:26:32.734 -05:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":1004,"pending":1004,"statusStripText":"BACKUPS: No progress: 1004  Encrypted: 0  Fully backed up: 0","menuItemText":"1004 remaining"}
2020-09-22 09:26:32.755 -05:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":51,"statusStripText":"|  PDFs: NOT d/l'ed: 51  Downloaded: 0","menuItemText":"51 remaining"}
2020-09-22 09:26:32.772 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: Completed: [B00K583BC6] Discovering Your Roots

2020-09-22 09:26:32.790 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: ERROR. All books have not been processed. Most recent valid book: processing failed
2020-09-22 09:26:32.811 -05:00 [INF] (at LibationWinForms.BookLiberation.ProcessorAutomationController.validateStatus(Dinah.Core.ErrorHandling.StatusHandler, LibationWinForms.BookLiberation.AutomatedBackupsForm)) Automated backup: Downloaded PDF cannot be found
2020-09-22 09:26:32.832 -05:00 [INF] (at LibationWinForms.BookLiberation.AutomatedBackupsForm.AppendText(System.String)) Automated backup: DONE
2020-09-22 09:26:54.477 -05:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"AccountId":"myacccount@email.org","LocaleName":"us"}
2020-09-22 09:26:54.533 -05:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__2.MoveNext()) ImportLibraryAsync. {"AccountName":"myacccount@email.org - us","AccountId":"myacccount@email.org","LocaleName":"us"}

**Comment by rmcrackan** [comment]
@anesone

this looks strangely truncated. Can you post the full contents on pastebin and give me the link. Feel free to redact your email of course

**Comment by anesone** [comment]
@rmcrackan Here is the link to the log file: https://pastebin.pl/view/f7248818

**Comment by rmcrackan** [comment]
@anesone Thanks! I think I found the last bug related to this. Try version 4.0.8  -- https://github.com/rmcrackan/Libation/releases/latest

If this still doesn't work for you, post the new log on pastebin and give me the link. Feel free to redact your email of course
