### ISSUE TITLE
Files still will not download with 5.4.9

### ISSUE THREAD

**Issue by chieftwidgit** [rmcrackan/Libation#81]
I have install 5.4.9 and still can't download files either .aax or .aacx.

**Comment by chieftwidgit** [comment]
2021-08-03 12:03:15.192 -04:00 [INF] (at LibationLauncher.Program.logStartupState(FileManager.Configuration)) 

2021-08-03 12:03:15.242 -04:00 [INF] (at LibationLauncher.Program.logStartupState(FileManager.Configuration)) Begin Libation. {"Version":"5.4.9.5","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"LibationFiles":"C:\\Users\\sjt\\Libation","BooksDirectory":"C:\\Users\\sjt\\Libation\\Books","InProgress":"C:\\Users\\sjt\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDir":"C:\\Users\\sjt\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":2,"DecryptInProgressDir":"C:\\Users\\sjt\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2021-08-03 12:03:18.905 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) Book counts. {"total":0,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":0}
2021-08-03 12:03:18.921 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0}
2021-08-03 12:03:22.366 -04:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=c[...]t@g[...]l.c[...]m|AccountName=c[...]t@g[...]l.c[...]s|Locale=us","LocaleName":"us"}
2021-08-03 12:03:22.433 -04:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__2.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=c[...]t@g[...]l.c[...]m|AccountName=c[...]t@g[...]l.c[...]s|Locale=us"}
2021-08-03 12:03:30.964 -04:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__37.MoveNext()) Page 1: 250 results
2021-08-03 12:03:36.846 -04:00 [INF] (at AudibleApi.Api+<GetAllLibraryItemsAsync>d__37.MoveNext()) Page 2: 182 results
2021-08-03 12:03:37.352 -04:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) GetAllLibraryItems: Total count 429
2021-08-03 12:04:30.115 -04:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Import: New count 429
2021-08-03 12:04:30.839 -04:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) FullReIndex: success
2021-08-03 12:04:37.039 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) Book counts. {"total":429,"booksFullyBackedUp":0,"booksDownloadedOnly":1,"booksNoProgress":428}
2021-08-03 12:04:37.040 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0}
2021-08-03 12:04:41.289 -04:00 [INF] (at LibationWinForms.BookLiberation.ProcessorAutomationController+<BackupSingleBookAsync>d__0.MoveNext()) Begin backup single {"AudibleProductId":"B096G1V7CV"}
2021-08-03 12:04:41.298 -04:00 [INF] (at FileLiberator.IProcessableExt+<ProcessBookAsync_NoValidation>d__2.MoveNext()) Begin ProcessBookAsync_NoValidation {"Title":"Citadel: Axiom Chronicles, Book 2","AudibleProductId":"B096G1V7CV","Locale":"us","Account":"c[...]t@g[...]l.c[...]m"}
2021-08-03 12:04:41.307 -04:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Decrypt Step, Begin: [B096G1V7CV] Citadel: Axiom Chronicles, Book 2
2021-08-03 12:04:41.337 -04:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(System.String, System.String, AudibleApi.ILoginCallback)) GetApiAsync. {"Username":"c[...]t@g[...]l.c[...]m","LocaleName":"us"}
2021-08-03 12:04:41.798 -04:00 [INF] (at Dinah.Core.StepRunner.BaseStep.logBegin()) Begin step 'Download and Convert Aaxc To M4b'
2021-08-03 12:04:41.799 -04:00 [INF] (at Dinah.Core.StepRunner.BaseStep.logBegin()) Begin step 'Step 1: Get Aaxc Metadata'
2021-08-03 12:04:42.112 -04:00 [ERR] (at Dinah.Core.StepRunner.BaseStep.logEnd(System.Boolean, System.TimeSpan, System.Exception)) End step 'Step 1: Get Aaxc Metadata'. FAILED. Completed in 00:00:00
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at AaxDecrypter.NetworkFileStream.BeginDownloading() in C:\Users\mbuca\source\repos\Libation\AaxDecrypter\NetworkFileStream.cs:line 191
   at AaxDecrypter.AaxcDownloadConverter.Step1_GetMetadata() in C:\Users\mbuca\source\repos\Libation\AaxDecrypter\AaxcDownloadConverter.cs:line 116
   at Dinah.Core.StepRunner.BasicStep.RunRaw() in C:\Users\mbuca\source\repos\Dinah.Core\Dinah.Core\StepRunner\BasicStep.cs:line 10
   at Dinah.Core.StepRunner.BaseStep.Run() in C:\Users\mbuca\source\repos\Dinah.Core\Dinah.Core\StepRunner\Abstract_BaseStep.cs:line 22
2021-08-03 12:04:42.116 -04:00 [ERR] (at Dinah.Core.StepRunner.BaseStep.logEnd(System.Boolean, System.TimeSpan, System.Exception)) End step 'Download and Convert Aaxc To M4b'. FAILED. Completed in 00:00:00
2021-08-03 12:04:42.117 -04:00 [INF] (at Dinah.Core.IO.SerilogTextWriter.WriteLine(System.String)) WARNING-Conversion failed
2021-08-03 12:04:42.145 -04:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Decrypt Step, Completed: [B096G1V7CV] Citadel: Axiom Chronicles, Book 2

2021-08-03 12:04:42.150 -04:00 [ERR] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_1(System.Object, System.String)) Decrypt failed
2021-08-03 12:04:42.158 -04:00 [ERR] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_1(System.Object, System.String)) ERROR. All books have not been processed. Most recent book: processing failed
2021-08-03 12:04:42.361 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) Book counts. {"total":429,"booksFullyBackedUp":0,"booksDownloadedOnly":1,"booksNoProgress":428}
2021-08-03 12:04:42.362 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts()) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0}
2021-08-03 12:04:58.817 -04:00 [INF] (at LibationWinForms.BookLiberation.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: DONE

**Comment by Mbucari** [comment]
Any partially downloaded file in %temp%\Libation\DownloadsInProgress will have the old, now invalud, user-agent in the .json file. Just delete everything in that folder and try again.

**Comment by chieftwidgit** [comment]
That appears to work.  Thanks

**Comment by Mulchman** [comment]
That fixed the problem for me as well. Thanks @Mbucari !

(Prior to that, line 191 in NetworkFileStream.cs was throwing 403 exceptions.)

**Comment by docbha** [comment]
Thanks working now !!!
