### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by eirek1234** [rmcrackan/Libation#818]
New install using 11.3.0

I first tried to use this on Windows Chardonnay version but it would never let me add an account.  I moved over to the windows classic and it would let me add the account. When I try to sync my Audible the bottom right says no books. Begin by Importing your library, However when I try to import it just comes up with this repeating error.

[error.txt](https://github.com/rmcrackan/Libation/files/13822957/error.txt)

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach the full log?

**Comment by eirek1234** [comment]
This is all I can find which I included on the first post.  The log file in zip format is empty.

Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 53
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by rmcrackan** [comment]
Does [v11.1](https://github.com/rmcrackan/Libation/releases/tag/v11.1.0) work for you? I'm getting concerned that this might be an issue with v11.3

**Comment by eirek1234** [comment]
Newest Version released yesterday fixed my problems and all is good.

**Comment by rmcrackan** [comment]
Hooray. Thanks for the update
