### ISSUE TITLE
Libation crashed at launching

### ISSUE THREAD

**Issue by ghost** [rmcrackan/Libation#833]
Platform

Arch Linux

Dependencies installed:

dotnet-sdk

Build (AUR - package), also tested with Snap unofficial build.

pkgname=libation
_pkgname=Libation
pkgver=11.0.4
pkgrel=1
pkgdesc="Audible Audiobook Manager: Liberate your Library"
arch=("any")
url="https://github.com/rmcrackan/Libation"
license=("GPL-3.0")
makedepends=("dotnet-sdk")
source=("$_pkgname-$pkgver.tar.gz::$url/archive/refs/tags/v$pkgver.tar.gz")
sha256sums=("d61632877f09696959a5227a50c16e2b876b4084d8df207e3de21d849e59bfc5")

build() {
  cd $_pkgname-$pkgver
  dotnet publish -c Release -o ./build ./Source/LibationCli/LibationCli.csproj -p:PublishProfile=./Source/LibationCli/Properties/PublishProfiles/LinuxProfile.pubxml
  dotnet publish -c Release -o ./build ./Source/LibationAvalonia/LibationAvalonia.csproj -p:PublishProfile=./Source/LibationAvalonia/Properties/PublishProfiles/LinuxProfile.pubxml
  dotnet publish -c Release -o ./build ./Source/HangoverAvalonia/HangoverAvalonia.csproj -p:PublishProfile=./Source/HangoverAvalonia/Properties/PublishProfiles/LinuxProfile.pubxml
}

package() {
  cd $_pkgname-$pkgver

  mkdir -p "$pkgdir/usr/share/icons/hicolor/scalable/apps"
  mkdir -p "$pkgdir/usr/share/applications"
  mkdir -p "$pkgdir/usr/lib"
  mkdir -p "$pkgdir/usr/bin"

  cp -v Images/libation_glass.svg "$pkgdir/usr/share/icons/hicolor/scalable/apps/libation.svg"
  cp -v Source/LoadByOS/LinuxConfigApp/Libation.desktop "$pkgdir/usr/share/applications/Libation.desktop"
  mv -v build "$pkgdir/usr/lib/libation"

  chmod +666 "$pkgdir/usr/share/icons/hicolor/scalable/apps/libation.svg"
  ln -s "/usr/lib/libation/Libation" "$pkgdir/usr/bin/Libation"
  ln -s "/usr/lib/libation/Libation" "$pkgdir/usr/bin/libation"
  ln -s "/usr/lib/libation/Hangover" "$pkgdir/usr/bin/Hangover"
  ln -s "/usr/lib/libation/LibationCli" "$pkgdir/usr/bin/LibationCli"
  ln -s "/usr/lib/libation/LibationCli" "$pkgdir/usr/bin/libationcli"

  touch "$pkgdir/usr/lib/libation/appsettings.json"
  chmod 666 "$pkgdir/usr/lib/libation/appsettings.json"
}

Crash Log, is it missing any FONT dependency?

2024/01/25 15:02:29 - Libation Crash
 OS                    Linux
 Version               11.0.4.1
 ReleaseIdentifier     None
 InteropFunctionsType  
 LibationFiles         /home/ryan/Libation
 Books Folder          
 === EXCEPTION ===
 System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Media.Typeface.get_GlyphTypeface()
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer()
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces)
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at LibationAvalonia.Dialogs.SetupDialog..ctor() in /home/ryan/.cache/yay/libation/src/Libation-11.0.4/Source/LibationAvalonia/Dialogs/SetupDialog.axaml.cs:line 12
   at LibationAvalonia.App.OnFrameworkInitializationCompleted() in /home/ryan/.cache/yay/libation/src/Libation-11.0.4/Source/LibationAvalonia/App.axaml.cs:line 64
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at LibationAvalonia.Program.Main(String[] args) in /home/ryan/.cache/yay/libation/src/Libation-11.0.4/Source/LibationAvalonia/Program.cs:line 65

**Comment by lufixSch** [comment]
I have the same Problem (#939). Where you able to solve this?

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
