### ISSUE TITLE
All downloads suddenly started failing

### ISSUE THREAD

**Issue by jjedele** [rmcrackan/Libation#834]
First of all, thx for your work. This tool is amazing!

**Version**
Libation 11.3.4

**Bug**
Everything worked like a charm for a while, but then suddenly _all_ my downloads stated failing directly.

**Reproducing**
Not sure, it worked in the beginning and then suddenly it stopped. I think my computer crashed somewhere inbetween, so maybe some working folder got messed up in a way Libation cannot handle yet?

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/779877/b711fbfe-bc72-479c-a301-9f2794a4b9e9)

**Platform**
Ubuntu 23.04

**Log Files**
For each failing download there is this error:

```
{}2024-01-26 20:16:31.298 +01:00 [ERR] (at LibationUiBase.LogMe.Error(System.Exception, System.String)) Download & Decrypt
System.NullReferenceException: Object reference not set to an instance of an object.
   at AaxDecrypter.AudiobookDownloadBase.OpenNetworkFileStream() in /home/runner/work/Libation/Libation/Source/AaxDecrypter/AudiobookDownloadBase.cs:line 226
   at AaxDecrypter.AudiobookDownloadBase..ctor(String outFileName, String cacheDirectory, IDownloadOptions dlOptions) in /home/runner/work/Libation/Libation/Source/AaxDecrypter/AudiobookDownloadBase.cs:line 56
   at AaxDecrypter.AaxcDownloadSingleConverter..ctor(String outFileName, String cacheDirectory, IDownloadOptions dlOptions) in /home/runner/work/Libation/Libation/Source/AaxDecrypter/AaxcDownloadSingleConverter.cs:line 15
   at FileLiberator.DownloadDecryptBook.downloadAudiobookAsync(LibraryBook libraryBook) in /home/runner/work/Libation/Libation/Source/FileLiberator/DownloadDecryptBook.cs:line 137
   at FileLiberator.DownloadDecryptBook.ProcessAsync(LibraryBook libraryBook) in /home/runner/work/Libation/Libation/Source/FileLiberator/DownloadDecryptBook.cs:line 56
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in /home/runner/work/Libation/Libation/Source/FileLiberator/Processable.cs:line 54
   at LibationAvalonia.ViewModels.ProcessBookViewModel.ProcessOneAsync() in /home/runner/work/Libation/Libation/Source/LibationAvalonia/ViewModels/ProcessBookViewModel.cs:line 138
 {"ExceptionDetail":{"Type":"System.NullReferenceException","HResult":-2147467261,"Message":"Object reference not set to an instance of an object.","Source":"AaxDecrypter","TargetSite":"AaxDecrypter.NetworkFileStreamPersister OpenNetworkFileStream()"}}2024-01-26 20:16:31.304 +01:00 [ERR] (at LibationAvalonia.ViewModels.ProcessBookViewModel+<showRetry>d__77.MoveNext()) ERROR. All books have not been processed. Most recent book: processing failed
```

**Comment by rmcrackan** [comment]
Sorry about this. Sounds like some temp file got borked. Your default temp folder in windows is `C:\Users\<username>\AppData\Local\Temp\Libation`. Please delete the whole folder, restart Libation and try again.

If you don't have this folder, you can find it via: Libation > Settings > Settings > Open log folder. Open the Settings.json file in a text editor, like notepad. Near the top is an entry for InProgress. For windows, it will use `\\` instead of `\` because of the type of file that settings are stored in. Turn them back into single `\` to find your real folder.

Lemme know if this works.

**Comment by jjedele** [comment]
Ok, I think I figured it out.

Turns out my Linux is putting the `/tmp` folder into RAM. Then on download a bigger audio book, it runs full, the laptop crashes and the temp files get corrupted somehow. I now moved the temporary directory to another folder, and it works like a charm again.

Thx for your help!

**Comment by rmcrackan** [comment]
Bizarre. Much thanks for the follow-up
