### ISSUE TITLE
Unable to open database file on startup

### ISSUE THREAD

**Issue by DavidSchor** [rmcrackan/Libation#839]
**Describe the bug**
When opening Libation I get this error:
SQLite Error 14: 'unable to open database file'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Dinah.EntityFrameworkCore.DesignTimeDbContextFactoryBase`1.Create(String connectionString)
   at ApplicationServices.DbContexts.GetLibrary_Flat_NoTracking(Boolean includeParents) in D:\a\Libation\Libation\Source\ApplicationServices\DbContexts.cs:line 17
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LibationWinForms.Program.<>c__DisplayClass1_0.<<Main>b__0>d.MoveNext() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 88
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**To Reproduce**
[Log202402.zip](https://github.com/rmcrackan/Libation/files/14140047/Log202402.zip)

After closing Libation I opened it again and got the error above.
Libation is on a cloud drive (think dropbox/gdrive) specifically PCloud. It allows me to keep track of what is imported regardless of which pc I use and has worked without issue so far (as long as settings files are also in cloud)

**Expected behavior**
Libation opens and does default behaviour.

**Screenshots**

**Platform**
Windows 11. Libation is on cloud drive.

**Log Files**
[Log202402.zip](https://github.com/rmcrackan/Libation/files/14140047/Log202402.zip)

**Comment by DavidSchor** [comment]
I had:
![image](https://github.com/rmcrackan/Libation/assets/742586/4b1d13b3-3cd2-423b-a699-c0ab068477a7)

I updated to 11.3.4 and restarted PCloud and it resolved the error. I don't know which step did it. I will make sure to have done those first if I experience issues again. Thank you for your time, help and amazing software!
