### ISSUE TITLE
Earlier library scan working fine now its not working

### ISSUE THREAD

**Issue by Farcry3413** [rmcrackan/Libation#840]
**Describe the bug**
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 57
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 138
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201

i tried deleting Libation.11.1.0-windows-chardonnay then reinstall, 11.3.3 and 11.3.4 versions still application unable to scan my library after successful login, i have only 90-100 books.

**To Reproduce**

1. Go to 'Import'
2. Click on 'Scan library optiom.'
3. See error

**Expected behavior**
Scanning library should not give any errors

**Platform**
Windows 11

**Log Files**
[_Log202402.zip](https://github.com/rmcrackan/Libation/files/14144685/_Log202402.zip)

**Comment by rmcrackan** [comment]
Sorry about this. I wonder if this related to the new version. Do you still get this the error if you use [v11.1.0](https://github.com/rmcrackan/Libation/releases/tag/v11.1.0)?

**Comment by Farcry3413** [comment]
yes earlier 11.1.0 working now i tried clean install of 11.1.0 and its also giving same error

**Comment by rmcrackan** [comment]
Gotcha. Since 11.1 isn't working either, it's probably not about the version. Unfortunately this a fairly generic networking error. Is there a way for you to try on a different network so we can see if this only happens on that network?

**Comment by Farcry3413** [comment]
tried with my mobile 5g hotspot still same issue

**Comment by rmcrackan** [comment]
@mkb79 -- have you seen more users lately with network errors? This seems to be happening more these days.

**Comment by mkb79** [comment]
@rmcrackan
I'll can report that I had some network issues when downloading aax files. I had to set timeout to 20 - 30 sec. to successfully download books. But this behavior occurred only sporadically and not reproducibly.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
