### ISSUE TITLE
Could not deserialize json

### ISSUE THREAD

**Issue by daft-goose** [rmcrackan/Libation#849]
[_Log202402_002.zip](https://github.com/rmcrackan/Libation/files/14271466/_Log202402_002.zip)

Could not deserialize json: 

   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Form1.refreshImportMenu(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by rmcrackan** [comment]
Sorry about this. It looks like somehow your `AccountsSettings.json` might have gotten corrupted. If you delete this file and restart Libation, you'll just need to re-do your login(s). AccountsSettings is in the same folder as your log files.

**Comment by daft-goose** [comment]
Solved, thank you!

**Comment by rmcrackan** [comment]
You're welcome
