### ISSUE TITLE
Error Importing library 

### ISSUE THREAD

**Issue by willl1992** [rmcrackan/Libation#852]
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 53
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

[_Log202402.zip](https://github.com/rmcrackan/Libation/files/14318190/_Log202402.zip)

   
   
![image](https://github.com/rmcrackan/Libation/assets/160312322/0c1acfcc-cb9e-43b5-9f98-c12dd1fc3d3a)

**Comment by willl1992** [comment]
i think thats all th einfo i can giv im VERY new to this kinda stuff

**Comment by rmcrackan** [comment]
Sorry about this. Thank you very much for attaching the log.

The only error I see is a timeout. For now turn off auto-scan so it's not trying over and over -- "import" menu, click the top item if it's checked. Do a manual scan ("import" menu, 2nd item down) and see if you still get an error. If yes, see if you can try when connected to a different network (friend's wifi, coffee shop, phone hotspot, etc) and see if that gives the same error. I'm curious to see if this is specific to your main home network.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.
