### ISSUE TITLE
Fatal error pre loggin

### ISSUE THREAD

**Issue by alias1957** [rmcrackan/Libation#859]
Dispositivo non pronto. : 'H:\Documenti\Aubibile 2'

   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at FileManager.PersistentDictionary..ctor(String filepath, Boolean isReadOnly) in D:\a\Libation\Libation\Source\FileManager\PersistentDictionary.cs:line 30
   at LibationFileManager.Configuration.get_LibationFiles() in D:\a\Libation\Libation\Source\LibationFileManager\Configuration.LibationFiles.cs:line 32
   at LibationFileManager.Configuration.get_SettingsFilePath() in D:\a\Libation\Libation\Source\LibationFileManager\Configuration.PersistentSettings.cs:line 83
   at LibationFileManager.Configuration.get_LibationSettingsAreValid() in D:\a\Libation\Libation\Source\LibationFileManager\Configuration.cs:line 12
   at LibationWinForms.Program.RunInstaller(Configuration config) in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 98
   at LibationWinForms.Program.Main() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 45

**Comment by alias1957** [comment]
Thanks I've solved the problem.

Maurizio

**Comment by rmcrackan** [comment]
Wonderful. Thanks for following up.
