### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by ysmorid** [rmcrackan/Libation#868]
**Describe the bug**
When trying to manually scan library, get error "Error Importing Library"
Tried multiple times over multiple days with the same issue.

**To Reproduce**
Click Import -> Scan Library

**Expected behavior**
Should import new books in my Audible library

**Screenshots**
![Screenshot 2024-03-20 115707](https://github.com/rmcrackan/Libation/assets/6166756/d278a3d3-0064-409e-bc1e-74123a5ee9da)

**Platform**
Windows 11 Home

**Log Files**
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 57
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach your log to this ticket? In Libation Settings there's a button on the first settings screen to help find it: "Open log folder"

**Comment by ysmorid** [comment]
Hi, I tried to access the logs with no luck.  There are no files for today's date, and the compressed folder labeled `Log202403` will not be unzipped as it says it is an empty folder.

**Comment by rmcrackan** [comment]
Thanks -- that's actually very helpful. This 0kb log file bug was specific to a few releases that I had to rescend. When you go to Settings > About, What version is in the top left? If it's bigger than 11.1.0.1, I recommend using [version 11.1](https://github.com/rmcrackan/Libation/releases/latest) instead and see if this fixes the bug.

**Comment by ysmorid** [comment]
ETA: I made sure to delete any other versions of Libation I had, and am only running version 11.1 classic.
I also tried deleting and re-adding my account, but am getting the same error: `Exception of type 'AudibleApi.ApiErrorException' was thrown.`

**Comment by rmcrackan** [comment]
The log thing is very strange. Let's delete the latest log (202403), get the error to happen again, then attach the zip file to this ticket. No need to unzip (unless you really want to).

**Comment by ysmorid** [comment]
Apologies for the delay; I didn't get the notification.
I deleted the previous logs, retried manually importing the library, and retried to download a book.  
Here are the zipped log files for those 2 actions. Hopefully you're able to open them:

[Log202403_001.zip](https://github.com/rmcrackan/Libation/files/14734183/Log202403_001.zip)

**Comment by IVleafclover** [comment]
I have the exact same issue with an audible.com (us) account that is active, but has not bought any book for its credits. I only wanted to use Libation for downloading a followed podcast.
I used one of the pre-release versions before and downgraded to 11.1 after that. I am not sure how to delete my settings, because 11.1 was finding the settings I made in the pre-release version.

**Comment by rmcrackan** [comment]
@ysmorid : Thank you for the log. This doesn't appear to be a software bug. "The request failed due to an underlying issue such as network connectivity, DNS failure, server certificate validation or timeout." I'm assuming this is your main network and this error is misleading. There are a few cryptic messages like this and the one below which are really frustrating. Can you try Libation on another network (friend, coffee shop, phone hotspot, ...) and see if you still get an error?

@IVleafclover : All of your errors are "The request failed due to timeout." This is another error which can be misleading, but audible doesn't reveal anything more. I recommend the same approach as above. That is: see if another network helps.

**Comment by rmcrackan** [comment]
There are 4 urls for each locale. Example, the US site has ".com"

https://www.audible.com
https://www.amazon.com
https://api.audible.com
https://api.amazon.com

UK:

https://www.audible.co.uk
https://www.amazon.co.uk
https://api.audible.co.uk
https://api.amazon.co.uk

[The full list is here](https://github.com/rmcrackan/AudibleApi/blob/master/AudibleApi/Localization.cs). `topDomain` determines the url endings

**Comment by ysmorid** [comment]
Ok, I did a hotspot and it worked.  I'm not sure what changed with my service, but I'll dig into it to see if I can't get it working again.  Thanks!

**Comment by rmcrackan** [comment]
Ooooh, interesting. Please tell me more about the router issue and your fix. I wonder how many others this has affected without me realizing it.

**Comment by ysmorid** [comment]
After you told me it seemed to be a network issue, I hotspot my phone's mobile data to see if I could import my library and download a book, and they both worked.

Because the error code and your feedback was a timeout with Amazon API, I went through my router settings to see if Amazon/AWS was getting caught in my firewall or some other security feature, and even turned off all security features temporarily to test with no luck.  When researching online, I saw someone else mention that their Amazon Prime Video wouldn't load, and a response said how AWS/Amazon isn't compatible/won't work with IPv6, so when disabling that so that IPv4 was the only option available, all the issues I've been having disappeared.

I'm actually surprised by this, as looking on the AWS website, they do say they support IPv6.  This could be an AT&T router issue, but so far this app is the only thing that's given me issues.  I do know other services/sites only work on IPv4, so if others have issues, I would recommend they check their router settings and see if changing that helps.

**Comment by IVleafclover** [comment]
> There are 4 urls for each locale. Example, the US site has ".com"
> 
> https://www.audible.com https://www.amazon.com https://api.audible.com https://api.amazon.com
> 
> UK:
> 
> https://www.audible.co.uk https://www.amazon.co.uk https://api.audible.co.uk https://api.amazon.co.uk
> 
> [The full list is here](https://github.com/rmcrackan/AudibleApi/blob/master/AudibleApi/Localization.cs). `topDomain` determines the url endings

I was able to test it. Pinging api.audible.com was not possible. My provider resolves its ip wrong. I will fix it with adding it to my hosts file.
So no issue you have to fix.
Thank you for your time and your good tool.
