### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by Badland** [rmcrackan/Libation#875]
**Describe the bug**
I just created my account on libation. 
After a successful login, I tried importing the library and run systematically in this error. 

**Expected behavior**
My library is imported

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/47223591/1e924a81-3252-4c63-97b1-452b3ef261a7)

error text : 
CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Platform**

Windows 11 23H2
**Log Files**
[_Log202404.zip](https://github.com/rmcrackan/Libation/files/14835444/_Log202404.zip)

**Comment by rmcrackan** [comment]
Sorry about this error. If you use a different network does this still happen?

**Comment by Badland** [comment]
Thanks for the quick response, on my phone data it works fine indeed !

Jean de Malartic
18 rue Lecourbe
06 48 05 63 89

**Comment by rmcrackan** [comment]
In that case it's a networking thing. Some more tech savvy users have had luck messing with the ipv6 settings on their routers. I have not been able to reproduce it on any hardware I own so I'm afraid I can't address it better at the moment -- since I have no way to test or debug possible solutions.
