### ISSUE TITLE
Unhandled exception downloading 

### ISSUE THREAD

**Issue by demoran23** [rmcrackan/Libation#88]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudibleApi.Api.GetPdfDownloadLinkAsync(String asin) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Api.Download.cs:line 167
   at FileLiberator.DownloadPdf.downloadPdfAsync(LibraryBook libraryBook, String proposedDownloadFilePath) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadPdf.cs:line 55
   at FileLiberator.DownloadPdf.ProcessItemAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadPdf.cs:line 23
   at FileLiberator.DownloadableBase.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadableBase.cs:line 35
   at FileLiberator.IProcessableExt.TryProcessAsync(IProcessable processable, LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\IProcessableExt.cs:line 47
   at LibationWinForms.BookLiberation.ProcessorAutomationController.<>c__DisplayClass4_0.<<CreateBackupBook>g__onDownloadDecryptBookCompleted|0>d.MoveNext() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\BookLiberation\ProcessorAutomationController.cs:line 108
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
```

After allowing the process to continue with other books, this appeared a few more times and then stopped.  However, I started to see the following error afterwards:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'PdfDownloadForm'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at LibationWinForms.SynchronizeInvoker.ThreadMethodEntry.Complete() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\SynchronizeInvoker.cs:line 114
   at LibationWinForms.SynchronizeInvoker.Invoke(Delegate method, Object[] args) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\SynchronizeInvoker.cs:line 61
   at LibationWinForms.BookLiberation.BaseForms.LiberationBaseForm.OnStreamingBeginShow(Object sender, String beginString) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\BookLiberation\BaseForms\LiberationBaseForm.cs:line 135
   at FileLiberator.DownloadableBase.PerformDownloadAsync(String proposedDownloadFilePath, Func`2 func) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadableBase.cs:line 51
   at FileLiberator.DownloadPdf.downloadPdfAsync(LibraryBook libraryBook, String proposedDownloadFilePath) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadPdf.cs:line 61
   at FileLiberator.DownloadPdf.ProcessItemAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadPdf.cs:line 30
   at FileLiberator.DownloadableBase.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\DownloadableBase.cs:line 41
   at FileLiberator.IProcessableExt.TryProcessAsync(IProcessable processable, LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\FileLiberator\IProcessableExt.cs:line 47
   at LibationWinForms.BookLiberation.ProcessorAutomationController.<>c__DisplayClass4_0.<<CreateBackupBook>g__onDownloadDecryptBookCompleted|0>d.MoveNext() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\BookLiberation\ProcessorAutomationController.cs:line 108
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
```

**Comment by rmcrackan** [comment]
I’ll look into this. Can you attach the log file?

**Comment by demoran23** [comment]
[_Log202108.zip](https://github.com/rmcrackan/Libation/files/7025530/_Log202108.zip)

**Comment by Mbucari** [comment]
The only errors in the log are from Audible giving an error code 000307: Unable to retrieve asset details from Sable(CDN), fallback to CDS...

As for the errors you're seeing, I just pushed a fix.

**Comment by rmcrackan** [comment]
Thanks for the log file. Code is complete for fixing this -- thanks @Mbucari ! It will be fixed in the next release which will probably be this weekend so I'm going to close this issue

**Comment by rmcrackan** [comment]
[New version](https://github.com/rmcrackan/Libation/releases/latest) released. If pdf downloads still give you trouble, please reply here with your new log and I'll take another look
