### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by Pantechniconsole** [rmcrackan/Libation#884]
Following a system crash, I've been trying to move my Libation setup to a new Windows machine, using Classic 11.1.01 (which the old machine should have been using). I have tried various ways of linking to the directory containing the books but Libation can't do simple tasks such as filtering on book metadata. Libation can, however successfully download new books.

I have turned on debug logging and am seeing the following type of error
 {}2024-04-21 14:44:46.075 +01:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Begin long-running import
 {}2024-04-21 14:44:47.810 +01:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Error importing library
Lucene.Net.Index.CorruptIndexException: checksum mismatch in segments file
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, StreamWriter infoStream, DocumentsWriter docWriter, HashSet`1 synced)
   at Lucene.Net.Index.IndexWriter.Init(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, Int32 maxFieldLength, IndexingChain indexingChain, IndexCommit commit)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, Analyzer a, Boolean create, MaxFieldLength mfl)
   at LibationSearchEngine.SearchEngine.CreateNewIndex(IEnumerable`1 library, Boolean overwrite) in D:\a\Libation\Libation\Source\LibationSearchEngine\SearchEngine.cs:line 80
   at ApplicationServices.SearchEngineCommands.update(Action`1 action) in D:\a\Libation\Libation\Source\ApplicationServices\SearchEngineCommands.cs:line 84
   at ApplicationServices.SearchEngineCommands.performSafeCommand(Action`1 action) in D:\a\Libation\Libation\Source\ApplicationServices\SearchEngineCommands.cs:line 64
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 331
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 143
 {"ExceptionDetail":{"HResult":-2146232800,"Message":"checksum mismatch in segments file","Source":"LuceneNet303r2","TargetSite":"Void Read(Lucene.Net.Store.Directory, System.String)","Type":"Lucene.Net.Index.CorruptIndexException"}}2024-04-21 14:44:48.246 +01:00 [ERR] (at LibationWinForms.Form1+<<Configure_ScanAuto>b__115_0>d.MoveNext()) Error invoking auto-scan
Lucene.Net.Index.CorruptIndexException: checksum mismatch in segments file
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, StreamWriter infoStream, DocumentsWriter docWriter, HashSet`1 synced)
   at Lucene.Net.Index.IndexWriter.Init(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, Int32 maxFieldLength, IndexingChain indexingChain, IndexCommit commit)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, Analyzer a, Boolean create, MaxFieldLength mfl)
   at LibationSearchEngine.SearchEngine.CreateNewIndex(IEnumerable`1 library, Boolean overwrite) in D:\a\Libation\Libation\Source\LibationSearchEngine\SearchEngine.cs:line 80
   at ApplicationServices.SearchEngineCommands.update(Action`1 action) in D:\a\Libation\Libation\Source\ApplicationServices\SearchEngineCommands.cs:line 84
   at ApplicationServices.SearchEngineCommands.performSafeCommand(Action`1 action) in D:\a\Libation\Libation\Source\ApplicationServices\SearchEngineCommands.cs:line 64
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 331
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 143
   at LibationWinForms.Form1.<Configure_ScanAuto>b__115_0(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanAuto.cs:line 37
 {"ExceptionDetail":{"HResult":-2146232800,"Message":"checksum mismatch in segments file","Source":"LuceneNet303r2","TargetSite":"Void Read(Lucene.Net.Store.Directory, System.String)","Type":"Lucene.Net.Index.CorruptIndexException"}}

**To Reproduce**

This is not a bug that is going to be replicated between machines

**Expected behavior**
The library should be searchable, but it isn't. Best guess is that importing books is somehow failing

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]
Windows 11 version 10.0.22000 Build 10.0.22000
Libation Classic 11.1.01

**Log Files**
[Log202404_001.zip](https://github.com/rmcrackan/Libation/files/15052241/Log202404_001.zip)

**Comment by rmcrackan** [comment]
Thank you much for the log file. `Lucene.Net.Index.CorruptIndexException` -- never seen this before; it looks like the search engine's files got corrupted.

* Close Libation
* Go into the folder with your log file and delete the `SearchEngine` folder
* Open Libation. The big grid should be empty.
* Do a new scan
* After the scan is complete, everything should go back to normal

Let me know whether this works.

**Comment by Pantechniconsole** [comment]
Thankyou, I deleted the SearchEngine folder and restarted. The big grid
came back immediately, but searching works fine and the log file looks good.

Many thanks for the prompt reply!

Cheers

**Comment by rmcrackan** [comment]
Nice! Thanks for the follow-up. Any other pending issues?

**Comment by Pantechniconsole** [comment]
It looks good to go for the moment - thanks for the effort you put in on
Libation!

**Comment by rmcrackan** [comment]
You're welcome :)

**Comment by Pantechniconsole** [comment]
I’ve paypal’ed you a couple of coffee’s worth - it was the least I could do.

**Comment by rmcrackan** [comment]
:D Wow -- thank you so much!
