### ISSUE TITLE
[MacOS] Libation crashes when the TMP and Download directories are stored on a SMB share

### ISSUE THREAD

**Issue by Flameborn** [rmcrackan/Libation#885]
**Describe the bug**
If the *download* and *tmp* directories are stored on a SMB share, Libation crashes after liberating a book. The decrypted m4b file is moved to the download directory, after which the crash happens.

**To Reproduce**
Liberate any book with any account, either as a single or a batch action.

**Expected behavior**
Libation should stay open, the books status should be set as downloaded.

**Screenshots**
NA.

**Platform**
MacOS 12.7.4, likely higher versions too.

**Log Files**
```
2024. 03. 07. 16:19:47 - Libation Crash
 OS                    MacOS
 Version               11.3.6.1
 ReleaseIdentifier     MacOSAvalonia
 InteropFunctionsType  MacOSConfigApp.MacOSInterop
 LibationFiles         /Users/MacUser/Libation
 Books Folder          /Users/MacUser/Libation/Books
 === EXCEPTION ===
 System.TypeInitializationException: The type initializer for 'LibationFileManager.AudibleFileStorage' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path '/Volumes/hd3' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at LibationFileManager.AudibleFileStorage.get_DecryptInProgressDirectory() in /Users/runner/work/Libation/Libation/Source/LibationFileManager/AudibleFileStorage.cs:line 23
   at LibationFileManager.AudibleFileStorage..cctor() in /Users/runner/work/Libation/Libation/Source/LibationFileManager/AudibleFileStorage.cs:line 29
   --- End of inner exception stack trace ---
   at LibationFileManager.AudibleFileStorage.get_BooksDirectory() in /Users/runner/work/Libation/Libation/Source/LibationFileManager/AudibleFileStorage.cs:line 43
   at AppScaffolding.LibationScaffolding.logStartupState(Configuration config) in /Users/runner/work/Libation/Libation/Source/AppScaffolding/LibationScaffolding.cs:line 230
   at AppScaffolding.LibationScaffolding.RunPostMigrationScaffolding(Variety variety, Configuration config) in /Users/runner/work/Libation/Libation/Source/AppScaffolding/LibationScaffolding.cs:line 103
   at LibationAvalonia.Program.Main(String[] args) in /Users/runner/work/Libation/Libation/Source/LibationAvalonia/Program.cs:line 58
```

**Comment by Flameborn** [comment]
This has been fixed in 12.0.
