### ISSUE TITLE
ERROR Importing Audible Library

### ISSUE THREAD

**Issue by arivias1** [rmcrackan/Libation#897]
I have Libation Classic 11.1.0 for Windows.

I was experiencing issues with downloading my library from Audible. I couldn't understand the rhyme or reason as to why some would download and why some would throw out an error. Some of the books are books I have purchased; some are from audible plus. This seems to not make a difference neither does the size.  I removed the program and re-downloaded it to see if that would fix the issue. It did not. 10/73 audio books downloaded. 

Here is the error code when I try to manually scan library. 
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 59
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 57
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 287
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 439
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 402
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 169
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 169
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 317
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 266
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 266
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 179
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by rmcrackan** [comment]
> Some of the books are books I have purchased; some are from audible plus.

That is super weird. Thank you for doing that diligence. A few people have had network issues so I've been playing around with some different settings. Let me know if this pre-release helps you -- https://github.com/rmcrackan/Libation/releases/tag/v11.3.8

**Comment by rmcrackan** [comment]
For the X-es, right-click and set status to 'not downloaded'. See if another liberate helps. For any which are still either red or X, please check if these are books that are no longer in your library. Especially books which used to be part of the audible Plus catalog that maybe they later removed from Plus.

**Comment by Cloggin** [comment]
@rmcrackan FWIW: Experienced the same issue this week, no additional parameters or variables in my (logs or) report make any difference than what's already been reported. The [pre-release](https://github.com/rmcrackan/Libation/issues/897#issuecomment-2098617645) version you listed in this thread solved whatever hang ups I was having.

**Comment by rmcrackan** [comment]
@Cloggin Thanks for the update. I'm glad it worked

@arivias1 This thread has gone stale so I'm going to close it out. If you add more, I'll still get notifications and can re-open if needed.
