### ISSUE TITLE
Unable to import library from Audible

### ISSUE THREAD

**Issue by mazzy1234** [rmcrackan/Libation#898]
HI there,

I am new here. I followed the directions, and a few tips from the site (like turning off VPN), but I am still unable to import my library from Audible. I get the following error message

One or more errors occurred. (Collection contains Series with null SeriesName (Parameter 'items'))

   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 293
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201
**Describe the bug**

**To Reproduce**

1. Go to Libation
2. Click on import, then scan
3. See error

**Expected behavior**
I expected my audible library to appear in the Libation app, or something similar.

**Screenshots**

**Platform**

Windows 11

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
I'm sorry for this bug. Can you try this pre-release version and let me know if it fixes your issue? https://github.com/rmcrackan/Libation/releases/tag/v11.3.5

**Comment by joshrivers** [comment]
I had the error described above and the pre-release you linked resolved that issue for me. Thank you.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
