### ISSUE TITLE
Unable to scan and import new titles 

### ISSUE THREAD

**Issue by zenchijen** [rmcrackan/Libation#907]
Error message when attempting to scan library for new entries

**To Reproduce**
1 go to Import
2 click on Scan

**Expected behavior**
I expected to import the new files since I last used Libation

Error Text:
 One or more errors occurred. (Collection contains Series with null SeriesName (Parameter 'items'))

   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 293
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Platform**
Windows 10
Classic Libation 11.1

**Log Files**
[_Log202405_005.log](https://github.com/rmcrackan/Libation/files/15339323/_Log202405_005.log)

**Comment by rmcrackan** [comment]
Sorry about this. I found and fixed this bug in my pre-releases but I haven't put out a new full release yet. It's fixed in here -- https://github.com/rmcrackan/Libation/releases/tag/v11.3.13

**Comment by zenchijen** [comment]
Thanks so much for all your hard work! I'm new to Libation, and it's a godsend.  I appreciate you!

**Comment by rmcrackan** [comment]
:D You're welcome
