### ISSUE TITLE
Error when opening application

### ISSUE THREAD

**Issue by aj149004** [rmcrackan/Libation#910]
**The application opens as a blank form with no options to import my library or sign into or out of my account. **

**To Reproduce**

1. Go to downloaded files 
2. Click on click on the application icon
4. See error code below

**The application to open with the books that were imported from my library**

Could not deserialize json: 

   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Form1.refreshImportMenu(Object _, EventArgs __) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Platform**
Windows 11
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
Sorry about this. It sounds like your AccountsSettings file got corrupted. Just rename or delete it and restart Libation. You'll need to re-add your account(s). After

**Comment by aj149004** [comment]
Thank you that worked.
