### ISSUE TITLE
New Issue 

### ISSUE THREAD

**Issue by Ally526** [rmcrackan/Libation#917]
**Describe the bug**
Tried to scan library. Error occured: SQLite Error 13: 'database or disk is full'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Dinah.Core.Collections.Generic.IEnumerable_T_Ext.ToDictionarySafe[TKey,TSource](IEnumerable`1 source, Func`2 keySelector, WinnerEnum winner)
   at DtoImporterService.BookImporter.loadLocal_books(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 51
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 36
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\LibraryBookImporter.cs:line 24
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 324
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 143
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77 
**To Reproduce**

**Expected behavior**
I expected Libation to scan my library. 

**Screenshots**
SQLite Error 13: 'database or disk is full'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Dinah.Core.Collections.Generic.IEnumerable_T_Ext.ToDictionarySafe[TKey,TSource](IEnumerable`1 source, Func`2 keySelector, WinnerEnum winner)
   at DtoImporterService.BookImporter.loadLocal_books(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 51
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 36
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at
[Uploading _Log202405.zip…]()
[Uploading _Log202405.zip…]()
 DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\LibraryBookImporter.cs:line 24
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 324
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 143
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Platform**

Windows 11

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
This sounds like your hard drive was filled up by the new books. See if you can move them to another drive and restart Libation.

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
