### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by winterskydragon** [rmcrackan/Libation#934]
**Describe the bug**
I'm getting an error while importing the library.

**To Reproduce**

1. Go to Import
2. Click on Scan library of all accounts
3. See error
 
End of Central Directory record could not be found.

   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 25
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 238
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Expected behavior**
I expected it to start scanning the library

**Platform**
Windows 11 Home

**Log Files**
Attach your Libation log file here.
[Log202407.zip](https://github.com/user-attachments/files/16099092/Log202407.zip)

**Comment by rmcrackan** [comment]
Sorry about this. Thank you for attaching this.

This log file is empty and you seem to be having issues writing to the log file. Either you have one of the older versions of Libation which had a bug related to logging or there's possibly something corrupt about that file. If you're below version v11.1, please upgrade to this -- https://github.com/rmcrackan/Libation/releases/tag/v11.1.0 . Also, delete your log files and see if that clears up any potentially corrupted files. Let me know if either of these works.

**Comment by winterskydragon** [comment]
Hi,
I was on version V11.3.0.1.  I went down to version v11.1.0.  I'm getting this error now, which, I think, is the same error, but it looks like the log file has something in it now.  I have attached it.

End of Central Directory record could not be found.

   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FileManager.LogArchiver..ctor(String filename, Encoding encoding) in D:\a\Libation\Libation\Source\FileManager\LogArchiver.cs:line 25
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 238
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77


[Log202407.zip](https://github.com/user-attachments/files/16131046/Log202407.zip)

**Comment by rmcrackan** [comment]
Thank you for the log file. I'm not sure exactly what's going wrong, but it appears to only be an issue in Debug mode. Unless you have a reason to run in Debug mode, I recommend: open Settings, lower left: change logging level to Information, save, and restart Libation.

**Comment by winterskydragon** [comment]
Thank you.  I'm not sure why it was changed to loggin level Debug, as I don't need it there.
I changed it to Information, and it is now working.
Thank you for your help!

**Comment by rmcrackan** [comment]
Wonderful. Much thanks for the update.
