### ISSUE TITLE
An issue with the date format

### ISSUE THREAD

**Issue by bader515** [rmcrackan/Libation#944]
**Describe the bug:**
I signed in to my account (us), but my PC is set to Saudi Arabia's time zone (UTC+3), so when I try to scan the library I get a date related error.
I searched for a solution, and it appears that the issue is in the date format (yyyy-mm-dd) meanwhile the server is expecting a (yyyy-dd-mm) format.

**To Reproduce:**
Set the time zone of the system to Saudi Arabia and the language to Arabic

**Platform:**
Windows 11 23H2 (22631.3880)

**Log Files:**

```
One or more errors occurred. (String '2024-01-30' was not recognized as a valid DateTime.)

   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 402
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201
```

**Comment by bader515** [comment]
I forget to mention that the error occurs in both Windows versions (classic, chardonnay).

**Comment by amphyvi** [comment]
Having the same issue, but this time it seems there's a `.0` in the `creationTime` field for some reason. This is driving me crazy - if I could just find some way to remove or ignore that `.0` then I would be able to decrypt the audiobook.

This doesn't seem to be related to my date/time settings at all. I changed the format from yyyy-MM-dd to yyyy-dd-MM but nothing changed in the logs. The creation time (11 January 2025) doesn't seem to match the audiobook's release date (31 December 2024) or when I bought it (7 January 2025) so I don't know where the date is coming from. @rmcrackan, could the DateTime be changed manually, or can this just be ignored entirely if not used in file metadata timestamps or something (i.e. the first 2 troubleshooting steps I listed below)? That would at least offer a workaround for date/time issues going forward in situations like this.

I've tried these troubleshooting steps:
- Changing `Set file "created" timestamp to:` -> `File creation date/time`
- Changing `Set file "modified" timestamp to:` -> `File creation date/time`
- Attempting to open the .aaxc file in a text editor to change the creation time
- Checking out AAXClean to see if I can modify the creation time that way, but that's way over my head

```{"md5":(redacted),"payload":{"acr":null,"guid":"_LATEST_","key":(redacted),"type":"AUDI","records":[{"type":"audible.last_heard","creationTime":"2025-01-11 16:20:55.0","startPosition":"8878082"}]}
System.FormatException: String '2025-01-11 16:20:55.0' was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s)
   at AudibleApi.Common.RecordConverter.<ReadJson>g__createRecord|1_0(JObject jObj) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi.Common/RecordDto.cs:line 48
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at AudibleApi.Common.DtoConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi.Common/DtoConverter.cs:line 36
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at AudibleApi.Common.Converter.ReadAsDtoAsync[T](HttpContent content) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi.Common/Converter.cs:line 47```

**Comment by rmcrackan** [comment]
This bug seems to be out of date. If you have more information, please reply here and we can look into it further.

Please try the latest version: https://github.com/rmcrackan/Libation/releases/latest
