### ISSUE TITLE
SqlLite Error 13 Database or disk is full

### ISSUE THREAD

**Issue by Jenlario** [rmcrackan/Libation#962]
Error upon opening libation

SQLite Error 13: 'database or disk is full'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Dinah.Core.Collections.Generic.IEnumerable_T_Ext.ToDictionarySafe[TKey,TSource](IEnumerable`1 source, Func`2 keySelector, WinnerEnum winner)
   at DtoImporterService.BookImporter.loadLocal_books(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 51
   at DtoImporterService.BookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 36
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\LibraryBookImporter.cs:line 24
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 324
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 143
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

**Comment by rmcrackan** [comment]
It sounds like your disk may be at capacity. Does this resolve itself if you move your audiobook files to a separate drive?

**Comment by Jenlario** [comment]
yes thankyou
