### ISSUE TITLE
Can't add audible account

### ISSUE THREAD

**Issue by jchan217** [rmcrackan/Libation#984]
I downloaded the program and was able to convert a few audiobooks; however, after canceling a few in progress, the program would freeze. I would "X" out of Libation and return. I now have an error message that appears when I open Libation that makes it to where I can't sign in to my audible account.

Log:
[_Log202409_006.zip](https://github.com/user-attachments/files/17103079/_Log202409_006.zip)

The error message:

Could not deserialize json: 
   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Dialogs.AccountsDialog.populateGridValues() in D:\a\Libation\Libation\Source\LibationWinForms\Dialogs\AccountsDialog.cs:line 43
   at LibationWinForms.Dialogs.AccountsDialog..ctor() in D:\a\Libation\Libation\Source\LibationWinForms\Dialogs\AccountsDialog.cs:line 28
   at LibationWinForms.Form1.accountsToolStripMenuItem_Click(Object sender, EventArgs e) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.Settings.cs:line 11
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by rmcrackan** [comment]
So sorry about this. Thank you much for your log file. In the folder where your log file live is a file `AccountsSettings.json`. It appears to be corrupted. Delete this file, restart Libation, and re-add your account(s). You will have to log in again but all other progress about previous downloads will be retained. ie: you won't need to download again.
