### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by pixxiesview** [rmcrackan/Libation#987]
After linking my account and trying to import my library I get the following error message. Any help would be greatly appreciated.

Windows 11

**Log Files**
Exception of type 'AudibleApi.ApiErrorException' was thrown.

   at AudibleApi.ApiUnauthenticated.SendClientRequest(IHttpClientActions client, HttpRequestMessage request) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/ApiUnauthenticated [partial].cs:line 53
   at AudibleApi.Api.AdHocAuthenticatedRequestAsync(String requestUri, HttpMethod method, IHttpClientActions client, HttpBody requestBody) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api [partial].cs:line 56
   at AudibleApi.Api.getLibraryResponseAsync(String parameters) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 285
   at AudibleApi.Api.GetItemsCountAsync(LibraryOptions libraryOptions) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 428
   at AudibleApi.Api.GetLibraryItemsPagesAsync(LibraryOptions libraryOptions, Int32 numItemsPerRequest, SemaphoreSlim semaphore)+MoveNext() in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Library.cs:line 375
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at AudibleUtilities.ApiExtended.getItemsAsync(LibraryOptions libraryOptions, Boolean importEpisodes) in D:\a\Libation\Libation\Source\AudibleUtilities\ApiExtended.cs:line 102
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 281
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\MainVM.Import.cs:line 201

**Comment by rmcrackan** [comment]
Sorry about this bug. Is it possible to attach your log file to this ticket?

**Comment by gartnomster** [comment]
I'm getting this same error. I'd attach log files, but I don't see any being created/updated when I get this error. I'm looking for them in the same folder as my AccountSettings.json and other files. Should I be looking elsewhere?

**Comment by rmcrackan** [comment]
@gartnomster no, that's where the log file should be. Have you ever had a successful scan? Or is this error during your first attempt?

**Comment by gartnomster** [comment]
Yeah, it was working successfully for a while. I even had one time where I got the error, re-scanned and it was fine the second time around. Now it's either scanning without throwing an error, but new audiobooks don't show up or I get the error.

**Comment by rmcrackan** [comment]
But not log file? That is very strange.

Without a log to check, my best guess is that maybe the AccountSettings.json file got corrupted. It's happed to a few people lately who are running Libation version 11.1. You can backup/rename/delete your existing AccountSettings.json, restart Libation, and re-create your account/s in Libation. This will require logging in again. [More recent pre-releases](https://github.com/rmcrackan/Libation/releases) should have this bug fixed. I'm not positive when I'll release the next full version.

**Comment by gartnomster** [comment]
I thought the same thing about the AccountSettings.json and gave that a try earlier. I don't know if it'll be of any use to you, but I got a black Audible Login screen
![image](https://github.com/user-attachments/assets/d2ee1761-2ed7-4d82-ab4e-b08349ac82f7)

I'll give the pre-release a try

**Comment by gartnomster** [comment]
11.5.1 seems to work just fine!
